#!/usr/bin/env python3
"""Generate FireOpsSim skill-support catalog JSON. Source of truth after generation: data/skill-support/*.json"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from skill_support_lib import SHARED_SOURCES, drill, mode, q, res, skill, src  # noqa: E402

ROOT = Path(__file__).resolve().parents[1] / "data" / "skill-support"


def dump(name, payload):
    ROOT.mkdir(parents=True, exist_ok=True)
    path = ROOT / name
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT.parent.parent)} ({len(payload.get('skills', payload.get('catalogFiles', [])))} items)")


# ---------------------------------------------------------------------------
# Driver / Operator — Pumper
# ---------------------------------------------------------------------------

def cert_do_pumper():
    return {
        "id": "driver_operator_pumper",
        "title": "Driver / Operator — Pumper",
        "shortTitle": "D/O Pumper",
        "careerStage": "driver",
        "category": "Driver / Operator",
        "aliases": [
            "driver operator", "driver operator pumper", "do pumper", "dop",
            "engineer", "pump operator", "pumper operator", "driver operator 1",
            "apparatus operator", "chauffeur",
        ],
        "summary": "Safe apparatus operation, placement, water supply, pump systems, hydraulics, troubleshooting, and fireground communication as one integrated role.",
        "skills": [
            skill(
                id="do_pumper_hydrant_ops",
                certificationId="driver_operator_pumper",
                title="Hydrant Operations",
                aliases=["hydrant", "hydrant supply", "hydrant connection", "pressurized water supply", "hydrant to engine"],
                category="Water Supply",
                careerStage="driver",
                summary="Connect a reliable hydrant supply, manage intake pressure, watch residual, and communicate before changing demand.",
                whyItMatters="Most urban structure fires succeed or fail on whether the first engine actually has the water the fire needs. Hydrant work is not just hooking a hose — it is reading the system while the incident changes.",
                learningPoints=[
                    "A hydrant is a connection to a water system with limits. Static pressure is not available flow.",
                    "Residual pressure is the best early warning that the system is being asked for more than it can comfortably give.",
                    "Intake pressure, gated intake control, and valve speed protect the pump, the water main, and the people on the lines.",
                    "Communicate before opening additional lines, starting a master stream, or making a large change in supply.",
                    "Department SOP, hydrant wrench/adapter package, and local water-system quirks beat any generic sequence.",
                ],
                beforeYouDo=[
                    "Know which hydrant is the assigned source and whether it is on the same main as nearby hydrants.",
                    "Confirm the apparatus intake, gated valve, LDH/supply hose, and steamer/outlet adapters for this engine.",
                    "Agree who works the hydrant, who watches the panel, and how you will say “hold,” “open,” and “shut down.”",
                ],
                terminology=[
                    {"term": "Static pressure", "meaning": "Hydrant/system pressure with no fire-department flow yet."},
                    {"term": "Residual pressure", "meaning": "Pressure remaining while water is flowing. A falling residual means demand is catching up to supply."},
                    {"term": "Intake / compound gauge", "meaning": "What the pump is seeing on the supply side. Watch it as lines open."},
                    {"term": "Steamer outlet", "meaning": "The large hydrant outlet usually used for LDH supply."},
                    {"term": "Gate the intake", "meaning": "Control water into the pump instead of slamming the system open or shut."},
                ],
                safetyNotes=[
                    "Never straddle hose that may charge. Charge and valve movement can injure.",
                    "Open and close hydrant valves slowly to limit water-hammer and main damage.",
                    "Do not assume a charged supply line is a completed water supply. Confirm intake and residual.",
                    "If residual is falling hard, do not add large additional demand until supply is improved or attack is adjusted.",
                    "Follow department traffic, hydrant-location, and apparatus-placement rules. The hydrant firefighter is in the street.",
                ],
                seeResources=[
                    res("Hydrant Flow Calculator", "/hydrant-flow-calculator.html", "Practice static/residual/available-flow relationships.", "calculator"),
                    res("Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Water-supply and demand-change problems.", "scenario"),
                ],
                practiceResources=[
                    res("Hydrant Flow Calculator", "/hydrant-flow-calculator.html", "Estimate available flow from test data.", "calculator"),
                    res("Pump Pressure Calculator", "/fire-pump-calculator.html", "Connect supply decisions to discharge pressure.", "calculator"),
                    res("Fire Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Changing fire-flow demand.", "scenario"),
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Engineer study hub.", "guide"),
                    res("Visual Scenario Player", "/scenario-player.html", "Pump-panel decision practice.", "simulator"),
                ],
                drill=drill(
                    "Establish hydrant-to-engine water, monitor residual/intake, and communicate before changing demand.",
                    "Engine, hydrant kit, supply hose/LDH, hydrant wrench, gated intake as equipped, radios.",
                    "Use an approved hydrant or a training hydrant/sim. Brief roles: hydrant firefighter, pump operator, officer. State the objective and the stop signal.",
                    mode(
                        "5-minute review",
                        "Walk the hydrant connection and communication sequence without charging if water is not available. Name who talks, what is confirmed, and what “open it” actually means for your department.",
                        ["Correct hose/outlet choice", "Slow valve operation named", "Intake confirmation named", "Radio words agreed"],
                        ["Skipping the gated intake", "No confirmation that water is at the pump", "Vague ‘you got it’ instead of a clear report"],
                        ["What is the first thing the pump operator should see after the hydrant is opened?", "When would we not open a second large discharge?"],
                    ),
                    mode(
                        "15-minute supply evolution",
                        "Deploy the supply line, make the hydrant, establish water to the engine, and place one attack line in service. Operator reports static, residual, and intake. Then add or shut a second line and report what changed.",
                        ["Hydrant made per SOP", "Slow valve operation", "Intake established", "Residual reported", "Demand change communicated"],
                        ["Opening the hydrant wide immediately", "Kinks in LDH ignored", "No one watching residual when the second line opens"],
                        ["What did residual do when the second line opened?", "What would you do if residual dropped below your department’s comfort number?"],
                    ),
                    mode(
                        "30-minute company scenario",
                        "Run an engine-company scenario with changing fire flow: initial attack line, second line, then a high-flow request (deck gun or two more lines — tabletop the high flow if the site cannot support it). Operator must keep a water-supply picture and say when the system is approaching its limit. Include a communication failure and a kink/intake problem to troubleshoot.",
                        ["Placement supports supply and later units", "Supply established before high demand", "Clear residual/intake reports", "Crew told before major water changes", "Problem identified without guessing"],
                        ["Treating hydrant connection as ‘done’ and walking away", "Adding a master stream on a weak residual", "No plan if this hydrant is a dog"],
                        ["When should we take a second hydrant or start a relay?", "Who owns the decision to refuse additional flow?"],
                    ),
                ),
                readinessQuestions=[
                    q("A residual pressure that is falling while you add lines most likely means:",
                      ["The pump is overheating", "The water system is approaching the flow it can give at that hydrant", "The attack line nozzle is too small", "The hydrant is a dry barrel and cannot be used"],
                      1, "Residual is the live picture of remaining system capacity. Falling residual while demand rises is the warning to stop adding large flow or improve supply."),
                    q("Before making a major change in water supply or adding a large discharge, the operator should:",
                      ["Wait until someone complains about low pressure", "Communicate the change and check intake/residual", "Open every gated intake at once", "Increase RPM first, then look at gauges"],
                      1, "People on the line, later-arriving apparatus, and the water system all need a heads-up. Look at supply gauges, then act."),
                    q("Which sign suggests the water system is approaching available flow?",
                      ["Rising residual with stable RPM", "Intake climbing with no discharge open", "Rapidly falling residual, hunting intake, or cavitation signs as flow increases", "A warm pump panel in cold weather"],
                      2, "The system tells you through residual, intake, and pump noise/feel. Do not wait for a line to go flat."),
                    q("Hydrant valves should generally be operated:",
                      ["As fast as possible to get water", "Slowly, to limit water hammer and control intake", "Only by the officer", "Only after the fire is knocked down"],
                      1, "Controlled valve movement protects mains, hydrants, hose, and the pump."),
                ],
                officialSources=src("nfa", "proboard", "ifsac") + [
                    {"label": "Department SOP/SOG and apparatus manual", "url": "/driver-operator-practice.html", "scope": "Your hydrant sequence, valve package, and pump panel are apparatus- and department-specific."},
                    {"label": "Local water authority / hydrant records", "url": "/hydrant-inspection-log.html", "scope": "Flow tests, main sizes, and out-of-service hydrants are local data, not FireOpsSim estimates."},
                ],
                relatedSkills=["do_pumper_engage_pump", "do_pumper_friction_loss", "do_pumper_multiple_attack_lines", "do_pumper_relay_pumping", "do_pumper_standpipe_fdc", "do_pumper_apparatus_placement", "do_pumper_troubleshooting"],
                searchKeywords=["hydrant", "residual", "intake", "water supply", "LDH", "steamer", "available flow", "engineer"],
            ),
            skill(
                id="do_pumper_pump_theory",
                certificationId="driver_operator_pumper",
                title="Pump Theory",
                aliases=["pump theory", "centrifugal pump", "net pump pressure", "cavitation", "priming"],
                category="Hydraulics",
                careerStage="driver",
                summary="Understand how a centrifugal fire pump makes pressure, why it needs water at the eye of the impeller, and what gauges are telling you.",
                whyItMatters="Formulas fail in the street if the operator does not know what the machine is doing. Pump theory is how you recognize cavitation, loss of prime, and useless RPM.",
                learningPoints=[
                    "A centrifugal pump moves water with an impeller. It does not ‘suck’ well if air is in the impeller eye.",
                    "Net pump pressure is about the work the pump is doing between intake and discharge — not a single magic number on one gauge.",
                    "Cavitation is water turning to vapor at the impeller because intake conditions cannot feed the pump. It damages the pump and starves lines.",
                    "Priming is for drafting/air at the impeller. A pressurized hydrant supply is a different problem than a dry pump.",
                    "Manufacturer and department pump-mode procedures (transfer valve, pressure/volume, governor/relief) outrank generic diagrams.",
                ],
                beforeYouDo=["Identify transfer valve, primer, intake, tank-to-pump, and governor/relief on THIS apparatus.", "Know whether you are on tank, hydrant, or draft before changing RPM."],
                terminology=[
                    {"term": "Impeller", "meaning": "Rotating component that adds energy to the water."},
                    {"term": "Prime", "meaning": "Removing air so the impeller is water-filled and can pump."},
                    {"term": "Cavitation", "meaning": "Vapor bubbles forming and collapsing at the impeller from inadequate intake conditions."},
                    {"term": "Pressure vs volume mode", "meaning": "How some two-stage pumps are set for higher pressure or higher volume."},
                ],
                safetyNotes=["Do not run a dry pump. Follow apparatus limits for tank water and primer use.", "Unusual noise, vibration, or a discharge gauge that will not rise with RPM is a stop-and-diagnose cue."],
                seeResources=[res("Driver / Operator Practice", "/driver-operator-practice.html", "Engineer concepts and scenarios.", "guide")],
                practiceResources=[
                    res("Pumper Flashcards", "/driver-operator-pumper-flashcards.html", "Active recall on pump and hydraulics terms.", "flashcards"),
                    res("Pump Pressure Calculator", "/fire-pump-calculator.html", "Connect theory to PDP practice.", "calculator"),
                    res("Fire Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Apply theory to problems.", "scenario"),
                ],
                drill=drill(
                    "Explain pump mode, priming, and cavitation signs on the assigned apparatus, then diagnose two common failures.",
                    "Assigned pumper (or pump panel trainer), department pump chart, radios.",
                    "Walk around the panel. No live pumping required for the 5-minute version. Use tank water only if authorized.",
                    mode("5-minute review", "Point to primer, tank-to-pump, intakes, transfer valve, and governor/relief. State when each is used.", ["Correct identification", "Correct ‘when’ for primer vs hydrant"], ["Calling every problem ‘cavitation’", "Priming on a hydrant supply by habit"], ["When do we prime? When do we not?"]),
                    mode("15-minute panel talk-through", "Give three conditions: tank water to a preconnect, hydrant supply, then a noisy pump with falling intake. Operator states actions in order.", ["Correct first action", "Gauge interpretation", "When to stop adding RPM"], ["Revving the engine to ‘make pressure’ with no water", "Ignoring intake"], ["What would you tell the officer?"]),
                    mode("30-minute diagnosis drill", "Run or tabletop: loss of prime, gated intake left closed, and a weak hydrant. Operator must change one variable at a time.", ["Systematic troubleshooting", "Communication", "No dry-pump operation"], ["Changing three things at once", "Leaving the crew uninformed"], ["Which clue separated cavitation from a closed valve?"]),
                ),
                readinessQuestions=[
                    q("A centrifugal fire pump generally needs which condition at the impeller to work?",
                      ["Air in the impeller eye", "Water filling the impeller", "The relief valve fully open", "The parking brake released"],
                      1, "No water at the impeller means no reliable pumping. That is why prime and intake matter."),
                    q("Cavitation is best understood as:",
                      ["Too much foam in the tank", "Vapor forming at the impeller because the pump is being asked for more than intake can supply", "A hydrant that is a wet barrel", "Normal governor hunting"],
                      1, "Fix supply/intake or reduce demand. More RPM often makes cavitation worse."),
                    q("Priming is typically associated with:",
                      ["A charged hydrant supply that already fills the pump", "Removing air so a dry or drafting pump can move water", "Setting the aerial outriggers", "Opening the tank fill"],
                      1, "Do not treat priming as a generic ‘start the pump’ step on a pressurized supply unless your apparatus procedure says so."),
                ],
                officialSources=src("nfa") + [{"label": "Apparatus manufacturer pump manual", "url": "/driver-operator-practice.html", "scope": "Pump mode, primer, and cavitation limits are apparatus-specific."}],
                relatedSkills=["do_pumper_engage_pump", "do_pumper_drafting", "do_pumper_troubleshooting", "do_pumper_friction_loss"],
                searchKeywords=["pump theory", "impeller", "cavitation", "prime", "net pump pressure", "two stage"],
            ),
            skill(
                id="do_pumper_apparatus_inspection",
                certificationId="driver_operator_pumper",
                title="Daily Apparatus Inspection",
                aliases=["apparatus check", "daily check", "truck check", "morning checks", "pump panel check"],
                category="Readiness",
                careerStage="driver",
                summary="Find the problem in the bay, not on the fireground. Fluids, warning systems, pump, tires, equipment, and documentation.",
                whyItMatters="Most ‘it died on the call’ stories started as a skipped check. Inspection is an operator skill, not busywork.",
                learningPoints=["Use the department sheet as the legal/operational checklist.", "Look, listen, feel, and function-test what policy allows.", "Out-of-service criteria must be known before you need them.", "Document defects. A verbal ‘it’s fine’ is not a record."],
                beforeYouDo=["Get the department inspection form for this apparatus.", "Know who you notify for a defect and what takes the rig out of service."],
                terminology=[{"term": "OOS", "meaning": "Out of service — the apparatus or a system cannot be safely used."}, {"term": "Deficiency vs OOS", "meaning": "Some defects are noted and monitored; others park the rig. Policy decides."}],
                safetyNotes=["Chock, park brake, and exhaust/CO awareness in the bay.", "Do not disable warning systems to ‘pass’ a check.", "High-voltage hybrid/electric apparatus follow manufacturer rules."],
                practiceResources=[
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Organize inspection learning points.", "guide"),
                    res("Focus Drills — apparatus check", "/focus-drills.html?level=driver_operator&topic=apparatus%20check", "Timed daily-check drill.", "drill"),
                ],
                drill=drill(
                    "Complete a documented daily check emphasizing pump, water, warning systems, and equipment readiness.",
                    "Assigned apparatus, department inspection sheet, flashlight, PPE as required.",
                    "Start from a known ‘ready’ or intentionally seeded training defect if the training officer allows.",
                    mode("5-minute review", "List the five things that would park THIS rig this morning.", ["Department OOS items named"], ["Generic internet checklist"], ["What is our notification path?"]),
                    mode("15-minute walk-around", "Run the department sheet. Report one finding, even if ‘no defects.’", ["Form complete", "Pump/water items checked", "Defects documented"], ["Skipping top-side or pump panel", "Signing without looking"], ["What did you actually function-test?"]),
                    mode("30-minute readiness drill", "Full check plus a ‘missing tool / low oil / inop warning light’ inject. Crew restores or correctly OOS’s the unit.", ["Correct OOS decision", "Communication", "Equipment restored or tagged"], ["Hiding a defect to stay in service"], ["Who has authority to OOS?"]),
                ),
                readinessQuestions=[
                    q("The primary checklist for a daily apparatus inspection is:",
                      ["A generic social-media list", "The department form plus manufacturer/out-of-service rules", "Whatever the last driver remembered", "Only the pump panel"],
                      1, "Liability and readiness live on the department sheet."),
                    q("A warning-system defect should be:",
                      ["Ignored if the engine starts", "Documented and handled per OOS/notification policy", "Reset by pulling a fuse", "Left for the next shift without comment"],
                      1, "Warning systems are how the public and the crew get a chance to see you."),
                    q("Why document a minor deficiency that does not OOS the rig?",
                      ["To fill the log", "So the next operator and maintenance see the trend before it fails on a call", "It is not necessary", "Only if an officer asks"],
                      1, "Trends are how pumps, tires, and governors fail ‘suddenly.’"),
                ],
                officialSources=src("nfa") + [{"label": "Department inspection SOP and manufacturer manual", "url": "/driver-operator-practice.html", "scope": "Inspection content and OOS criteria are local and apparatus-specific."}],
                relatedSkills=["do_pumper_engage_pump", "do_pumper_troubleshooting"],
                searchKeywords=["inspection", "daily check", "apparatus", "out of service", "fluids", "warning lights"],
            ),
            skill(
                id="do_pumper_engage_pump",
                certificationId="driver_operator_pumper",
                title="Engage Pump",
                aliases=["pump engagement", "put it in pump", "pump shift", "pump mode"],
                category="Pump Operations",
                careerStage="driver",
                summary="Position, shift to pump, confirm pump mode, tank-to-pump or supply, and a charged first line without guessing.",
                whyItMatters="The first 60 seconds of pumping set up everything that follows. A missed shift confirmation is a dry line at the door.",
                learningPoints=["Follow the exact manufacturer/department sequence for THIS transmission and pump.", "Confirm pump mode with indicators, not hope.", "Know whether the first water is tank or hydrant.", "Set a pressure control device before the line gets away from you."],
                beforeYouDo=["Spot the apparatus so pump panel, intakes, and later units can work.", "Know the first-line package (length, GPM, nozzle pressure)."],
                terminology=[{"term": "Pump shift", "meaning": "Transferring driveline power to the fire pump per apparatus design."}, {"term": "Tank-to-pump", "meaning": "Onboard water feeding the pump until a supply is established."}],
                safetyNotes=["Parking brake and wheel chocks per SOP before pumping.", "Do not leave the cab until the shift is confirmed if that is your procedure.", "Watch for open discharges and personnel in front of lines."],
                seeResources=[res("Fire Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Engage-and-supply problems.", "scenario")],
                practiceResources=[
                    res("Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Decision sequence practice.", "scenario"),
                    res("Pump Pressure Calculator", "/fire-pump-calculator.html", "First-line PDP.", "calculator"),
                    res("Visual Scenario Player", "/scenario-player.html", "Panel decisions under a picture.", "simulator"),
                ],
                drill=drill(
                    "Engage the pump per department procedure and place the standard first line in service with a pressure-control setting.",
                    "Assigned pumper, attack line, water source authorized for training.",
                    "Chocks, radio, and a safety officer. Use tank water only if the site and policy allow.",
                    mode("5-minute review", "Say the engage-pump sequence out loud, including confirmation cues.", ["Order correct", "Confirmation named"], ["Skipping chock/brake", "Assuming the light means water is at the nozzle"], ["What tells you the pump is actually in pump?"]),
                    mode("15-minute first line", "Engage pump, tank-to-pump, charge the standard preconnect, set governor/relief, report pressures.", ["Sequence", "Pressure control on", "Clear report"], ["Charging before the nozzle firefighter is ready", "No relief/governor"], ["What pressure did you choose and why?"]),
                    mode("30-minute transition", "First line on tank, then transition to hydrant without losing the line. Include a failed pump-shift inject if training-safe.", ["Transition without interruption", "Communication", "Intake watched"], ["Dumping the tank with no supply plan", "Leaving RPM unmanaged"], ["When do we leave tank water and why?"]),
                ),
                readinessQuestions=[
                    q("The safest way to know the pump is engaged is:",
                      ["The parking brake is set", "Follow apparatus indicators/procedure, not assumption", "The siren still works", "Someone yelled ‘pump’"],
                      1, "Each apparatus has confirmation cues. Learn them."),
                    q("Pressure control (governor/relief) should be:",
                      ["Set after a line already surged", "Part of placing the first line in service", "Only used on relays", "Left off so you can ‘feel’ the pump"],
                      1, "It is how you keep a firefighter from being launched by a sudden pressure spike."),
                    q("Tank-to-pump is used to:",
                      ["Fill the booster tank from a hydrant only", "Supply the pump from onboard water until a source is established", "Prime a hydrant", "Cool the transmission"],
                      1, "Have a supply plan before the tank is gone."),
                ],
                officialSources=src("nfa") + [{"label": "Apparatus manufacturer operating instructions", "url": "/driver-operator-practice.html", "scope": "Pump-shift steps differ by make, model, and transmission."}],
                relatedSkills=["do_pumper_hydrant_ops", "do_pumper_friction_loss", "do_pumper_apparatus_inspection", "do_pumper_troubleshooting"],
                searchKeywords=["engage pump", "pump shift", "tank to pump", "governor", "relief valve", "preconnect"],
            ),
            skill(
                id="do_pumper_friction_loss",
                certificationId="driver_operator_pumper",
                title="Friction Loss and PDP",
                aliases=["friction loss", "pdp", "pump discharge pressure", "hydraulics", "c value"],
                category="Hydraulics",
                careerStage="driver",
                summary="Estimate pump discharge pressure from nozzle pressure, hose friction, elevation, and appliances — then sanity-check the number.",
                whyItMatters="A wrong PDP either starves the nozzle or overpressures people and hose. The math is a starting point; the gauges and the nozzle firefighter tell you if it is working.",
                learningPoints=["PDP ≈ NP + FL + elevation + appliance (department formula may vary).", "Friction loss rises with flow and length and depends on hose diameter/C-value.", "Your department hose/nozzle package matters more than a textbook example.", "If the number does not match what the gauges and the line are doing, believe the fireground."],
                beforeYouDo=["Know the target NP and GPM for the line you are pumping.", "Know department C-values or pump chart for assigned hose."],
                terminology=[{"term": "PDP", "meaning": "Pump discharge pressure — what you are trying to produce for that line."}, {"term": "FL", "meaning": "Friction loss in the hose/appliances between pump and nozzle/device."}, {"term": "C-value", "meaning": "Coefficient used in common training formulas for a hose diameter at a given flow."}],
                safetyNotes=["Do not chase a formula into an unsafe pressure.", "Elevation and long lays change everything — re-calculate when the layout changes."],
                seeResources=[
                    res("Friction Loss Calculator", "/friction-loss-calculator.html", "Work FL from flow, length, and C.", "calculator"),
                    res("Friction Loss Table", "/friction-loss-table.html", "See how diameter and flow change FL.", "calculator"),
                ],
                practiceResources=[
                    res("Friction Loss Calculator", "/friction-loss-calculator.html", "Line-specific FL practice.", "calculator"),
                    res("Pump Pressure Calculator", "/fire-pump-calculator.html", "Full PDP practice.", "calculator"),
                    res("Attack Line Calculator", "/attack-line-calculator.html", "Single-line layouts.", "calculator"),
                    res("Friction Loss Practice Problems", "/friction-loss-practice-problems.html", "Reps.", "practice"),
                    res("Pumper Flashcards", "/driver-operator-pumper-flashcards.html", "Recall.", "flashcards"),
                ],
                drill=drill(
                    "Calculate PDP for the department’s standard lines, then compare the estimate to a pump-chart or instructor target.",
                    "Calculator or pump chart, sample hose layouts, radios optional.",
                    "Classroom or bay. Use actual department line packages, not random textbook numbers.",
                    mode("5-minute review", "Compute PDP for the standard 1¾ preconnect. Say each component.", ["NP, FL, elevation, appliance named"], ["Skipping elevation", "Using the wrong GPM"], ["What would 100 more feet do?"]),
                    mode("15-minute chart vs calc", "Three layouts: preconnect, 2½, and a long lay. Compare calculator to department chart.", ["Correct GPM/NP", "Reasonable FL", "Difference explained"], ["Mixing diameters in one formula blindly"], ["When do we trust the chart over the calculator?"]),
                    mode("30-minute live or tabletop pump", "Pump a training line if authorized; otherwise tabletop gauge pictures. Match PDP to nozzle performance and adjust.", ["Estimate then verify", "Communication with nozzle"], ["Never looking at the gauge after the math"], ["What told you the formula was off?"]),
                ),
                readinessQuestions=[
                    q("If hose length doubles and flow stays the same, friction loss generally:",
                      ["Stays the same", "Approximately doubles", "Drops by half", "Depends only on RPM"],
                      1, "FL is proportional to length in the common training model."),
                    q("A calculated PDP is:",
                      ["An official required discharge pressure", "A training estimate to be checked against gauges, nozzle, and SOP", "Always higher than 200 psi", "Only for relay pumping"],
                      1, "FireOpsSim calculators are training tools, not policy."),
                    q("Increasing GPM on the same hose will generally:",
                      ["Lower friction loss", "Raise friction loss sharply", "Never affect PDP", "Only affect elevation"],
                      1, "Flow has a large effect (often modeled with a square relationship)."),
                ],
                officialSources=src("nfa") + [{"label": "Department pump chart / hose-nozzle package", "url": "/pump-card-builder.html", "scope": "Operational target pressures come from the AHJ and the hose you actually carry."}],
                relatedSkills=["do_pumper_engage_pump", "do_pumper_multiple_attack_lines", "do_pumper_hydrant_ops", "do_pumper_master_streams"],
                searchKeywords=["friction loss", "pdp", "hydraulics", "c value", "nozzle pressure", "engineer math"],
            ),
            skill(
                id="do_pumper_multiple_attack_lines",
                certificationId="driver_operator_pumper",
                title="Multiple Attack Lines",
                aliases=["multiple lines", "second line", "two lines", "adding a line"],
                category="Pump Operations",
                careerStage="driver",
                summary="Keep pressure, supply, and communication stable when a second or third line opens or shuts.",
                whyItMatters="The fire does not wait while you re-do math. Opening another line changes flow, residual, and every existing discharge.",
                learningPoints=["Each additional line is more GPM from the same pump and the same water system.", "Tell the officer and the lines before you change a lot of water.", "Watch residual and intake as much as discharge.", "Know which line is which on the panel."],
                beforeYouDo=["Know estimated GPM of each line in service.", "Have supply established or a tank plan that can survive the extra line."],
                terminology=[{"term": "Discharge", "meaning": "A gated outlet on the pump panel feeding a specific line or device."}, {"term": "Pressure governor", "meaning": "Can hold pressure as flow changes — still watch supply."}],
                safetyNotes=["A sudden shut-down of one line can spike pressure on another if pressure control is wrong or off.", "Do not steal the attack line’s water to feed a vanity layout."],
                seeResources=[res("Wye / Siamese Calculator", "/wye-siamese-calculator.html", "Split-flow layouts.", "calculator")],
                practiceResources=[
                    res("Fire Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Demand changes.", "scenario"),
                    res("Scenario Player", "/scenario-player.html", "Visual multi-line problems.", "simulator"),
                    res("Wye / Siamese Calculator", "/wye-siamese-calculator.html", "Branch lines.", "calculator"),
                    res("Attack Line Calculator", "/attack-line-calculator.html", "Per-line PDP.", "calculator"),
                ],
                drill=drill(
                    "Place two attack lines in service, report what residual/intake did, then shut one down without surprising the remaining line.",
                    "Pumper, two attack lines, authorized water, radios.",
                    "Brief who calls for the second line and how the operator acknowledges.",
                    mode("5-minute review", "Talk through adding a second line: supply check, communication, then open.", ["Order of actions"], ["Opening first, talking later"], ["What do we tell the first nozzle?"]),
                    mode("15-minute two-line pump", "One line, then second line, then one shutdown. Operator reports gauges each time.", ["Pressure control used", "Supply watched", "Clear IDs of lines"], ["Mixing discharges", "No residual check"], ["Which gauge moved first?"]),
                    mode("30-minute fire-flow scenario", "Changing request: second line, then a third or a high-flow device (tabletop if needed). Operator must say when supply cannot support it.", ["Limit recognized", "Officer informed", "Lines labeled"], ["Silent panel while the fire grows"], ["What is our next water move?"]),
                ),
                readinessQuestions=[
                    q("When a second attack line opens, the operator should first be thinking about:",
                      ["Siren use", "Additional flow vs remaining supply and existing line pressures", "Only foam", "Turning off the first line automatically"],
                      1, "Flow has to come from somewhere."),
                    q("Shutting down one of two lines can:",
                      ["Never affect the other line", "Spike pressure on the remaining line if pressure control is not managing it", "Always drop residual", "Prime the pump"],
                      1, "Pressure control and communication exist for this moment."),
                    q("The officer asks for a third line while residual is already falling. Best operator action:",
                      ["Open it immediately to be a team player", "Report the supply picture and the risk, then follow the officer’s informed decision / improve supply", "Leave the panel to pull the line", "Increase RPM only"],
                      1, "Give the officer the water facts. Do not silently exceed the system."),
                ],
                officialSources=src("nfa") + [{"label": "Department pumping SOP", "url": "/fire-pump-training-scenarios.html", "scope": "Line designations, color codes, and target pressures are local."}],
                relatedSkills=["do_pumper_hydrant_ops", "do_pumper_friction_loss", "do_pumper_master_streams", "do_pumper_troubleshooting"],
                searchKeywords=["multiple lines", "second line", "discharge", "governor", "flow demand"],
            ),
            skill(
                id="do_pumper_master_streams",
                certificationId="driver_operator_pumper",
                title="Master Stream Operations",
                aliases=["master stream", "deck gun", "monitor", "elevated stream"],
                category="High Flow",
                careerStage="driver",
                summary="High-flow devices need water, reaction awareness, supply, and a reason — not just a bigger nozzle.",
                whyItMatters="A master stream can overwhelm a hydrant, a pump, and a building. It is a tactical tool with a supply problem attached.",
                learningPoints=["Know the device GPM and NP before you open it.", "Confirm supply can support that flow.", "Reaction, collapse, and stream direction are safety problems, not decorations.", "Transitioning to or from handlines changes everything on the panel."],
                beforeYouDo=["Estimate needed flow vs hydrant/tank reality.", "Know whether this is deck gun, portable monitor, or aerial waterway — they are not the same."],
                terminology=[{"term": "Master stream", "meaning": "High-capacity stream from a monitor, deck gun, or waterway — typically hundreds of GPM."}, {"term": "Reaction", "meaning": "Force trying to push the device/apparatus."}],
                safetyNotes=["Do not staff an unsafe portable monitor.", "Watch collapse zones and electrical hazards.", "Do not take the handline’s last water to feed a gun without a plan."],
                seeResources=[
                    res("Master Stream Calculator", "/master-stream-calculator.html", "Supply-line and NP planning.", "calculator"),
                    res("Deck Gun Calculator", "/deck-gun-calculator.html", "Apparatus-mounted stream pressure and reaction.", "calculator"),
                ],
                practiceResources=[
                    res("Master Stream Calculator", "/master-stream-calculator.html", "High-flow PDP practice.", "calculator"),
                    res("Deck Gun Calculator", "/deck-gun-calculator.html", "Deck-gun specific.", "calculator"),
                    res("Hydrant Flow Calculator", "/hydrant-flow-calculator.html", "Can this hydrant support the gun?", "calculator"),
                    res("Pump Training Scenarios", "/fire-pump-training-scenarios.html", "High-flow demand.", "scenario"),
                ],
                drill=drill(
                    "Decide whether a master stream is supply-supported, then tabletop or flow a training stream if authorized.",
                    "Flow data, calculators, apparatus if authorized, radios.",
                    "If you cannot flow a gun, tabletop the numbers and the placement.",
                    mode("5-minute review", "Name GPM, supply need, and one reason you would refuse the gun.", ["Number named", "Safety named"], ["‘Open it and see’"], ["What hydrant picture do we need first?"]),
                    mode("15-minute calc + placement", "Work a 500–1000 GPM request against a hydrant estimate. Place the rig for later units.", ["Supply vs demand", "Placement"], ["Ignoring reaction"], ["If residual is 25 psi while flowing 250, do we add 750?"]),
                    mode("30-minute evolution", "Authorized flow or full tabletop: handline, then gun request, then back. Operator keeps a water narrative.", ["Transition", "Communication", "Limit recognized"], ["Silent high-flow"], ["When does the gun become a liability?"]),
                ),
                readinessQuestions=[
                    q("Before opening a master stream, the operator needs:",
                      ["Only the officer’s enthusiasm", "A flow target, a supply that can support it, and a safe device/crew setup", "The tank fill open", "Foam in every case"],
                      1, "High flow without supply is a show, then a failure."),
                    q("A portable monitor should be:",
                      ["Staffed in the collapse zone to ‘aim better’", "Set and operated per department/manufacturer rules, with reaction considered", "Supplied by a garden hose", "Opened before the supply line is charged"],
                      1, "Uncontrolled reaction injures people."),
                    q("If residual collapses when the gun opens, you should:",
                      ["Keep it open to ‘win’", "Reduce demand and/or improve supply and tell command", "Close the hydrant completely", "Switch to tank water only and hope"],
                      1, "Give command the water facts immediately."),
                ],
                officialSources=src("nfa") + [{"label": "Device and apparatus manufacturer instructions", "url": "/master-stream-calculator.html", "scope": "Flow, NP, and reaction limits are equipment-specific."}],
                relatedSkills=["do_pumper_multiple_attack_lines", "do_pumper_hydrant_ops", "do_pumper_friction_loss"],
                searchKeywords=["master stream", "deck gun", "monitor", "high flow", "reaction"],
            ),
            skill(
                id="do_pumper_relay_pumping",
                certificationId="driver_operator_pumper",
                title="Relay Pumping",
                aliases=["relay", "ldh relay", "source pumper", "in-line pumping"],
                category="Water Supply",
                careerStage="driver",
                summary="Move water a long distance with more than one pump: roles, intake targets, communications, and failure recognition.",
                whyItMatters="Relays fail from silence and ego, not from math. Every engine needs a role, an intake target, and a way to say ‘hold.’",
                learningPoints=["Source, relay, and attack pumpers have different jobs.", "Intake pressure at the next engine is the product, not dump pressure for sport.", "Talk before you change RPM a lot.", "Plan for a burst, a kink, or a dropped hydrant."],
                beforeYouDo=["Know LDH diameter, lay length, and target flow.", "Assign radio words for increase/decrease/hold."],
                terminology=[{"term": "Source pumper", "meaning": "The engine at the water source."}, {"term": "Relay / in-line pumper", "meaning": "Boosts pressure in the supply line toward the fire."}, {"term": "Attack pumper", "meaning": "The engine supplying fire streams."}],
                safetyNotes=["Do not overpressure LDH.", "Traffic and hose crossings on long lays.", "Never assume the next engine saw your gauge."],
                seeResources=[res("Relay Pumping Calculator", "/relay-pumping-calculator.html", "Spacing and FL estimates.", "calculator")],
                practiceResources=[
                    res("Relay Pumping Calculator", "/relay-pumping-calculator.html", "Segment planning.", "calculator"),
                    res("Relay Pumping Training", "/relay-pumping-training.html", "Role-based practice.", "guide"),
                    res("Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Relay problems.", "scenario"),
                ],
                drill=drill(
                    "Assign source/relay/attack roles, set an intake target, and practice the communication loop for a pressure change.",
                    "Map or cones, radios, calculators, two or more engines if available — otherwise tabletop.",
                    "Even a tabletop with three people works: source, relay, attack.",
                    mode("5-minute review", "Name the three roles and one radio phrase for ‘hold.’", ["Roles correct"], ["Everyone pumping ‘as hard as they can’"], ["Who owns intake at the attack engine?"]),
                    mode("15-minute tabletop relay", "Given a long lay and a flow, pick spacing with the calculator and brief the comms plan.", ["Spacing reasonable", "Intake target named"], ["No failure plan"], ["What if the middle engine dies?"]),
                    mode("30-minute evolution or full tabletop", "Change flow twice. Each pumper reports intake/discharge. Inject a kink or lost source.", ["Comms before RPM", "Failure handled"], ["Silent pressure wars"], ["What would make you abort the relay?"]),
                ),
                readinessQuestions=[
                    q("The attack pumper in a relay primarily cares about:",
                      ["How impressive the source RPM looks", "Stable intake and enough flow for the fire streams", "Closing all discharges", "Drafting on a hydrant"],
                      1, "Intake at the fire engine is the point of the relay."),
                    q("Before increasing RPM significantly in a relay, operators should:",
                      ["Wait 10 minutes", "Communicate the change so the next engine is not surprised", "Shut the hydrant", "Switch to tank water"],
                      1, "Silence creates overpressure and cavitation."),
                    q("A relay is a good tool when:",
                      ["The fire is small and a preconnect would do", "The source is far and one engine cannot deliver the needed flow/pressure alone", "You want to avoid hydrants in town", "The officer is not on scene"],
                      1, "Match the water method to the distance and demand."),
                ],
                officialSources=src("nfa") + [{"label": "Department LDH / relay SOP", "url": "/relay-pumping-training.html", "scope": "Hose ratings, intake targets, and engine spacing are AHJ-specific."}],
                relatedSkills=["do_pumper_hydrant_ops", "do_pumper_drafting", "do_pumper_rural_tender", "do_pumper_troubleshooting", "do_pumper_friction_loss"],
                searchKeywords=["relay", "LDH", "source pumper", "in-line", "rural water", "long lay"],
            ),
            skill(
                id="do_pumper_drafting",
                certificationId="driver_operator_pumper",
                title="Drafting",
                aliases=["draft", "static source", "hard suction", "prime from pond"],
                category="Water Supply",
                careerStage="driver",
                summary="Build an airtight suction path, prime, lift water from a static source, and recognize cavitation and air leaks.",
                whyItMatters="Drafting is unforgiving. One air leak or a fouled strainer turns a rural fire into a tank of regrets.",
                learningPoints=["Hard suction must be airtight. Connections and gaskets matter.", "Lift, strainer placement, and primer use follow physics and the manual.", "Watch intake: vacuum that is too high is a warning.", "Have a plan for a lost prime during pumping."],
                beforeYouDo=["Site the engine for lift, hose, and later tenders if used.", "Inspect gaskets and strainer before you need them."],
                terminology=[{"term": "Lift", "meaning": "Vertical distance from water surface to the pump."}, {"term": "Strainer", "meaning": "Keeps debris out of the suction hose; must stay submerged and unobstructed."}, {"term": "Vacuum / compound", "meaning": "Intake-side reading while drafting."}],
                safetyNotes=["Drowning, drop-offs, and ice at static sources.", "Carbon monoxide if idling in a hole or against a wall.", "Do not walk the suction hose once it is under vacuum in an unsafe way."],
                practiceResources=[
                    res("Drafting Fire Pump Training", "/drafting-fire-pump-training.html", "Draft concepts.", "guide"),
                    res("Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Prime and draft problems.", "scenario"),
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Engineer hub.", "guide"),
                    res("Tender Shuttle Calculator", "/tender-shuttle-calculator.html", "When draft is not enough, plan rural water.", "calculator"),
                ],
                drill=drill(
                    "Set up a draft (live or walk-through), prime, and name three failure clues.",
                    "Pumper, hard suction, strainer, approved static source or dry setup, PPE.",
                    "Use a training pond/draft pit if available. Otherwise complete a dry airtight setup and primer talk-through.",
                    mode("5-minute review", "Show gasket, strainer, and primer. State max practical lift as a concept, not a brag.", ["Parts identified"], ["‘It always primes’"], ["Where do air leaks hide?"]),
                    mode("15-minute setup", "Make all connections, strainer in water (or simulated), primer sequence verbalized, failure clues listed.", ["Airtight path", "Strainer submerged conceptually"], ["Dry strainer", "Kinked suction"], ["What does a rising vacuum with no water mean?"]),
                    mode("30-minute draft evolution", "Live draft if authorized; else full tabletop with a lost-prime inject and a tender backup plan.", ["Prime achieved or correctly simulated", "Cavitation recognized", "Backup water named"], ["Revving through cavitation"], ["When do we abandon the draft for a shuttle?"]),
                ),
                readinessQuestions=[
                    q("The most common practical enemy of a draft is:",
                      ["Too much residual pressure", "Air leaks or a strainer that cannot feed the pump", "A wet-barrel hydrant", "Foam"],
                      1, "Air and starved intake stop centrifugal pumps."),
                    q("Hard suction hose is used because:",
                      ["It looks traditional", "It can handle vacuum without collapsing like soft hose", "It has less friction than LDH always", "It stores water"],
                      1, "Soft supply hose is not a substitute for suction hose in a true draft."),
                    q("If the pump cavitates while drafting, a useful first thought is:",
                      ["More RPM", "Reduce demand and check lift, strainer, and air leaks", "Open every discharge", "Turn off the primer forever"],
                      1, "Fix the intake side; do not bully the impeller."),
                ],
                officialSources=src("nfa") + [{"label": "Apparatus primer / pump manufacturer instructions", "url": "/drafting-fire-pump-training.html", "scope": "Primer type, lift limits, and recommended vacuum are apparatus-specific."}],
                relatedSkills=["do_pumper_pump_theory", "do_pumper_relay_pumping", "do_pumper_rural_tender", "do_pumper_troubleshooting"],
                searchKeywords=["draft", "hard suction", "static source", "primer", "strainer", "lift", "rural"],
            ),
            skill(
                id="do_pumper_standpipe_fdc",
                certificationId="driver_operator_pumper",
                title="Standpipe and FDC Operations",
                aliases=["standpipe", "fdc", "fire department connection", "high rise pump", "standpipe support", "sprinkler fdc"],
                category="High-Rise / FDC",
                careerStage="driver",
                summary="Supply a standpipe or sprinkler FDC with the right hose, the right pressure method, and a clear communication loop with the interior crew.",
                whyItMatters="High-rise and sprinklered buildings fail the first engine when the operator treats an FDC like a hydrant with extra hose. Elevation, system loss, and the people on the standpipe outlet all have to be in the same picture.",
                learningPoints=[
                    "An FDC is a building fire-protection inlet. You are pushing water into a system with its own pipes, valves, and losses — not just a long attack line.",
                    "Standpipe PDP is nozzle pressure plus hose on the floor plus elevation plus system/FDC loss. Department charts and the building’s system beat a generic number.",
                    "Confirm the connection: Siamese vs storz, caps, clapper, and whether this FDC actually feeds the standpipe or sprinkler zone you think it does.",
                    "Place the engine so later trucks can still work, LDH can reach, and you are not blocking the building’s only access.",
                    "Talk to the interior/standpipe crew before large pressure changes. They feel your panel before you hear their radio.",
                ],
                beforeYouDo=[
                    "Know this apparatus’ FDC hose, adapters, and whether you pump sprinkler and standpipe from the same inlet.",
                    "Agree who owns pressure: pump operator, officer, or the crew at the standpipe outlet.",
                    "Have a backup if the FDC is damaged, capped wrong, or the system is isolated.",
                ],
                terminology=[
                    {"term": "FDC", "meaning": "Fire department connection — the inlet on the building (or nearby) where the engine supplies the system."},
                    {"term": "Standpipe", "meaning": "Fixed piping that delivers water to hose outlets on upper floors or remote areas."},
                    {"term": "System / FDC loss", "meaning": "Pressure lost in the building piping, valves, and connection — often a department or building-specific allowance."},
                    {"term": "Elevation loss", "meaning": "Pressure needed to lift water to the fire floor. Floor count is a training estimate; the building and SOP win."},
                    {"term": "Siamese", "meaning": "A two-inlet FDC body. Pump both sides unless the system and SOP say otherwise."},
                ],
                safetyNotes=[
                    "Do not assume an FDC is in service. Caps, debris, a closed OS&Y, or a broken clapper can give you a beautiful discharge gauge and no water upstairs.",
                    "Overpressure can damage the system and the hose on the floor. Follow department max PDP and relief/governor practice.",
                    "LDH and charged FDC lines in a driveway are a trip and vehicle hazard. Place, chock, and light as SOP requires.",
                    "If the interior crew reports no water, treat it as a water emergency — not an argument about your math.",
                ],
                seeResources=[
                    res("Standpipe / FDC Calculator", "/standpipe-fdc-calculator.html", "Practice NP, hose FL, system loss, and floor elevation as one PDP.", "calculator"),
                    res("Sprinkler FDC reference", "/sprinkler-fdc-calculator.html", "Sprinkler-support landing page and department-pressure reminder.", "calculator"),
                ],
                practiceResources=[
                    res("Standpipe / FDC Calculator", "/standpipe-fdc-calculator.html", "Estimate FDC pressure from NP, FL, system loss, and floors.", "calculator"),
                    res("Sprinkler / FDC page", "/sprinkler-fdc-calculator.html", "Separate sprinkler-support searches from standpipe work.", "calculator"),
                    res("Pump Pressure Calculator", "/fire-pump-calculator.html", "Same hydraulics building blocks used on the panel.", "calculator"),
                    res("Scenario Library", "/scenario-library.html", "Standpipe and high-rise practice problems.", "scenario"),
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Engineer study hub.", "guide"),
                ],
                drill=drill(
                    "Connect and pump an FDC (live or tabletop), state the pressure method, and communicate before changing PDP.",
                    "Engine, LDH/supply to FDC, adapters/caps wrench, radios, standpipe/FDC calculator or department chart, building photo or training FDC.",
                    "Use a training FDC or a tabletop building. Brief: operator, hydrant/supply firefighter, interior/standpipe voice. Name the stop signal and max PDP.",
                    mode(
                        "5-minute review",
                        "Walk the FDC: caps, inlets, what it feeds, hose choice, and who talks. Name every term in the PDP stack for this building without charging if water is not available.",
                        ["Correct FDC identification", "PDP stack named", "Interior communication named", "Backup if FDC is dead"],
                        ["Calling it ‘just another hydrant’", "No plan if the connection is clogged", "Vague ‘I usually pump 150’"],
                        ["What does this FDC actually supply?", "What is the first radio sentence if upstairs reports no water?"],
                    ),
                    mode(
                        "15-minute supply evolution",
                        "Make the FDC, establish supply, and set an initial PDP from the calculator or chart. Then change floors or add a second line (tabletop the second line if the site cannot support it). Operator reports PDP, intake/residual, and what changed.",
                        ["Connection per SOP", "Pressure method stated", "Supply watched while PDP changed", "Interior told before the change"],
                        ["Pumping a number with no floor or hose story", "Ignoring intake while chasing PDP", "No confirmation water is in the system"],
                        ["What would you do if PDP is correct and the floor still has no water?", "When would you refuse a higher-pressure request?"],
                    ),
                    mode(
                        "30-minute high-rise / sprinkler scenario",
                        "Run a building scenario: first connection, a clogged or one-sided FDC inject, then a floor change or sprinkler vs standpipe question. Operator must keep supply, PDP, and the interior picture together. Include a later-arriving truck that needs the spot you took.",
                        ["Placement leaves later access", "FDC problem diagnosed without guessing", "Clear PDP and water reports", "Crew told before major pressure changes"],
                        ["Blocking the aerial or the only driveway", "Raising PDP instead of checking the connection", "Silent panel while the standpipe crew is dry"],
                        ["How do we tell standpipe support from sprinkler support on this building?", "Who owns the decision to abandon this FDC?"],
                    ),
                ),
                readinessQuestions=[
                    q("Pump discharge pressure for a standpipe assignment is best thought of as:",
                      ["Whatever residual the hydrant showed", "Nozzle pressure plus hose on the fire floor plus elevation plus system/FDC loss, using the department method", "Always 150 psi because that is a common classroom number", "Intake pressure times two"],
                      1, "Stack the pieces. The building, the hose package, and SOP decide the number — not a slogan."),
                    q("If the interior crew reports no water at the standpipe outlet while your discharge gauge looks healthy, a useful first thought is:",
                      ["Tell them to open the nozzle more", "Check the FDC/path into the system, valves, and whether you are actually supplying that zone", "Double RPM immediately", "Shut down and leave"],
                      1, "A pretty panel does not prove water is in the riser. Find the break in the path."),
                    q("Many FDCs are two-inlet bodies. Unless SOP and the system say otherwise, engines should usually:",
                      ["Pump one inlet so the other stays pretty", "Supply both inlets", "Avoid FDC work and draft from a planter", "Cap both inlets after charging"],
                      1, "Two inlets exist to move volume into the system and to have a backup path. Follow the local connection rule."),
                    q("Before a large PDP increase to an FDC, the operator should:",
                      ["Wait until hose bursts", "Tell the interior/standpipe crew and watch supply gauges", "Open every discharge on the panel", "Switch to tank water"],
                      1, "People on the line feel your change. Supply has to support it."),
                ],
                officialSources=src("nfa", "proboard", "ifsac") + [
                    {"label": "Department high-rise / FDC SOP and apparatus pump chart", "url": "/driver-operator-practice.html", "scope": "FDC hose, adapters, max PDP, and standpipe vs sprinkler assignments are AHJ- and building-specific."},
                    {"label": "Building fire-protection information / preplan", "url": "/scenario-library.html", "scope": "Which FDC feeds which system, and whether a connection is in service, is local building data."},
                ],
                relatedSkills=["do_pumper_hydrant_ops", "do_pumper_friction_loss", "do_pumper_apparatus_placement", "do_pumper_multiple_attack_lines", "do_pumper_troubleshooting"],
                searchKeywords=["standpipe", "FDC", "high rise", "sprinkler", "elevation", "siamese", "fire department connection", "engineer"],
            ),
            skill(
                id="do_pumper_rural_tender",
                certificationId="driver_operator_pumper",
                title="Rural Water and Tender Shuttle",
                aliases=["tender shuttle", "tanker shuttle", "rural water", "fill site", "dump site", "nurse tanker", "portable tank"],
                category="Water Supply",
                careerStage="driver",
                summary="Keep fire flow coming when there is no hydrant: tank duration, fill and dump sites, shuttle math, and the radio loop that actually delivers water.",
                whyItMatters="Rural fires run out of water in minutes if the first engine treats tank water as infinite. Shuttle success is cycle time and jobs — not how many tenders are ‘en route.’",
                learningPoints=[
                    "Tank duration is working water divided by flow. Reserve exists so you can still move the engine or protect a crew when the shuttle hiccups.",
                    "Sustained shuttle GPM is usable gallons per tender divided by cycle time, times the number of tenders actually completing the loop.",
                    "Cycle time is fill + travel + dump + travel + turnaround. The slowest step, not the fastest truck, sets the flow.",
                    "Fill site, dump site, nurse, and attack pumper are different jobs. Mixing them on the radio is how water stops.",
                    "Drafting, a relay, or a second fill site may beat adding another tender that has nowhere to dump.",
                ],
                beforeYouDo=[
                    "Know this engine’s tank size, usable water, and the department reserve rule.",
                    "Name the fill site, dump method (portable tank, nurse, jet dump), and who owns traffic at each end.",
                    "Agree the radio words for ‘hold dump,’ ‘need water,’ and ‘fill site delay.’",
                ],
                terminology=[
                    {"term": "Cycle time", "meaning": "Minutes for one tender to fill, travel, dump, return, and turn around."},
                    {"term": "Dump site", "meaning": "Where tenders offload — portable tanks, a nurse pumper, or a jet-dump into a tank."},
                    {"term": "Fill site", "meaning": "Hydrant, draft, or other source where tenders reload."},
                    {"term": "Nurse", "meaning": "A pumper (or tender/pumper) that stays and supplies the attack engine while others shuttle."},
                    {"term": "Working tank water", "meaning": "Usable tank gallons minus the reserve you refuse to burn."},
                ],
                safetyNotes=[
                    "Dump sites and fill sites are vehicle, drop-off, and drowning hazards. Spotters and lighting matter at night.",
                    "Do not dump into a collapsing tank or onto charged hose.",
                    "Traffic control is part of water supply. A wrecked tender is zero GPM.",
                    "If tank water is about to die, the officer needs that sentence immediately — interior crews are using water they think they have.",
                ],
                seeResources=[
                    res("Tender Shuttle Calculator", "/tender-shuttle-calculator.html", "Tank, fill, dump, travel, and tender count to sustained GPM.", "calculator"),
                    res("Tender Timer", "/tender-timer.html", "Cycle time, delivered GPM, and tenders needed for a target flow.", "calculator"),
                ],
                practiceResources=[
                    res("Tender Shuttle Calculator", "/tender-shuttle-calculator.html", "Estimate shuttle flow from cycle pieces.", "calculator"),
                    res("Tender Timer", "/tender-timer.html", "Distance, speed, and target-flow planning.", "calculator"),
                    res("Tank Duration Calculator", "/tank-duration.html", "How long this engine’s tank lasts at the current flow.", "calculator"),
                    res("Relay Pumping Calculator", "/relay-pumping-calculator.html", "When a long LDH lay beats a weak shuttle.", "calculator"),
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Engineer study hub.", "guide"),
                ],
                drill=drill(
                    "Plan a rural water supply: tank duration, shuttle or relay choice, fill/dump jobs, and the radio loop before the tank hits reserve.",
                    "Engine tank figure, radios, tender/shuttle calculator, map or cones for fill and dump, optional portable tank.",
                    "Tabletop is enough if you cannot move tenders. Assign attack pump, dump-site boss, and at least one tender driver. State the stop signal.",
                    mode(
                        "5-minute review",
                        "Given tank size and a fire flow, compute working time with a reserve. Name fill site, dump site, and the first radio sentence when time is short.",
                        ["Duration computed", "Reserve named", "Jobs named", "Shortage radio sentence ready"],
                        ["Ignoring reserve", "Calling every truck a ‘tanker’ with no job", "Waiting until the tank is empty to talk"],
                        ["How many minutes of working water do we have?", "Who do we call first for more water?"],
                    ),
                    mode(
                        "15-minute shuttle plan",
                        "Use the tender calculators to build a cycle: fill, dump, travel, tender count, target GPM. Compare to tank duration. Decide shuttle vs draft/relay. Brief the radio words.",
                        ["Cycle time stated", "Sustained GPM vs need", "Fill and dump jobs clear", "Backup method named"],
                        ["Counting tenders that have not been given a fill site", "No dump-site plan", "Math with no radio plan"],
                        ["What step in the cycle is the bottleneck?", "When would we switch to a relay or a second fill site?"],
                    ),
                    mode(
                        "30-minute rural scenario",
                        "Run or tabletop a working fire: initial tank attack, first tender dump, a fill-site delay inject, then a flow increase. Operator must keep tank duration honest and say when the shuttle cannot meet demand. Include a portable-tank or nurse decision.",
                        ["Tank time watched", "Shuttle jobs held under stress", "Shortage reported early", "Plan B used without chaos"],
                        ["Silent tank death", "Tenders circling with no dump site", "Raising fire flow with no water math"],
                        ["What would make you tell the officer to cut flow?", "How do we keep one tender from blocking the dump site?"],
                    ),
                ),
                readinessQuestions=[
                    q("The most useful first rural-water question on arrival is:",
                      ["How shiny are the tenders?", "How long will this tank last at the flow we are about to use, and what is the next water?", "What is static hydrant pressure in town?", "Should we wait to stretch until every tender arrives?"],
                      1, "Tank duration plus a next-water plan is the rural clock."),
                    q("Shuttle flow goes up most honestly when you:",
                      ["Count every apparatus on the printout as a working tender", "Shorten real cycle time or add tenders that can actually complete the loop", "Open a second attack line with no dump site", "Idle the fill site to ‘save the hydrant’"],
                      1, "GPM is gallons that finish the cycle, divided by minutes. Fantasy units do not dump."),
                    q("If fill time doubles because the fill site is poorly staffed, shuttle GPM will:",
                      ["Stay the same because travel did not change", "Fall, because cycle time got longer", "Double", "Only affect the attack engine’s intake color"],
                      1, "Every slow step is in the denominator."),
                    q("The officer should hear that tank water is short:",
                      ["At the critique", "As soon as working time will not cover the next stretch of the fire", "Only after the pump sucks air", "Never — handle it on the panel"],
                      1, "Interior decisions assume water that may already be gone."),
                ],
                officialSources=src("nfa") + [
                    {"label": "Department rural water / tender SOP", "url": "/tender-shuttle-calculator.html", "scope": "Fill sites, dump methods, portable-tank rules, and reserve gallons are AHJ-specific."},
                    {"label": "Apparatus tank and dump-valve manufacturer data", "url": "/tank-duration.html", "scope": "Usable tank gallons and dump rates are apparatus-specific."},
                ],
                relatedSkills=["do_pumper_drafting", "do_pumper_relay_pumping", "do_pumper_hydrant_ops", "do_pumper_troubleshooting", "do_pumper_apparatus_placement"],
                searchKeywords=["tender", "tanker", "shuttle", "rural", "fill site", "dump site", "portable tank", "nurse", "tank duration", "engineer"],
            ),
            skill(
                id="do_pumper_apparatus_placement",
                certificationId="driver_operator_pumper",
                title="Apparatus Placement",
                aliases=["engine placement", "spot the rig", "where to park", "first due placement", "arrival position", "don't block"],
                category="Placement",
                careerStage="driver",
                summary="Stop the engine where the hose, water, rescue path, later units, and a way out all still work — then set the brake and own that decision.",
                whyItMatters="A bad spot is a permanent tactical problem. You can recut a line. You cannot un-park a blocked aerial or a hydrant you drove past with no plan.",
                learningPoints=[
                    "Placement is a size-up skill: occupancy, fire location, access, water, collapse/overhead, and who is coming after you.",
                    "First engine usually owns a working spot for attack and water — not the front door selfie. Leave the aerial, ambulance, and later engines a path.",
                    "Hydrant vs fire: know whether this department lays in, lays out, or spots at the building and waits for water. Do not invent a third method in the driveway.",
                    "Once the parking brake is set, you still own wheel chocks, pump engagement setup, and a way to move if command orders it.",
                    "Say the placement out loud if it is non-obvious: ‘taking the hydrant side, leaving the front for the truck.’",
                ],
                beforeYouDo=[
                    "Know first-due hose loads, LDH, and whether you are expected to hit a hydrant before the building.",
                    "Know typical later-arriving apparatus for this alarm (truck, rescue, second engine) and what they need.",
                    "Have a backup spot if the driveway, wires, or parked cars steal the textbook position.",
                ],
                terminology=[
                    {"term": "Working spot", "meaning": "A position that lets this company do its job without stealing the next company’s job."},
                    {"term": "Lay in / lay out", "meaning": "Department water-supply driving pattern — hydrant first vs building first. Follow yours."},
                    {"term": "Collapse zone", "meaning": "Area to keep clear of people and apparatus if the building or wall can come down."},
                    {"term": "Egress for apparatus", "meaning": "A way to get this rig or later rigs out — not a dead-end jammed with hose."},
                ],
                safetyNotes=[
                    "Do not spot under wires, dying walls, or on known collapse sides just to be close.",
                    "Never leave the apparatus in drive on a grade. Brake, chock, and follow department wheel-chock rules.",
                    "Personnel in the street while you spot: the hydrant firefighter and later units. Slow is part of the skill.",
                    "Do not block hydrants, FDCs, or the only aerial corner because the address felt urgent.",
                ],
                seeResources=[
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Arrival scenes that include first-engine placement choices.", "simulator"),
                    res("Focus Drills — placement", "/focus-drills.html?level=driver_operator&topic=placement", "Tabletop spotting reps.", "drill"),
                ],
                practiceResources=[
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Read the scene, then defend where the engine would stop.", "simulator"),
                    res("Hydrant Operations skill", "/skill-support.html?cert=driver_operator_pumper&task=do_pumper_hydrant_ops", "Water supply is why many spots exist.", "skill"),
                    res("Standpipe / FDC skill", "/skill-support.html?cert=driver_operator_pumper&task=do_pumper_standpipe_fdc", "High-rise spots must leave FDC and later trucks.", "skill"),
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Engineer hub.", "guide"),
                    res("Focus Drills — Driver/Operator", "/focus-drills.html?level=driver_operator&topic=placement", "Placement tabletop in the drill library.", "drill"),
                ],
                drill=drill(
                    "Choose and defend an engine spot for three different arrivals, including water, later units, and a way out.",
                    "Printed or projected arrival photos, cones or a parking lot, radios, department hose/hydrant SOP.",
                    "No live pumping required. Use photos first, then walk a station apron or training lot if available. Officer or instructor plays later-arriving truck.",
                    mode(
                        "5-minute review",
                        "From one photo, point to where this engine stops, where the hydrant or FDC is, and what you left for the truck. Say it in one radio sentence.",
                        ["Spot named", "Water plan named", "Later unit considered", "One-sentence report"],
                        ["Nose on the front door with no water story", "Blocking the aerial corner", "Silent ‘I just park’"],
                        ["What would make you take a worse-looking spot that is actually better?", "Who is coming after us?"],
                    ),
                    mode(
                        "15-minute three-spot tabletop",
                        "Three scenes: house fire with a hydrant past the address, garden apartment narrow lane, and a standpipe building. Operator spots each, then the instructor steals one option (parked car, wires, blocked hydrant). Adjust without losing water or later access.",
                        ["Three defensible spots", "Adjustment when the first choice dies", "Hose/water method matches SOP"],
                        ["Same spot for every building", "No collapse or overhead look", "Hydrant forgotten until the line is dry"],
                        ["Which scene would you hydrant first?", "What do you tell command if you cannot get the textbook spot?"],
                    ),
                    mode(
                        "30-minute lot or scenario",
                        "On a training lot or with cones, spot for attack, then a second engine and a truck arrive. Include a ‘move up’ order and a hose that will trap you if you dump it in the only egress. Debrief with the decision sim on a similar occupancy.",
                        ["Chocks/brake called", "Later units can work", "Egress not suicided with hose", "Spot explained, not guessed"],
                        ["Final parking wherever the bumper stopped", "No chocks", "Arguing instead of taking the next best hole"],
                        ["When is a farther spot the safer pump position?", "How do we move if command needs the hole?"],
                    ),
                ),
                readinessQuestions=[
                    q("A good first-engine spot is one that:",
                      ["Looks closest to the fire in the windshield", "Lets this company work water and hose while leaving a path for later units and a way out", "Blocks the driveway so nobody else can mess it up", "Always sits on the address side regardless of hydrant or wires"],
                      1, "You are parking a water-and-hose platform inside a larger incident, not winning a closeness contest."),
                    q("If the only close spot sits under wires on a working fire side, the operator should:",
                      ["Take it anyway because seconds matter more than overhead", "Choose the next working spot that does not put the crew and rig under that hazard, and say so", "Wait in the street with the pump in road", "Park on the sidewalk and leave the brake off"],
                      1, "A burned windshield is slower than fifty extra feet of hose from a survivable hole."),
                    q("Department lay-in / lay-out / hydrant-then-building patterns exist so that:",
                      ["Every driver can freelance", "Water and hose get to the fire the way this agency trained", "The aerial always has to wait", "You never need a hydrant firefighter"],
                      1, "Placement and water supply are one SOP. Do not invent a third pattern in the dark."),
                    q("After the brake is set, apparatus placement is:",
                      ["Finished forever", "Still your problem if command needs the hole, hose traps the rig, or the spot is unsafe", "The officer’s alone", "Only about how it photographs"],
                      1, "You can be asked to move. Chocks, hose, and a remaining path make that possible."),
                ],
                officialSources=src("nfa") + [
                    {"label": "Department apparatus placement / first-due SOP", "url": "/driver-operator-practice.html", "scope": "Hydrant sequence, spotting rules, and later-unit access are AHJ-specific."},
                    {"label": "Apparatus manufacturer parking-brake and chock instructions", "url": "/driver-operator-practice.html", "scope": "How this rig is secured on a grade is apparatus-specific."},
                ],
                relatedSkills=["do_pumper_hydrant_ops", "do_pumper_standpipe_fdc", "do_pumper_engage_pump", "do_pumper_rural_tender"],
                searchKeywords=["placement", "spot", "park", "first due", "don't block", "aerial access", "hydrant lay", "engineer"],
            ),
            skill(
                id="do_pumper_troubleshooting",
                certificationId="driver_operator_pumper",
                title="Pump and Supply Troubleshooting",
                aliases=["troubleshooting", "no water", "cavitation", "loss of prime", "pressure problem"],
                category="Troubleshooting",
                careerStage="driver",
                summary="Change one variable at a time: supply, valves, air, restrictions, cavitation, governor, then the discharge side.",
                whyItMatters="Panic makes operators twist everything. Method makes water come back.",
                learningPoints=["Start with: do I have water at the pump?", "Then: is a valve wrong?", "Then: is the pump cavitating or out of prime?", "Then: is the problem on the discharge/hose/nozzle side?", "Tell the officer what you know, not a novel."],
                beforeYouDo=["Know the panel well enough to find tank-to-pump, intakes, and discharges in the dark.", "Keep a light and a hydrant wrench where you always keep them."],
                terminology=[{"term": "Intake restriction", "meaning": "Kink, closed gate, debris, or a weak source starving the pump."}, {"term": "Discharge problem", "meaning": "Closed gate, kink, burst, or nozzle issue after the pump."}],
                safetyNotes=["Do not stand over charged lines while ‘fixing’ blindly.", "A burst LDH is a violent event."],
                practiceResources=[
                    res("Pump Training Scenarios", "/fire-pump-training-scenarios.html", "Failure injects.", "scenario"),
                    res("Scenario Player", "/scenario-player.html", "Visual troubleshooting.", "simulator"),
                    res("Driver / Operator Practice", "/driver-operator-practice.html", "Structured study.", "guide"),
                    res("Focus Drills — troubleshooting", "/focus-drills.html?level=driver_operator&topic=troubleshooting", "Panel cards.", "drill"),
                ],
                drill=drill(
                    "Diagnose three seeded problems using a one-variable-at-a-time method and a short radio report.",
                    "Pump panel or training cards, radios, optional live pump.",
                    "Instructor seeds: closed intake, kink, wrong discharge, weak residual, or primer issue.",
                    mode("5-minute review", "Recite the order: water at pump → valves → cavitation/prime → discharge.", ["Order correct"], ["Guessing foam first"], ["What is your first gauge glance?"]),
                    mode("15-minute cards", "Three scenario cards. Operator states first check and the radio sentence.", ["Method", "Concise report"], ["Changing three valves at once"], ["What did you tell command?"]),
                    mode("30-minute live or panel", "Seeded faults on an authorized evolution or a full tabletop with time pressure.", ["Correct diagnosis", "Crew not left dry without a warning"], ["Silent failure"], ["How fast should the officer hear there is a water problem?"]),
                ),
                readinessQuestions=[
                    q("Best first question when a line goes soft:",
                      ["Is the radio on scan?", "Do I still have water at the pump (intake/tank) and an open path to that discharge?", "Should I add foam?", "Should I pull a second engine immediately without looking?"],
                      1, "Locate the failure. Supply and valves first."),
                    q("Changing several controls at once is a problem because:",
                      ["It looks decisive", "You cannot tell what actually fixed or broke the situation", "Pumps require it", "Officers prefer it"],
                      1, "One variable at a time is how you learn and how you recover."),
                    q("The officer needs to hear a water problem:",
                      ["At the critique tomorrow", "As soon as you know attack water is in doubt", "Only if the tank is empty", "Never — handle it quietly"],
                      1, "Interior crews make life decisions based on water they think they have."),
                ],
                officialSources=src("nfa") + [{"label": "Apparatus troubleshooting section / department pumping SOP", "url": "/driver-operator-practice.html", "scope": "Governor modes, primer faults, and valve layouts are apparatus-specific."}],
                relatedSkills=["do_pumper_pump_theory", "do_pumper_hydrant_ops", "do_pumper_engage_pump", "do_pumper_drafting", "do_pumper_standpipe_fdc", "do_pumper_multiple_attack_lines"],
                searchKeywords=["troubleshoot", "no pressure", "cavitation", "kink", "closed valve", "loss of water"],
            ),
        ],
    }


def build_index(certs):
    stages = [
        {"id": "candidate", "label": "Candidate", "blurb": "Hiring, CPAT, and academy prep", "certIds": []},
        {"id": "probationary", "label": "Probationary", "blurb": "First 100 shifts", "certIds": ["probationary_firefighter"]},
        {"id": "firefighter", "label": "Firefighter", "blurb": "Firefighter I and II", "certIds": ["firefighter_1", "firefighter_2"]},
        {"id": "driver", "label": "Driver/Operator", "blurb": "Pumper operations", "certIds": ["driver_operator_pumper"]},
        {"id": "officer", "label": "Company Officer", "blurb": "Fire Officer I", "certIds": ["fire_officer_1"]},
        {"id": "instructor", "label": "Instructor", "blurb": "Fire Instructor I", "certIds": ["fire_instructor_1"]},
        {"id": "specialty", "label": "Specialty", "blurb": "HazMat Operations", "certIds": ["hazmat_operations"]},
    ]
    catalog_files = [f"{c['id']}.json" for c in certs]
    practice = [
        {"title": "Hydrant Flow Calculator", "url": "/hydrant-flow-calculator.html", "keywords": ["hydrant", "flow", "residual", "water supply"], "type": "calculator", "certificationId": "driver_operator_pumper", "skillId": "do_pumper_hydrant_ops"},
        {"title": "Pump Pressure Calculator", "url": "/fire-pump-calculator.html", "keywords": ["pdp", "pump", "friction loss", "engineer"], "type": "calculator", "certificationId": "driver_operator_pumper", "skillId": "do_pumper_friction_loss"},
        {"title": "Standpipe / FDC Calculator", "url": "/standpipe-fdc-calculator.html", "keywords": ["standpipe", "fdc", "high rise", "elevation"], "type": "calculator", "certificationId": "driver_operator_pumper", "skillId": "do_pumper_standpipe_fdc"},
        {"title": "Tender Shuttle Calculator", "url": "/tender-shuttle-calculator.html", "keywords": ["tender", "tanker", "shuttle", "rural water"], "type": "calculator", "certificationId": "driver_operator_pumper", "skillId": "do_pumper_rural_tender"},
        {"title": "SCBA Air Management Calculator", "url": "/scba-air-management-calculator.html", "keywords": ["scba", "air", "cylinder"], "type": "calculator", "certificationId": "firefighter_1", "skillId": "ff1_scba"},
        {"title": "Fireground Decision Sim", "url": "/fireground-decision-sim.html", "keywords": ["size up", "strategy", "tactics", "FO1", "placement"], "type": "simulator", "certificationId": "driver_operator_pumper", "skillId": "do_pumper_apparatus_placement"},
        {"title": "Fireground Decision Sim (officer)", "url": "/fireground-decision-sim.html", "keywords": ["size up", "strategy", "tactics", "FO1"], "type": "simulator", "certificationId": "fire_officer_1", "skillId": "fo1_size_up"},
        {"title": "Focus Drills + Skill Wheel", "url": "/focus-drills.html", "keywords": ["drill", "wheel", "15 minute", "company drill"], "type": "drill"},
        {"title": "Hose Advancement Checklist", "url": "/hose-advancement-checklist.html", "keywords": ["hose", "attack line", "probation"], "type": "checklist", "skillId": "probation_hose_advancement"},
        {"title": "Ventilation Checklist", "url": "/ventilation-checklist.html", "keywords": ["ventilation", "ff2", "flow path"], "type": "checklist", "skillId": "ff2_ventilation"},
        {"title": "Driver/Operator Practice Hub", "url": "/driver-operator-practice.html", "keywords": ["engineer", "pumper", "driver operator"], "type": "guide", "certificationId": "driver_operator_pumper"},
    ]
    return {
        "schemaVersion": 1,
        "updatedAt": "2026-08-28",
        "purpose": "FireOpsSim Skill Support Engine catalog. Learning and practice only — not official Taskbook completion.",
        "disclaimer": "FireOpsSim training guidance is not an official skill sheet, NFPA standard, state certification requirement, or department policy. Completing a session never marks a Roadmap task complete. Verify current SOPs, manufacturer instructions, and the issuing authority.",
        "catalogFiles": catalog_files,
        "stages": stages,
        "sharedSources": list(SHARED_SOURCES.values()),
        "practiceCatalog": practice,
        "candidateResources": [
            {"label": "Become a Firefighter", "url": "/become-a-firefighter.html", "note": "Hiring path and academy prep"},
            {"label": "CPAT Preparation", "url": "/cpat-preparation.html", "note": "Physical ability prep"},
            {"label": "Firefighter I skills", "url": "/skill-support.html?cert=firefighter_1", "note": "Academy fundamentals"},
        ],
    }


def dump_handoff(certs):
    skills = []
    for cert in certs:
        for item in cert.get("skills") or []:
            skills.append({
                "certificationId": cert["id"],
                "certificationTitle": cert.get("shortTitle") or cert.get("title"),
                "skillId": item["id"],
                "title": item["title"],
                "url": f"/skill-support.html?cert={cert['id']}&task={item['id']}",
            })
    dump("handoff.json", {
        "schemaVersion": 1,
        "updatedAt": "2026-08-28",
        "purpose": "Stable FireOpsSim Skill Support URLs for FireOps Career Road Taskbook and Daily Focus handoffs. Completing a session never marks a Roadmap task complete.",
        "sessionPage": "/skill-support.html",
        "dailyFocus": {
            "currentRoadmapUrl": "/focus-drills.html",
            "behavior": "When source=roadmap, FireOpsSim redirects Daily Focus links to Skill Support. Skill Support accepts task, task_id, cert, certification, qualification, level, requirement, requirement_id, topic/title, goal, state, and return_url.",
            "levelToCert": {
                "probationary": "probationary_firefighter",
                "firefighter_1": "firefighter_1",
                "firefighter_2": "firefighter_2",
                "hazmat_ops": "hazmat_operations",
                "driver_operator": "driver_operator_pumper",
                "officer_1": "fire_officer_1",
                "instructor_1": "fire_instructor_1",
            },
        },
        "skills": skills,
    })


def main():
    from skill_packs_ff import cert_ff1
    from skill_packs_ops import cert_ff2, cert_hazmat
    from skill_packs_lead import cert_fo1, cert_fi1, cert_probation

    certs = [
        cert_probation(),
        cert_ff1(),
        cert_ff2(),
        cert_hazmat(),
        cert_do_pumper(),
        cert_fo1(),
        cert_fi1(),
    ]
    dump("index.json", build_index(certs))
    dump_handoff(certs)
    for cert in certs:
        dump(f"{cert['id']}.json", cert)
    n = sum(len(c["skills"]) for c in certs)
    print(f"total skills: {n}")


if __name__ == "__main__":
    main()

