"""Firefighter II, HazMat Ops, Fire Officer I, Fire Instructor I, Probationary packs."""
from skill_support_lib import drill, mode, q, res, skill, src


def _std_drill(obj, equip, setup, r5, r15, r30):
    return drill(obj, equip, setup, mode(*r5), mode(*r15), mode(*r30))


def cert_ff2():
    return {
        "id": "firefighter_2",
        "title": "Firefighter II",
        "shortTitle": "FF II",
        "careerStage": "firefighter",
        "category": "Firefighting",
        "aliases": ["firefighter 2", "firefighter ii", "ff2", "ff ii"],
        "summary": "Coordinated company operations: ventilation decisions, extrication support, foam, preplanning, radio reports, and evidence-aware overhaul.",
        "skills": [
            skill(
                id="ff2_ventilation",
                certificationId="firefighter_2",
                title="Coordinated Ventilation",
                aliases=["ventilation", "vent", "flow path", "coordinated vent", "vertical ventilation"],
                category="Ventilation",
                careerStage="firefighter",
                summary="Choose opening location and timing with suppression and search — not as a separate sport.",
                whyItMatters="Firefighter II is where you stop ‘taking the roof because we always do’ and start making the fire behave on purpose.",
                learningPoints=["State the exhaust, the inlet, and who is in the flow path before you cut or break.", "Changing conditions can make yesterday’s good hole today’s blowtorch.", "PPV/PPA is a coordinated tactic with rules, not a default.", "Vertical ventilation needs a sound roof, staffing, and an objective."],
                beforeYouDo=["Fire location, attack progress, search status.", "Department PPV and roof policy."],
                terminology=[{"term": "Coordination", "meaning": "The opening happens when the line and search can use the change."}, {"term": "Flow path", "meaning": "Inlet to exhaust route for air and fire gases."}],
                safetyNotes=["Uncoordinated vertical vent can pull fire through crews.", "Saw work on a roof is a fall/collapse problem first."],
                seeResources=[res("Ventilation Checklist", "/ventilation-checklist.html", "Coordination checklist.", "checklist")],
                practiceResources=[
                    res("Ventilation Checklist", "/ventilation-checklist.html", "Plan the opening.", "checklist"),
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Changing conditions.", "simulator"),
                    res("Focus Drills — FF2 vent", "/focus-drills.html?level=firefighter_2&topic=ventilation", "Decision drill.", "drill"),
                    res("FSRI Fire Safety Academy", "https://training.fsri.org/", "Research-based dynamics.", "official"),
                ],
                drill=_std_drill(
                    "Given changing fire conditions, coordinate ventilation timing, location, and assignments with suppression and search.",
                    "Scenario images, radios, charged line or tabletop, ventilation tools as assigned.",
                    "Tabletop or tower. No freelance openings.",
                    ("5-minute review", "From one photo, name inlet, intended exhaust, and who must be ready.", ["Coordination named"], ["Roof by habit"], ["Who can stop the cut?"]),
                    ("15-minute decision set", "Three evolving cards: kitchen fire with search, basement, and a wind-driven hint. Pick openings and timing.", ["Why/where/when"], ["Vent opposite the crew"], ["What smoke change confirms it worked?"]),
                    ("30-minute company drill", "Line in place, search assigned, then a ventilation order. Inject ‘too early’ and ‘wrong side.’", ["Wait for water", "Correct location"], ["Independent truck work"], ["Did we help the search or the fire?"]),
                ),
                readinessQuestions=[
                    q("The difference between FF I support vent and FF II coordinated vent is mainly:", ["Bigger saws", "Owning the decision of whether, where, and when with the rest of the incident", "Never using windows", "Always cutting a trench"], 1, "Judgment is the skill."),
                    q("If search is in the planned exhaust path, you should:", ["Vent anyway for the video", "Change the plan — do not push fire over people", "Only use PPV", "Wait for the news helicopter"], 1, "People beat holes."),
                    q("PPV without a coordinated exhaust and a charged line:", ["Always works", "Can push fire and products into unburned spaces and people", "Is required by every SOP", "Replaces water"], 1, "Fans change flow path on purpose — or by accident."),
                ],
                officialSources=src("fsri", "nfa", "niosh") + [{"label": "Department ventilation / PPV SOP", "url": "/ventilation-checklist.html", "scope": "Fan use and roof operations are local."}],
                relatedSkills=["ff1_ventilation", "ff2_company_tactics", "fo1_size_up", "ff1_fire_attack"],
                searchKeywords=["ventilation", "flow path", "PPV", "roof", "coordination", "ff2"],
            ),
            skill(
                id="ff2_vehicle_extrication",
                certificationId="firefighter_2",
                title="Vehicle Extrication Support",
                aliases=["extrication", "rescue", "stabilize the car", "jaws", "vehicle rescue"],
                category="Rescue",
                careerStage="firefighter",
                summary="Stabilize, create a work plan, and support patient access with approved tools — without becoming a victim of traffic or energy.",
                whyItMatters="Cars store energy. Traffic keeps moving. The patient is not helped by a rushed, unstabilized cut.",
                learningPoints=["Scene size-up: traffic, fuel, hybrid/EV, airbags, occupants.", "Stabilize before you cut, when that is the plan.", "Tool staging and roles beat a pile of iron at the C-post.", "Know operations-level limits vs technician rescue."],
                beforeYouDo=["Department vehicle-rescue SOP and the tools on YOUR rig.", "PPE including eye/ear as required."],
                terminology=[{"term": "Stabilization", "meaning": "Making the vehicle’s movement predictable before interior work."}, {"term": "Crib / strut", "meaning": "Common stabilization methods — use what you carry and are trained on."}],
                safetyNotes=["Traffic is the killer on many ‘simple’ wrecks.", "Undeployed airbags and high-voltage systems are not guesses — follow current department/EV guidance.", "Never crawl under an unstabilized vehicle."],
                practiceResources=[
                    res("Focus Drills — extrication", "/focus-drills.html?level=firefighter_2&topic=extrication", "Stabilize and stage.", "drill"),
                    res("Search and Rescue Size-Up", "/search-and-rescue-sizeup.html", "Hazard organization.", "checklist"),
                    res("Firefighter Drill Builder", "/firefighter-drill-builder.html", "Plan a company extrication drill.", "planner"),
                ],
                drill=_std_drill(
                    "Size up a vehicle scenario, stabilize, stage tools, assign roles, and verbalize the access plan before any tool operation.",
                    "Approved vehicle prop or tabletop car, rescue tools as authorized, traffic vests, cribbing/struts as carried.",
                    "No live traffic. Instructor controls tool use.",
                    ("5-minute review", "From a wreck photo: traffic plan, energy sources, and first stabilization idea.", ["Hazards named"], ["Running to the door"], ["Where is the safest approach?"]),
                    ("15-minute stabilize + stage", "Crib/strut as trained, tool dump organized, roles assigned.", ["Stable platform", "Tool control"], ["Tools in the mud randomly"], ["Is the vehicle done moving?"]),
                    ("30-minute access plan", "Full talk-through of glass, doors, and a plan B. Include EV/hybrid inject if relevant to your response area.", ["Plan before cut", "Patient path"], ["Cutting without a path"], ["When do we call a tech team?"]),
                ),
                readinessQuestions=[
                    q("Before operating hydraulic tools you should generally:", ["Pop the hood for fun", "Control traffic, size up energy, and stabilize per the plan", "Remove your helmet to see better", "Cut the roof first always"], 1, "Setup is the skill."),
                    q("Hybrid/EV vehicles:", ["Can be treated exactly like 1998 Civics", "Need current department/manufacturer guidance for power-down and extra hazards", "Never wreck", "Only matter on interstates"], 1, "Do not invent high-voltage procedures."),
                    q("If the rescue exceeds FF II operations-level training:", ["Freestyle it", "Request the appropriate technical resource and protect the scene", "Leave the patient", "Turn off the radios"], 1, "Know the boundary."),
                ],
                officialSources=src("niosh", "nfa") + [{"label": "Department vehicle-rescue SOP and tool manufacturer instructions", "url": "/focus-drills.html?level=firefighter_2&topic=extrication", "scope": "Stabilization methods and EV procedures are local and equipment-specific."}],
                relatedSkills=["ff2_company_tactics", "ff1_forcible_entry", "fo1_size_up"],
                searchKeywords=["extrication", "stabilize", "vehicle", "jaws", "cribbing", "ev", "hybrid"],
            ),
            skill(
                id="ff2_foam",
                certificationId="firefighter_2",
                title="Foam Operations",
                aliases=["foam", "class b", "eductor", "afff", "flammable liquid"],
                category="Special Operations",
                careerStage="firefighter",
                summary="Match foam to the fuel, set up proportioning equipment correctly, and know when foam is the wrong tool.",
                whyItMatters="Wrong foam, wrong percentage, or a starved eductor wastes concentrate and fails to extinguish.",
                learningPoints=["Fuel and foam type must match. Follow current department product guidance — formulations change.", "Eductors have flow, hose-length, and nozzle constraints.", "Finished-foam application is a blanket, not a stirring rod.", "Environmental and runoff concerns are part of the decision."],
                beforeYouDo=["What concentrate is on YOUR engine and what it is for.", "Manufacturer eductor/nozzle pairing."],
                terminology=[{"term": "Proportioning", "meaning": "Mixing concentrate and water at the intended percentage."}, {"term": "Eductor", "meaning": "A common device that pulls concentrate using water flow — picky about setup."}],
                safetyNotes=["Flammable-liquid fire is a specialized problem. Do not treat it like a dumpster.", "Runoff can spread product. Think containment."],
                seeResources=[res("Foam Eductor Calculator", "/foam-operations-calculator.html", "Engine-to-eductor pressure planning.", "calculator")],
                practiceResources=[
                    res("Foam Eductor Calculator", "/foam-operations-calculator.html", "Setup pressures.", "calculator"),
                    res("Spill Volume Calculator", "/spill-volume-calculator.html", "How much product might you be looking at?", "calculator"),
                    res("Focus Drills — foam", "/focus-drills.html?level=firefighter_2&topic=foam", "Setup walk-through.", "drill"),
                ],
                drill=_std_drill(
                    "Select foam for a stated fuel, assemble the department foam appliance correctly, and explain application and limitations.",
                    "Department foam equipment, water if authorized, SDS/product sheet, radios.",
                    "Do not discharge foam into storm drains. Dry setup is acceptable.",
                    ("5-minute review", "Match two fuels to foam type/percentage per your product sheet.", ["Correct product"], ["Any foam on any fire"], ["What does the label actually say?"]),
                    ("15-minute setup", "Build eductor/nozzle layout, check flow arrow, hose lengths, and pickup tube.", ["Manufacturer limits"], ["Hose too long for the eductor"], ["What pressure at the eductor?"]),
                    ("30-minute scenario", "Small spill fire tabletop: water first? isolation? foam? runoff? When to stop.", ["Tactical order", "Environment"], ["Plunging the stream"], ["When is this a HazMat problem, not a foam trick?"]),
                ),
                readinessQuestions=[
                    q("An eductor that does not pick up concentrate is often caused by:", ["Too much training", "Wrong flow, too much hose, kink, or a closed tube", "The color of the pail", "A wet hydrant"], 1, "Eductors are fussy by design."),
                    q("Foam application on a spill should generally:", ["Blast a hole in the middle", "Build a blanket gently per training — do not churn the fuel", "Use a straight stream from 3 feet", "Always mix Class A and B in one pail"], 1, "Do not stir the flammable liquid."),
                    q("FireOpsSim foam calculators are:", ["Manufacturer law", "Training estimates — confirm with the actual eductor/nozzle pair and SOP", "Required for certification", "Only for Class A"], 1, "Equipment manuals win."),
                ],
                officialSources=src("nfa") + [{"label": "Foam concentrate and eductor manufacturer instructions", "url": "/foam-operations-calculator.html", "scope": "Percentages, environmental rules, and compatible hardware are product-specific."}],
                relatedSkills=["ff1_fire_attack", "hazmat_ops_defensive", "do_pumper_friction_loss"],
                searchKeywords=["foam", "eductor", "class b", "afff", "proportioner", "spill"],
            ),
            skill(
                id="ff2_preplan",
                certificationId="firefighter_2",
                title="Preincident Survey",
                aliases=["preplan", "pre-incident", "occupancy survey", "target hazard"],
                category="Preplanning",
                careerStage="firefighter",
                summary="Collect the information a company will wish it had at 2 a.m.: access, water, occupancy, systems, and special hazards.",
                whyItMatters="First-due knowledge is a firefighting skill. Guessing a building in smoke is how people get trapped.",
                learningPoints=["Walk the occupancy with a purpose: access, forcible entry, water, utilities, fire protection, people.", "Write what later crews can use — not a novel.", "Note what you could not determine.", "Preplans go stale. Date them."],
                beforeYouDo=["Department preplan form.", "Permission/policy for occupancy visits."],
                terminology=[{"term": "Target hazard", "meaning": "An occupancy whose risk, complexity, or consequence deserves extra study."}, {"term": "FDC", "meaning": "Fire department connection for sprinkler/standpipe — location and condition matter."}],
                safetyNotes=["You are a guest. Do not create a tactical secret that the occupant should have told the AHJ.", "Do not enter hazardous process areas beyond your training."],
                seeResources=[res("Pre-Incident Plan Builder", "/pre-incident-plan-builder.html", "Structured occupancy notes.", "planner")],
                practiceResources=[
                    res("Pre-Incident Plan Builder", "/pre-incident-plan-builder.html", "Capture the building.", "planner"),
                    res("Occupancy Load Calculator", "/occupancy-load-calculator.html", "People vs space.", "calculator"),
                    res("Hydrant Inspection Log", "/hydrant-inspection-log.html", "Water near the target.", "log"),
                    res("Focus Drills — preplan", "/focus-drills.html?level=firefighter_2&topic=preplan", "Walk-through.", "drill"),
                ],
                drill=_std_drill(
                    "Complete a rapid preplan of an assigned occupancy covering access, water, hazards, systems, and information gaps.",
                    "Local occupancy or photos, preplan form, radio optional.",
                    "Stay in public/authorized areas.",
                    ("5-minute review", "List the eight things you must know about your first-due big box.", ["Water and access named"], ["Only the owner’s name"], ["Where is the FDC?"]),
                    ("15-minute walk", "Fill the FireOpsSim preplan builder or department form for one building.", ["Form complete", "Gaps listed"], ["Copying last year’s guess"], ["What would we do at 0200 in smoke?"]),
                    ("30-minute company preplan", "Whole crew walk, assignments (water, rear access, utilities), then a 2-minute arrival report from the notes.", ["Shared picture", "Usable notes"], ["One person did it all silently"], ["What did we still not know?"]),
                ),
                readinessQuestions=[
                    q("A useful preplan always includes:", ["The occupant’s favorite restaurant", "Access, water, occupancy/hazard, systems, and what is still unknown", "Only interior photos of desks", "A guarantee the building will never change"], 1, "Unknowns belong on the page."),
                    q("Hydrants and FDCs near a target occupancy:", ["Are decorative", "Should be verified — out-of-service and blocked connections are common", "Never matter if you have a tank", "Are only an engineer’s hobby"], 1, "Water is a preplan item."),
                    q("Preplans should be:", ["Written once in 1998", "Reviewed and dated because occupancies change", "Kept only in someone’s head", "Classified so the next shift cannot see them"], 1, "Stale preplans create false confidence."),
                ],
                officialSources=src("nfa") + [{"label": "Department preplan / target-hazard program", "url": "/pre-incident-plan-builder.html", "scope": "Required forms and inspection authority are local."}],
                relatedSkills=["ff2_company_tactics", "fo1_size_up", "do_pumper_hydrant_ops"],
                searchKeywords=["preplan", "occupancy", "target hazard", "fdc", "standpipe", "access"],
            ),
            skill(
                id="ff2_company_tactics",
                certificationId="firefighter_2",
                title="Company-Level Tactics",
                aliases=["tactics", "company operations", "assignments", "benchmarks"],
                category="Operations",
                careerStage="firefighter",
                summary="Turn an incident objective into firefighter tasks, benchmarks, and a radio update without pretending to be command.",
                whyItMatters="Firefighter II is the working supervisor of a task — not the IC, not a freelancer.",
                learningPoints=["Repeat the assignment in your own words.", "Name the benchmark that means you succeeded or failed.", "Call for help early when the task is bigger than the staffing.", "Stay inside the role: you can recommend; the IC decides strategy."],
                beforeYouDo=["A simple fire or rescue problem.", "ICS language your department actually uses."],
                terminology=[{"term": "Benchmark", "meaning": "An observable condition that shows progress (water on fire, primary complete, utilities controlled)."}, {"term": "Task vs strategy", "meaning": "You own the task; command owns the overall plan."}],
                safetyNotes=["Do not freelance a second strategy on the D side.", "If you see a life hazard command missed, say it — that is not freelancing, that is communication."],
                seeResources=[res("Fireground Decision Sim", "/fireground-decision-sim.html", "Company-level decisions inside a bigger plan.", "simulator")],
                practiceResources=[
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Tactical cases.", "simulator"),
                    res("Focus Drills — tactical support", "/focus-drills.html?level=firefighter_2&topic=tactics", "Assignment tabletop.", "drill"),
                    res("Company Officer Tools", "/company-officer-tools.html", "How officers think about your assignment.", "guide"),
                ],
                drill=_std_drill(
                    "Receive an assignment, restate it, execute a tabletop or practical task, and give a progress report with a benchmark.",
                    "Scenario cards, radios, optional hose/ladder for a practical piece.",
                    "One person plays IC. Keep the FF II inside the assignment.",
                    ("5-minute review", "Practice restating: ‘You want us to… benchmark is…’", ["Closed loop"], ["‘OK’ with no content"], ["What is the benchmark for primary search?"]),
                    ("15-minute tabletop", "Three assignments: backup line, utilities, and a vent group. Give updates.", ["Role discipline", "Clear updates"], ["Inventing a new strategy"], ["When do we tell IC we cannot do it?"]),
                    ("30-minute evolution", "Combined: stretch, search support, and a condition-change card. Stay in role.", ["Benchmarks", "Reassessment"], ["Freelancing the roof"], ["Did IC actually know our progress?"]),
                ),
                readinessQuestions=[
                    q("If an assignment is bigger than your crew, you should:", ["Quietly do half of it", "Tell command what you can do and what you need", "Ignore it", "Take a second company without telling anyone"], 1, "Staffing honesty is tactics."),
                    q("A benchmark is useful because:", ["It fills the radio", "It tells command whether the objective is actually happening", "It replaces size-up", "It is only for chiefs"], 1, "‘Working on it’ is not a benchmark."),
                    q("Seeing a serious unseen hazard as the assigned crew means:", ["Stay silent to avoid bothering IC", "Report it — that is part of operations", "Leave the scene", "Post it online"], 1, "Communication is not freelancing."),
                ],
                officialSources=src("nfa", "fema") + [{"label": "Department ICS / tactical SOP", "url": "/fireground-decision-sim.html", "scope": "Assignment language and benchmarks are local."}],
                relatedSkills=["fo1_initial_radio_report", "fo1_accountability", "ff2_radio_reports", "ff1_fire_attack"],
                searchKeywords=["tactics", "assignment", "benchmark", "company", "ics", "progress report"],
            ),
            skill(
                id="ff2_radio_reports",
                certificationId="firefighter_2",
                title="Condition and Progress Reports",
                aliases=["can report", "progress report", "radio report", "conditions actions needs"],
                category="Communications",
                careerStage="firefighter",
                summary="Give short CAN-style updates: conditions, actions, needs — so command can think.",
                whyItMatters="Long stories clog the channel. Missing stories leave people in danger.",
                learningPoints=["Conditions: what is the fire/building/people doing now?", "Actions: what are YOU doing?", "Needs: what must happen next?", "If nothing changed, a short ‘unchanged’ can still be useful when asked."],
                beforeYouDo=["Department radio report format.", "Training channel."],
                terminology=[{"term": "CAN", "meaning": "Conditions, Actions, Needs — a common training structure, not a law."}],
                safetyNotes=["Do not bury a Mayday inside a casual update.", "If you are in trouble, use the emergency format."],
                practiceResources=[
                    res("Focus Drills — radio reports", "/focus-drills.html?level=firefighter_2&topic=radio", "CAN reps.", "drill"),
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Talk while the problem changes.", "simulator"),
                    res("Fire Officer I — initial radio report", "/skill-support.html?cert=fire_officer_1&task=fo1_initial_radio_report", "How command hears you.", "skill"),
                ],
                drill=_std_drill(
                    "Deliver timed CAN reports from changing fireground assignments.",
                    "Radio or timer, scenario cards, photos.",
                    "Training talkgroup only.",
                    ("5-minute review", "One photo, one 15-second CAN.", ["All three parts"], ["A 90-second story"], ["What is the need?"]),
                    ("15-minute reps", "Six cards, 20 seconds each. Partner scores missing pieces.", ["Brevity", "Needs stated"], ["Filler words"], ["Would IC know to send a second line?"]),
                    ("30-minute evolving fire", "A scenario with three condition changes. Reports at each change.", ["Timely", "Accurate"], ["Waiting for the perfect sentence"], ["When should this have been a Mayday instead?"]),
                ),
                readinessQuestions=[
                    q("‘Needs’ in a progress report should be:", ["A complaint about lunch", "The next resource or action required for the assignment", "Optional", "Only water"], 1, "Needs let command help you."),
                    q("If conditions deteriorate rapidly, your radio should:", ["Stay silent until knockdown", "Match the urgency — including emergency traffic/Mayday if that is the truth", "Switch to cell phone", "Ask dispatch for the weather"], 1, "The radio exists for this."),
                    q("CAN is:", ["Required NFPA text", "A training pattern to keep reports complete and short", "Only for chiefs", "A type of foam"], 1, "Departments may use a different acronym. The idea is completeness."),
                ],
                officialSources=src("nfa") + [{"label": "Department radio SOP", "url": "/focus-drills.html?level=firefighter_2&topic=radio", "scope": "Report format and channel use are local."}],
                relatedSkills=["ff1_communications_mayday", "fo1_initial_radio_report", "ff2_company_tactics"],
                searchKeywords=["CAN", "progress report", "radio", "conditions", "needs", "benchmark"],
            ),
            skill(
                id="ff2_evidence_overhaul",
                certificationId="firefighter_2",
                title="Evidence-Aware Overhaul",
                aliases=["evidence", "origin cause", "overhaul", "investigation"],
                category="Overhaul",
                careerStage="firefighter",
                summary="Expose hidden fire while disturbing origin indicators as little as the fire problem allows.",
                whyItMatters="The investigation is often won or lost by the first companies with pike poles.",
                learningPoints=["Knock down hidden fire. That still comes first for life safety.", "Do not shovel the origin out the window.", "Photograph or report unusual things before they vanish if policy allows.", "Chain of custody and legal rules are local — do not play detective beyond your role."],
                beforeYouDo=["Department origin/cause notification SOP.", "Overhaul PPE/SCBA rules."],
                terminology=[{"term": "Origin area", "meaning": "Where the fire is believed to have started — extra care."}, {"term": "Indicator", "meaning": "A burn pattern or object that might help investigators — not proof by itself."}],
                safetyNotes=["Overhaul injuries and respiratory exposure are still the job hazard.", "Do not keep ‘souvenirs.’"],
                practiceResources=[
                    res("Focus Drills — evidence overhaul", "/focus-drills.html?level=firefighter_2&topic=evidence", "Decision photos.", "drill"),
                    res("Firefighter I — overhaul", "/skill-support.html?cert=firefighter_1&task=ff1_overhaul_salvage", "Hazard scan first.", "skill"),
                    res("Fire Inspection / notes tools", "/fire-code-violation-notes.html", "Objective notes practice.", "practice"),
                ],
                drill=_std_drill(
                    "From scene photos, choose overhaul actions that find hidden fire and protect likely origin indicators.",
                    "Scene photos, salvage cover, pike pole (optional), note sheet.",
                    "Tabletop is enough. Mark ‘do not toss’ items.",
                    ("5-minute review", "Name three things firefighters accidentally destroy.", ["Indicators named"], ["Everything in the dumpster"], ["Who do we notify?"]),
                    ("15-minute photo set", "Five photos: room-and-contents vs suspicious vs clearly accidental. Plan overhaul depth.", ["Restrained demolition"], ["Same overhaul everywhere"], ["What would you tell an investigator?"]),
                    ("30-minute practical", "Overhaul a training room with planted ‘evidence’ and a hidden smolder sim (or card). Find the fire, leave the clue.", ["Hidden fire found", "Clue preserved"], ["Souvenir hunting"], ["Did we stay on air?"]),
                ),
                readinessQuestions=[
                    q("If life safety and hidden fire conflict with preserving a room:", ["Preserve the room and let it rekindle", "Life safety and extinguishment win — then protect what is left", "Call the news first", "Remove SCBA to smell for accelerants"], 1, "People and rekindle first, then the scene."),
                    q("Unusual containers, pour patterns you think you see, or multiple starts:", ["Should be posted online", "Should be reported through the department investigation path — not diagnosed as a hobby", "Mean you should interrogate the occupant", "Are always arson"], 1, "Stay in your lane; still speak up."),
                    q("Taking a burned object home:", ["Is a training aid", "Is not acceptable", "Is fine if it is small", "Helps the case"], 1, "It can be evidence. It is not yours."),
                ],
                officialSources=src("nfa") + [{"label": "Department fire-investigation / overhaul SOP", "url": "/firefighter-1-2-tools.html", "scope": "Who investigates and how scenes are held are local and legal issues."}],
                relatedSkills=["ff1_overhaul_salvage", "fo1_documentation", "ff2_company_tactics"],
                searchKeywords=["evidence", "origin", "cause", "overhaul", "investigation", "arson"],
            ),
            skill(
                id="ff2_hose_testing",
                certificationId="firefighter_2",
                title="Hose and Equipment Service Testing",
                aliases=["hose test", "service test", "annual hose", "out of service hose"],
                category="Readiness",
                careerStage="firefighter",
                summary="Plan a safe hose/equipment service test: zones, documentation, failure criteria, and tagging out failures.",
                whyItMatters="Burst hose on the fireground is a predictable maintenance failure. Testing is how you find it in the lot.",
                learningPoints=["Follow current department and manufacturer test pressures — FireOpsSim will not quote a standard as if it were the law.", "Safety zone: a pressurized hose is a weapon.", "Document pass/fail and remove failures from service.", "Testing is not a pump-operator ego contest."],
                beforeYouDo=["Department hose-test SOP and the form.", "Who may operate the test pump/gate."],
                terminology=[{"term": "Service test", "meaning": "A scheduled pressure/function test of hose or equipment per AHJ procedure."}, {"term": "Out of service tag", "meaning": "The hose/device may not go back on the rig."}],
                safetyNotes=["Nobody stands over hose under test.", "Slow fill. Watch couplings.", "Hearing and eye protection as required."],
                practiceResources=[
                    res("Focus Drills — hose test", "/focus-drills.html?level=firefighter_2&topic=hose%20test", "Planning walk-through.", "drill"),
                    res("Firefighter Drill Builder", "/firefighter-drill-builder.html", "Build a safe test-day plan.", "planner"),
                    res("Driver / Operator inspection skill", "/skill-support.html?cert=driver_operator_pumper&task=do_pumper_apparatus_inspection", "Readiness mindset.", "skill"),
                ],
                drill=_std_drill(
                    "Walk through a department hose-test workflow: layout, safety zone, documentation, and failure handling — without inventing test pressures.",
                    "Department test records, cones for a safety zone, sample hose if authorized.",
                    "Do not pressurize hose unless a qualified instructor is running a real test.",
                    ("5-minute review", "Draw the safety zone and the ‘no-go’ line for people.", ["Zone drawn"], ["Standing over hose"], ["Who records pass/fail?"]),
                    ("15-minute paper drill", "Fill a mock record for 10 sections. Two fail. Tag and separate them.", ["Docs", "OOS handling"], ["Putting failed hose back on the bed ‘until next week’"], ["Where does failed hose live?"]),
                    ("30-minute test-day plan", "Build a full evolution with the drill builder: staffing, water source, sequence, rehab, and emergency if a line bursts.", ["Plan complete", "Safety brief"], ["Rushing to finish before shift change"], ["What is our burst-hose action?"]),
                ),
                readinessQuestions=[
                    q("Test pressures and intervals should come from:", ["A forum post", "Department SOP plus manufacturer/AHJ-adopted procedures", "Whatever the pump can make", "The last shift’s memory"], 1, "Do not invent a standard."),
                    q("Failed hose should be:", ["Folded on the engine anyway", "Removed from service and documented", "Repaired with electrical tape for one more fire", "Given to another company"], 1, "A known failure belongs off the rig."),
                    q("People during a hose test should be:", ["Sitting on the hose", "Outside the safety zone except as the procedure requires", "Using the hose as a bench", "Filming from the coupling"], 1, "Pressurized hose kills."),
                ],
                officialSources=src("nfa") + [{"label": "Department hose-testing SOP and hose manufacturer instructions", "url": "/firefighter-drill-builder.html", "scope": "Pressures, intervals, and tagging are AHJ- and product-specific. FireOpsSim does not reproduce those numbers."}],
                relatedSkills=["do_pumper_apparatus_inspection", "fi1_training_safety", "ff1_hose_advancement"],
                searchKeywords=["hose test", "service test", "annual test", "out of service", "coupling"],
            ),
        ],
    }


def cert_hazmat():
    return {
        "id": "hazmat_operations",
        "title": "Hazardous Materials Operations",
        "shortTitle": "HazMat Ops",
        "careerStage": "specialty",
        "category": "HazMat",
        "aliases": ["hazmat", "hazmat ops", "hazardous materials operations", "hm ops", "haz ops", "operations level hazmat"],
        "summary": "Recognize, isolate, deny entry, use current references, and take defensive actions within operations-level training — not technician work.",
        "skills": [
            skill(
                id="hazmat_ops_recognition",
                certificationId="hazmat_operations",
                title="Recognition and Identification",
                aliases=["placard", "container", "erg", "recognition", "what is it"],
                category="Recognition",
                careerStage="specialty",
                summary="Use clues, markings, occupancy, and current references to identify likely hazards without becoming part of the release.",
                whyItMatters="Wrong ID produces wrong isolation and dead firefighters. Guessing a product from a smell is not a tactic.",
                learningPoints=["Occupancy, container shape, placards/labels, shipping papers, and people are clues — not certainties.", "Stay out of the product. Binoculars beat footsteps.", "The ERG is a starting reference, not a chemistry degree.", "If clues conflict, isolate wider and call resources."],
                beforeYouDo=["Current ERG or department-approved reference.", "Binoculars / spotting scope if carried."],
                terminology=[{"term": "Placard", "meaning": "Diamond marking on bulk transport giving hazard class clues."}, {"term": "Shipping papers", "meaning": "Documents that may name the product — obtained without becoming a victim."}],
                safetyNotes=["Do not walk into a cloud to read a 4-digit number.", "Terrorism/WMD clues change isolation and notifications."],
                seeResources=[res("HazMat Placard Reference", "/hazmat-placard-reference.html", "Class clues for training — verify with a current official source.", "reference")],
                practiceResources=[
                    res("HazMat Placard Reference", "/hazmat-placard-reference.html", "Class recognition.", "reference"),
                    res("HazMat Tools", "/hazmat-tools.html", "Recognition hub.", "guide"),
                    res("HazMat Awareness & Operations Center", "/hazmat-awareness-operations.html", "Study and drills.", "guide"),
                    res("PHMSA ERG", "https://www.phmsa.dot.gov/hazmat/erg/emergency-response-guidebook-erg", "Current guidebook.", "official"),
                ],
                drill=_std_drill(
                    "From photos or a training trailer, list clues, state what you will not do, and locate the correct ERG guide concept without entering the hot zone.",
                    "Current ERG, photos or props, binoculars if available.",
                    "Stay at a conservative distance. No product.",
                    ("5-minute review", "Name five clue categories before you mention a chemical name.", ["Clues first"], ["Running in"], ["What if there is no placard?"]),
                    ("15-minute ERG drill", "Three IDs: UN number, placard-only, occupancy-only. Find the guide page idea and isolation concept.", ["Reference used", "Distance mindset"], ["Memorized old numbers"], ["When do we upgrade to a tech team?"]),
                    ("30-minute scene problem", "Mixed clues (facility + vehicle). Build a notification and isolation recommendation.", ["Conflict handled", "Notifications"], ["Declaring the product from a smell"], ["What did we still not know?"]),
                ),
                readinessQuestions=[
                    q("The safest way to get a 4-digit ID is often:", ["Walk up to the tanker", "Use optics, papers from a safe person, or facility staff — not your lungs", "Taste the product", "Wait for the news"], 1, "Distance is a tactic."),
                    q("If occupancy says pesticide and the placard says flammable liquid:", ["Pick the more exciting one", "Treat the uncertainty as a reason for wider isolation and specialist help", "Ignore the occupancy", "Assume it is water"], 1, "Conflicting clues are a warning."),
                    q("FireOpsSim placard pages are:", ["A replacement for the current ERG", "Training aids — confirm with the current official ERG and SOP", "Legal ID", "Only for technicians"], 1, "References go out of date."),
                ],
                officialSources=src("phmsa", "nfa") + [{"label": "Department HazMat SOP and current ERG", "url": "/hazmat-awareness-operations.html", "scope": "Product ID methods and notifications are local plus current federal/state references."}],
                relatedSkills=["hazmat_ops_erg", "hazmat_ops_isolation", "hazmat_ops_radio_brief"],
                searchKeywords=["placard", "UN number", "container", "ERG", "recognition", "hazmat"],
            ),
            skill(
                id="hazmat_ops_isolation",
                certificationId="hazmat_operations",
                title="Isolation and Protective Actions",
                aliases=["isolation", "deny entry", "evacuate", "shelter in place", "protective action"],
                category="Isolation",
                careerStage="specialty",
                summary="Establish initial isolation, deny entry, and choose protective actions from current references and the AHJ plan.",
                whyItMatters="Most lives at a HazMat scene are saved by keeping people out of the product, not by heroic entries.",
                learningPoints=["Initial isolation is a conservative guess you can enlarge.", "Evacuate vs shelter-in-place depends on the material, building, and time.", "Control the people problem: spectators, employees, and your own crews.", "Weather (wind) is part of the geometry."],
                beforeYouDo=["Current ERG isolation/protective action tables as applicable.", "Map or intersection."],
                terminology=[{"term": "Deny entry", "meaning": "Stop additional people from walking into the problem."}, {"term": "Protective action", "meaning": "Evacuate or shelter-in-place decisions for the public."}],
                safetyNotes=["Do not place engines in the plume to ‘block the road.’", "Your isolation is not a technician’s hot-zone tape — but it must still be real."],
                seeResources=[res("HazMat Isolation Planner", "/hazmat-isolation-planner.html", "Distance and geometry practice.", "planner")],
                practiceResources=[
                    res("HazMat Isolation Planner", "/hazmat-isolation-planner.html", "Lay out distances.", "planner"),
                    res("HazMat Size-Up Checklist", "/hazmat-sizeup-checklist.html", "Initial observations.", "checklist"),
                    res("Focus Drills — isolation", "/focus-drills.html?level=hazmat_ops&topic=isolation", "Tabletop map.", "drill"),
                ],
                drill=_std_drill(
                    "On a map, set an initial isolation polygon using wind and a current reference concept, then identify who is still inside it.",
                    "Map, cones if outdoor, current ERG, radios.",
                    "Tabletop is fine. Use today’s wind if outdoors.",
                    ("5-minute review", "Upwind, uphill, upstream — say it and place the first engine.", ["Positioning"], ["Downwind ‘to see better’"], ["Who do we move first?"]),
                    ("15-minute map problem", "School, highway, and a small leak. Pick evacuate vs shelter for one building.", ["Protective action reasoned"], ["One-size isolation"], ["What changed when the wind shifted?"]),
                    ("30-minute expanding incident", "Start small, then a larger release inject. Re-draw isolation and notifications.", ["Expand early", "Public protection"], ["Holding a tiny circle for pride"], ["When is this bigger than Ops-level?"]),
                ),
                readinessQuestions=[
                    q("Initial isolation should be:", ["Exact to the inch", "Conservative and adjustable as information improves", "Always 1 mile", "Only for explosives"], 1, "You can shrink later more easily than you can un-expose people."),
                    q("Shelter-in-place can be better than evacuation when:", ["You want to ignore the public", "The atmosphere outside is worse and buildings can protect people for a time", "It is always better", "The product is guaranteed harmless"], 1, "It is a timed, informed choice — not a default."),
                    q("The first engine should generally stage:", ["In the visible cloud", "Upwind/uphill/upstream of the problem as conditions allow", "Against the tank for a good photo", "On the downhill side to ‘catch runoff’ with the crew"], 1, "Apparatus are not plugs for a plume."),
                ],
                officialSources=src("phmsa", "nfa") + [{"label": "Department / LEPC emergency response plan", "url": "/hazmat-isolation-planner.html", "scope": "Public protective actions are AHJ decisions using current references."}],
                relatedSkills=["hazmat_ops_zones", "hazmat_ops_recognition", "hazmat_ops_radio_brief"],
                searchKeywords=["isolation", "evacuate", "shelter in place", "deny entry", "upwind", "ERG"],
            ),
            skill(
                id="hazmat_ops_erg",
                certificationId="hazmat_operations",
                title="ERG Navigation",
                aliases=["erg", "guidebook", "orange guide", "green section"],
                category="Reference Use",
                careerStage="specialty",
                summary="Find the material, the guide, isolation information, and emergency contacts quickly in the current ERG.",
                whyItMatters="A reference you cannot navigate under stress is a paperweight.",
                learningPoints=["Know yellow/blue lookup vs orange guides vs green isolation table — in the current edition.", "Tablets and apps are fine if they are the current official content.", "The ERG is first-responder general guidance, not a site-specific plan.", "Practice timed lookups."],
                beforeYouDo=["A current ERG (print or official digital)."],
                terminology=[{"term": "Guide page", "meaning": "The orange-bordered general hazard and action information in the ERG."}],
                safetyNotes=["Do not use a 10-year-old book in the cab as if it were current.", "Apps must be the real current data, not a random screenshot."],
                practiceResources=[
                    res("PHMSA ERG", "https://www.phmsa.dot.gov/hazmat/erg/emergency-response-guidebook-erg", "Get the current book/app.", "official"),
                    res("HazMat Awareness & Operations Center", "/hazmat-awareness-operations.html", "ERG drills.", "guide"),
                    res("Focus Drills — ERG", "/focus-drills.html?level=hazmat_ops&topic=erg", "5-minute navigation.", "drill"),
                ],
                drill=_std_drill(
                    "Complete timed ERG lookups: name, UN number, placard, and a rail/highway ID — then state the isolation concept.",
                    "Current ERG for every participant, timer, ID list.",
                    "Classroom. No product.",
                    ("5-minute review", "Open to the how-to-use section and point to lookup paths.", ["Book orientation"], ["Memorizing old guides"], ["Print or digital — is it current?"]),
                    ("15-minute timed lookups", "Ten IDs. Score accuracy, not swagger.", ["Correct guide", "Isolation noted"], ["Guessing without the book"], ["Which lookup was slowest?"]),
                    ("30-minute mixed traffic", "Combine ERG with a map isolation for two incidents, including a ‘not in the book’ facility chemical.", ["When ERG is not enough"], ["Forcing a UN number"], ["Who do we call next?"]),
                ),
                readinessQuestions=[
                    q("If the chemical is a facility product not in the ERG:", ["Invent a UN number", "Use occupancy procedures, SDS/facility staff, and specialists — do not fake an ERG ID", "Treat it as gasoline", "Leave"], 1, "The ERG is not every chemical on earth."),
                    q("Green-section isolation ideas are:", ["Always exact", "A starting protective-action tool for certain listed materials/scenarios in the current book", "Only for officers", "A replacement for wind"], 1, "Read the current table’s conditions."),
                    q("Using last decade’s ERG is:", ["Fine", "A risk — isolation and guides change; use the current official edition", "Required for Pro Board", "Better because you marked it up"], 1, "Currency is part of competence."),
                ],
                officialSources=src("phmsa", "nfa"),
                relatedSkills=["hazmat_ops_recognition", "hazmat_ops_isolation", "hazmat_ops_radio_brief"],
                searchKeywords=["ERG", "guidebook", "UN", "orange guide", "green table", "PHMSA"],
            ),
            skill(
                id="hazmat_ops_zones",
                certificationId="hazmat_operations",
                title="Control Zones",
                aliases=["hot zone", "warm zone", "cold zone", "control zones"],
                category="Control Zones",
                careerStage="specialty",
                summary="Lay out hot/warm/cold concepts so work, decon, and command do not share the same puddle.",
                whyItMatters="If the cold zone is in the product, everyone is in the hot zone and nobody admitted it.",
                learningPoints=["Zones are about contamination control and access, not pretty tape.", "Decon usually lives in the warm zone conceptually.", "Command and staging belong out of the product and preferably upwind.", "Zones move if the plume or spill moves."],
                beforeYouDo=["Tape/cones, a map, wind indication."],
                terminology=[{"term": "Hot zone", "meaning": "Where the hazard is — entry limited to appropriate PPE and mission."}, {"term": "Warm zone", "meaning": "Contamination reduction / limited access."}, {"term": "Cold zone", "meaning": "Support — should remain uncontaminated."}],
                safetyNotes=["Do not put rehab in the vapor.", "Spectators will walk through tape. Staff the control points."],
                seeResources=[res("Decon Corridor Planner", "/decon-corridor-planner.html", "Warm-zone work layout.", "planner")],
                practiceResources=[
                    res("Decon Corridor Planner", "/decon-corridor-planner.html", "Decon in the warm zone.", "planner"),
                    res("HazMat Isolation Planner", "/hazmat-isolation-planner.html", "Geometry.", "planner"),
                    res("Focus Drills — zones", "/focus-drills.html?level=hazmat_ops&topic=zones", "Cone layout.", "drill"),
                ],
                drill=_std_drill(
                    "Using cones or a map, lay out operational zones, access control, decon placement, and command for a defensive incident.",
                    "Cones/tape, map, wind flag, radios.",
                    "Parking lot or tabletop.",
                    ("5-minute review", "Place command, staging, and a public control point on a sketch.", ["Upwind support"], ["Command next to the leak"], ["Where do ambulances park?"]),
                    ("15-minute cone drill", "Hot/warm/cold with one access corridor.", ["Corridor obvious"], ["Tape with no staffing"], ["How does a victim get to EMS without contaminating the cold zone?"]),
                    ("30-minute moving plume", "Shift wind 90 degrees. Move zones and explain who is now contaminated.", ["Zones move", "Accountability"], ["Pride in the original tape line"], ["Who got exposed during the move?"]),
                ),
                readinessQuestions=[
                    q("Command post in the visible vapor is:", ["Leadership", "A zone failure", "Required", "Fine if windows are up"], 1, "Support belongs in the cold zone."),
                    q("Decon is conceptually part of:", ["The hot zone picnic", "Contamination reduction — typically the warm-zone function", "The next day’s problem", "Only technician work never ops"], 1, "Ops-level decon support still needs a place to exist."),
                    q("If the spill grows, zones should:", ["Stay for consistency", "Expand and be re-briefed", "Be ignored", "Only be drawn on a whiteboard downtown"], 1, "Geometry follows the product."),
                ],
                officialSources=src("nfa", "phmsa") + [{"label": "Department HazMat zone / ICS SOP", "url": "/decon-corridor-planner.html", "scope": "Zone distances and PPE for each zone are AHJ- and product-specific."}],
                relatedSkills=["hazmat_ops_decon", "hazmat_ops_isolation", "hazmat_ops_defensive"],
                searchKeywords=["hot zone", "warm zone", "cold zone", "control zones", "decon placement"],
            ),
            skill(
                id="hazmat_ops_decon",
                certificationId="hazmat_operations",
                title="Emergency Decontamination",
                aliases=["decon", "decontamination", "corridor", "gross decon"],
                category="Decon",
                careerStage="specialty",
                summary="Set up operations-level emergency/gross decon so people and equipment do not spread the problem.",
                whyItMatters="The second incident is the contaminated ambulance and the exposed firefighter who ‘only stepped in it.’",
                learningPoints=["Emergency decon for life safety vs technical decon for a planned entry — know which you are doing.", "Flow: dirty to cleaner, not a maze.", "Protect decon members with appropriate PPE and a plan for their own decon.", "Runoff is a secondary release."],
                beforeYouDo=["Department decon cache and SOP.", "Water source and runoff plan."],
                terminology=[{"term": "Gross / emergency decon", "meaning": "Rapid contamination reduction, often for victims or unexpectedly contaminated responders."}],
                safetyNotes=["Do not send contaminated patients through a normal ED entrance without notice.", "Hypothermia and privacy still matter."],
                seeResources=[res("Decon Corridor Planner", "/decon-corridor-planner.html", "Layout practice.", "planner")],
                practiceResources=[
                    res("Decon Corridor Planner", "/decon-corridor-planner.html", "Build the corridor on paper.", "planner"),
                    res("HazMat Tools", "/hazmat-tools.html", "Decon and isolation tools.", "guide"),
                    res("Focus Drills — decon", "/focus-drills.html?level=hazmat_ops&topic=decon", "Hands-on layout.", "drill"),
                ],
                drill=_std_drill(
                    "Lay out an operations-level decon corridor with zones, flow, assignments, and a runoff/containment idea.",
                    "Department decon cache or cones/tarp stand-ins, water if authorized, radios.",
                    "Do not create a real environmental release. Contain training water.",
                    ("5-minute review", "Sketch dirty-to-clean flow and where EMS waits.", ["Flow direction"], ["EMS in the hot zone"], ["Where do clothes go?"]),
                    ("15-minute corridor", "Build it with cones. Assign wash, bagging, and a medic in the cold zone.", ["Assignments", "Access control"], ["No bag for PPE"], ["How do we decon the decon team?"]),
                    ("30-minute victim flow", "Two ambulatory and one non-ambulatory cards. Keep contamination out of the ambulance.", ["Triage vs decon", "Notifications"], ["Loading a dirty patient because it is faster"], ["What does the hospital need to hear?"]),
                ),
                readinessQuestions=[
                    q("The point of emergency decon is:", ["A perfect lab-clean responder", "Rapidly reduce contamination to protect life and keep the rest of the system clean", "Only for technicians", "To wash the street"], 1, "Speed and isolation, not spa day."),
                    q("A contaminated patient in an unprotected ambulance:", ["Saves time", "Spreads the incident into the hospital system", "Is required by EMTALA always", "Is fine if windows are down"], 1, "Notify and protect the chain of care."),
                    q("Runoff from decon:", ["Is always potable water", "Can be a secondary contamination problem — plan containment per SOP", "Should go to storm drains by default", "Does not matter with soap"], 1, "You can make a second spill."),
                ],
                officialSources=src("nfa", "niosh") + [{"label": "Department decon SOP and hospital notification plan", "url": "/decon-corridor-planner.html", "scope": "Decon methods, solutions, and EMS transport rules are local."}],
                relatedSkills=["hazmat_ops_zones", "hazmat_ops_ppe", "hazmat_ops_defensive"],
                searchKeywords=["decon", "gross decon", "corridor", "contamination", "runoff"],
            ),
            skill(
                id="hazmat_ops_defensive",
                certificationId="hazmat_operations",
                title="Defensive Control Options",
                aliases=["dike", "dam", "divert", "defensive", "remote shutoff", "vapor suppression"],
                category="Operations",
                careerStage="specialty",
                summary="Choose defensive actions you are trained and authorized to do: dike, dam, divert, remote valve, vapor suppression — and stop at the ops boundary.",
                whyItMatters="Operations level is not ‘almost a technician.’ Leaving your level is how people die in product.",
                learningPoints=["Defensive means you are not plugging the hole with your body in a Level A suit unless that is actually your qualification.", "Remote shutoff and product control that does not require entering the release are the usual wins.", "Diking buys time for people who own the product.", "If you cannot explain the action inside your SOP, do not do it."],
                beforeYouDo=["AHJ ops-level action list.", "Absorbents/booms as carried."],
                terminology=[{"term": "Defensive", "meaning": "Preventing spread and protecting people/environment without offensive leak control beyond your training."}, {"term": "Offensive/technician", "meaning": "Entry and leak control requiring higher qualification and PPE."}],
                safetyNotes=["A boom in a fast sewer can become a drowning/confined hazard.", "Vapor suppression foam is a foam problem plus a HazMat problem."],
                practiceResources=[
                    res("Spill Volume Calculator", "/spill-volume-calculator.html", "How big is the puddle?", "calculator"),
                    res("HazMat Incident Notes", "/hazmat-incident-notes.html", "Document actions.", "notes"),
                    res("Focus Drills — defensive", "/focus-drills.html?level=hazmat_ops&topic=defensive", "Option tabletop.", "drill"),
                    res("Foam Operations skill", "/skill-support.html?cert=firefighter_2&task=ff2_foam", "If vapor suppression is the tool.", "skill"),
                ],
                drill=_std_drill(
                    "For a spill scenario, pick defensive options within ops-level authorization, list required equipment, and name the stop point.",
                    "Scenario cards, cones for a dike line, department absorbent/boom if available.",
                    "No real product. Discuss environmental notifications.",
                    ("5-minute review", "List five defensive options and one action that would be technician-only on your team.", ["Boundary named"], ["‘Just go cap it’"], ["Who owns the facility valve?"]),
                    ("15-minute spill", "50-gallon drum leak toward a drain. Plan dike/divert and notifications.", ["Drain protected", "PPE honest"], ["Standing in the product to place a pad"], ["Do we have enough boom?"]),
                    ("30-minute mixed incident", "Leak plus fire plus a crowd. Prioritize life, isolation, then product. Call the boundary when the problem needs a team.", ["Priorities", "Upgrade"], ["Freelancing a plug"], ["What did we tell the technician team?"]),
                ),
                readinessQuestions=[
                    q("An operations-level firefighter should:", ["Enter any cloud if the officer is excited", "Take defensive actions they are trained and authorized for, and request technicians when the job exceeds that", "Always plug the leak", "Never touch a valve even if it is a labeled remote shutoff they are trained to use"], 1, "Train and SOP define the box."),
                    q("Stopping product from entering a storm drain is usually:", ["Technician-only always", "A common defensive goal using dikes/covers you are trained to use", "Impossible", "A police problem only"], 1, "Keep it out of the water system."),
                    q("If the only ‘fix’ requires entering the release in chemical PPE you do not have:", ["Improvise with structural gear", "Hold isolation, protect people, and get the right team", "Send the probationary firefighter", "Spray water on every chemical"], 1, "Structural firefighting gear is not a chemically resistant suit."),
                ],
                officialSources=src("nfa", "phmsa") + [{"label": "Department HazMat operations SOP", "url": "/hazmat-awareness-operations.html", "scope": "Authorized defensive tasks and PPE are local."}],
                relatedSkills=["hazmat_ops_ppe", "hazmat_ops_decon", "ff2_foam", "hazmat_ops_zones"],
                searchKeywords=["dike", "dam", "divert", "defensive", "shutoff", "spill", "ops level"],
            ),
            skill(
                id="hazmat_ops_ppe",
                certificationId="hazmat_operations",
                title="PPE Limitations",
                aliases=["chemical ppe", "level a", "level b", "structural gear hazmat", "encapsulation"],
                category="PPE",
                careerStage="specialty",
                summary="Know what department HazMat PPE actually protects against — and when structural firefighting gear is the wrong answer.",
                whyItMatters="The wrong suit is a costume. Breakthrough, heat stress, and training limits kill.",
                learningPoints=["Structural PPE is for fire, not a chemical catalog.", "Chemical protective clothing is chemical- and manufacturer-specific.", "Heat stress in encapsulating suits is a medical problem.", "If you are not trained and medically cleared for the ensemble, you do not wear it to ‘help.’"],
                beforeYouDo=["What CPC/SCBA combinations YOUR department actually fields at ops level.", "Manufacturer lookup culture — do not memorize a 1990s chart as gospel."],
                terminology=[{"term": "Breakthrough", "meaning": "When a chemical moves through a material — time is not infinite."}, {"term": "CPC", "meaning": "Chemical protective clothing."}],
                safetyNotes=["Never assume dish soap and a rain coat are chemical PPE.", "Decon the people who wore the suits."],
                practiceResources=[
                    res("HazMat Awareness & Operations Center", "/hazmat-awareness-operations.html", "PPE modules.", "guide"),
                    res("Focus Drills — PPE limits", "/focus-drills.html?level=hazmat_ops&topic=ppe", "Capability review.", "drill"),
                    res("NIOSH Firefighter Center", "https://www.cdc.gov/niosh/firefighters/", "Health context.", "official"),
                ],
                drill=_std_drill(
                    "Review department PPE: what it is for, what it is not for, and when specialist guidance is required.",
                    "Department HazMat PPE (display), manufacturer info, scenario cards.",
                    "Do not make untrained members don technician ensembles.",
                    ("5-minute review", "Name three chemicals or conditions where structural gear is the wrong answer.", ["Limits named"], ["‘Bunker gear is fine for everything’"], ["Who is medically cleared to wear CPC?"]),
                    ("15-minute ensemble talk", "Match three scenarios to no-entry vs ops PPE vs tech team.", ["Honest matching"], ["Dressing the volunteer in Level A for photos"], ["What is our heat-stress plan?"]),
                    ("30-minute don/doff if authorized", "Only for members already in the program: inspect, don, walk, emergency doff concept, decon path.", ["Inspection", "Decon path"], ["Untrained donning"], ["Where does contaminated CPC go?"]),
                ),
                readinessQuestions=[
                    q("Structural firefighting clothing in a chemical vapor:", ["Is usually excellent chemical PPE", "Is generally the wrong ensemble unless the AHJ and the hazard say otherwise", "Is Level A", "Stops all gases"], 1, "It is fire gear."),
                    q("Chemical suit selection must consider:", ["Color only", "The chemical, concentration, manufacturer data, and mission time", "Whatever is closest", "Only the cost"], 1, "There is no universal suit."),
                    q("If you are not trained in the ensemble:", ["Wear it anyway to be brave", "Do not wear it — request qualified members", "Put it on the patient", "Cut holes for comfort"], 1, "Untrained CPC is a hazard."),
                ],
                officialSources=src("niosh", "nfa") + [{"label": "CPC manufacturer data and department PPE program", "url": "/hazmat-awareness-operations.html", "scope": "Suit selection, medical clearance, and duration limits are manufacturer- and AHJ-specific."}],
                relatedSkills=["hazmat_ops_defensive", "hazmat_ops_decon", "ff1_ppe"],
                searchKeywords=["ppe", "level a", "level b", "chemical suit", "breakthrough", "structural gear"],
            ),
            skill(
                id="hazmat_ops_radio_brief",
                certificationId="hazmat_operations",
                title="HazMat Initial Radio Brief",
                aliases=["hazmat size up", "initial report", "hazmat radio"],
                category="Communications",
                careerStage="specialty",
                summary="Give a concise first report: location, clues, wind, exposures, actions, resources, and a safe approach.",
                whyItMatters="The second-due company will drive into the product if your first report was ‘we have a smell.’",
                learningPoints=["Name the problem class if known, and the uncertainty if not.", "Give an approach/staging instruction.", "Say what you are doing (isolate, deny entry) and what you need (HazMat team, PD, public works).", "Keep it short enough to hear."],
                beforeYouDo=["Department size-up format.", "Training channel."],
                terminology=[{"term": "Safe approach", "meaning": "Where later units should come from — usually upwind/uphill."}],
                safetyNotes=["Do not transmit guesses as facts.", "If people are down, say so — that changes everything."],
                practiceResources=[
                    res("HazMat Size-Up Checklist", "/hazmat-sizeup-checklist.html", "Build the report from a list.", "checklist"),
                    res("HazMat Incident Notes", "/hazmat-incident-notes.html", "Capture clues.", "notes"),
                    res("Focus Drills — HazMat radio", "/focus-drills.html?level=hazmat_ops&topic=radio", "Timed briefs.", "drill"),
                    res("Fire Officer I — initial radio report", "/skill-support.html?cert=fire_officer_1&task=fo1_initial_radio_report", "Same muscle, different hazard.", "skill"),
                ],
                drill=_std_drill(
                    "Deliver a 20–30 second HazMat initial report from a photo, including approach instructions.",
                    "Photos, radios or timer, size-up checklist.",
                    "Training talkgroup.",
                    ("5-minute review", "List the must-have pieces of the first transmission.", ["Staging named"], ["‘Odor in the area’ only"], ["Where should Engine 2 stop?"]),
                    ("15-minute photo reports", "Five photos, 25 seconds each. Partner scores missing pieces.", ["Clues", "Actions", "Needs"], ["Chemical name invented"], ["Would you have driven into it?"]),
                    ("30-minute evolving leak", "Report, then a wind shift and a victim. Second report and resource request.", ["Update", "Life hazard"], ["Forgetting staging"], ["When does this become a mass-casualty problem?"]),
                ),
                readinessQuestions=[
                    q("The most important extra in a HazMat first report vs a house fire is often:", ["The color of the engine", "Safe approach/staging and isolation picture", "Your years on the job", "A joke"], 1, "Later units need a place to not die."),
                    q("If you do not know the product, you should:", ["Make up a UN number to sound sure", "Say what clues you have and what you do not know", "Say nothing", "Call it gasoline"], 1, "Uncertainty is useful information."),
                    q("‘People down’ in the first report:", ["Can wait", "Is a priority piece of information", "Is only for EMS", "Means you should enter immediately in bunker gear"], 1, "Life hazard changes the whole response — still do not create more victims."),
                ],
                officialSources=src("nfa", "phmsa") + [{"label": "Department radio / HazMat SOP", "url": "/hazmat-sizeup-checklist.html", "scope": "Report format and resource lists are local."}],
                relatedSkills=["hazmat_ops_recognition", "hazmat_ops_isolation", "fo1_initial_radio_report"],
                searchKeywords=["hazmat size up", "radio report", "staging", "approach", "notifications"],
            ),
        ],
    }
