"""Firefighter I skill pack."""
from skill_support_lib import drill, mode, q, res, skill, src


def cert_ff1():
    return {
        "id": "firefighter_1",
        "title": "Firefighter I",
        "shortTitle": "FF I",
        "careerStage": "firefighter",
        "category": "Firefighting",
        "aliases": ["firefighter 1", "firefighter i", "ff1", "ff i", "academy"],
        "summary": "Entry-level structural firefighter skills: PPE, SCBA, hose, ladders, search, ventilation, water supply, fire attack, and emergency communications.",
        "skills": [
            skill(
                id="ff1_ppe",
                certificationId="firefighter_1",
                title="PPE Readiness and Donning",
                aliases=["ppe", "turnout", "bunker gear", "donning"],
                category="PPE",
                careerStage="firefighter",
                summary="Don complete structural PPE correctly, check interfaces, and be ready to go on air without skipping protection for speed.",
                whyItMatters="Gear that is open, twisted, or incomplete is how firefighters get burned and inhale products of combustion on ‘ordinary’ jobs.",
                learningPoints=["Complete ensemble: helmet, hood, coat, pants, boots, gloves, SCBA as assigned.", "Interfaces (hood/collar, gloves/wrist, waist) matter as much as the clock.", "Inspect for damage, moisture, and missing parts before the tones.", "Speed comes from repetition of the correct sequence, not from skipping straps."],
                beforeYouDo=["Use YOUR issued gear. Training gear should still be complete.", "Know department donning standard and when SCBA is required."],
                terminology=[{"term": "Interface", "meaning": "Where two pieces of PPE meet — a common failure point."}, {"term": "Ready-for-entry", "meaning": "PPE and SCBA complete enough to make the assigned interior or IDLH task."}],
                safetyNotes=["Damaged or contaminated gear is not a fashion problem — it is a barrier failure.", "Do not store gear in living areas; follow department cancer-reduction practices."],
                practiceResources=[
                    res("Firefighter Skills Checklist", "/firefighter-skills-checklist.html", "Track PPE/SCBA reps.", "checklist"),
                    res("Fire Skill Wheel", "/fire-skill-wheel.html", "Random PPE/SCBA drills.", "wheel"),
                    res("Firefighter I/II Tools", "/firefighter-1-2-tools.html", "Core skill hub.", "guide"),
                    res("Focus Drills — PPE", "/focus-drills.html?level=firefighter_1&topic=ppe", "Timed ready-check.", "drill"),
                ],
                drill=drill(
                    "Complete a correct PPE don and partner check without sacrificing interfaces for the clock.",
                    "Issued structural PPE, SCBA as assigned, timer.",
                    "Start from a standard ready rack. Partner calls defects.",
                    mode("5-minute review", "Name every interface and one common miss (open coat, hood gaps, glove wrists).", ["Interfaces named"], ["Speed-only mindset"], ["What would you reject on a partner?"]),
                    mode("15-minute donning reps", "Three full dons with partner check. Time the third only after two correct ones.", ["Correct sequence", "Partner check"], ["Skipping hood", "Unfastened collars"], ["Did time improve after technique, or instead of it?"]),
                    mode("30-minute ready circuit", "Don, short work (stairs or hose pull), doff/reset, repeat. Include a damaged-gear inject.", ["Reset complete", "Defect handled"], ["Leaving gloves in the cab"], ["How do we catch gear problems before the next call?"]),
                ),
                readinessQuestions=[
                    q("The most important part of fast donning is:", ["Skipping the hood", "A correct, complete sequence repeated until it is smooth", "Leaving the coat open for ventilation", "Wearing street shoes in boots"], 1, "Incorrect gear is not a pass, no matter the time."),
                    q("A hood gap at the collar is:", ["Cosmetic", "An interface failure that can burn or expose you", "Required for radio mics", "Only a problem on wildland gear"], 1, "Interfaces are the weak points."),
                    q("If you find a torn moisture barrier during a check, you should:", ["Wear it anyway", "Follow department defective-PPE rules — do not make entry in failed gear", "Tape it with electrical tape and go", "Only tell the person who issued it next month"], 1, "Failed PPE is an OOS problem."),
                ],
                officialSources=src("niosh", "nfa") + [{"label": "Department PPE SOP and manufacturer care instructions", "url": "/firefighter-1-2-tools.html", "scope": "Donning standards, inspection, and retirement of gear are local and manufacturer-specific."}],
                relatedSkills=["ff1_scba", "probation_ppe_scba", "ff1_communications_mayday"],
                searchKeywords=["ppe", "turnout", "donning", "hood", "gloves", "cancer", "gear check"],
            ),
            skill(
                id="ff1_scba",
                certificationId="firefighter_1",
                title="SCBA Operations",
                aliases=["scba", "breathing apparatus", "pack", "on air", "mask"],
                category="SCBA",
                careerStage="firefighter",
                summary="Don and work on air, manage consumption, handle emergencies, and leave with a reserve — air is a tactical resource.",
                whyItMatters="Most Maydays have an air problem attached. SCBA skill is survival, not just a test station.",
                learningPoints=["Don, seal, and check before you need the pack in smoke.", "Know remaining air, workload, location, and exit time together.", "Emergency procedures are department- and manufacturer-specific — practice yours.", "A low-air alarm is a decision point, not a surprise."],
                beforeYouDo=["Use the assigned SCBA model.", "Know cylinder rating vs actual work time — they are not the same."],
                terminology=[{"term": "IDLH", "meaning": "Immediately dangerous to life or health atmosphere — SCBA territory."}, {"term": "Point of no return / turnaround", "meaning": "The time/air decision to leave so you exit with reserve."}],
                safetyNotes=["Never disable alarms.", "Buddy check the cylinder, valves, and connections.", "Entanglement and regulator emergencies need practiced responses, not creativity in the smoke."],
                seeResources=[res("SCBA Air Management Calculator", "/scba-air-management-calculator.html", "Training estimates for work time and reserve.", "calculator")],
                practiceResources=[
                    res("SCBA Air Management Calculator", "/scba-air-management-calculator.html", "Plan consumption.", "calculator"),
                    res("Fire Skill Wheel", "/fire-skill-wheel.html", "SCBA repetitions.", "wheel"),
                    res("Focus Drills — SCBA emergencies", "/focus-drills.html?level=firefighter_1&topic=scba", "Emergency circuit.", "drill"),
                    res("Study Center — academy track", "/study-center.html?track=academy", "Fundamentals review.", "guide"),
                ],
                drill=drill(
                    "Don SCBA, complete a partner check, work a short evolution, and practice the department low-air / emergency actions in a clear area.",
                    "SCBA, full PPE, training area, radios, accountability tags as used.",
                    "No live fire required. Use reduced visibility only if the instructor controls the environment.",
                    mode("5-minute review", "Buddy check: cylinder, valves, PASS, seal. State the low-air action.", ["Complete check"], ["Skipping PASS"], ["When do we leave vs fight?"]),
                    mode("15-minute work cycle", "Don, short work, check gauges twice, exit on a simulated low-air. Time the exit walk.", ["Gauge discipline", "Team exit"], ["Ignoring the partner’s air"], ["Did work time match what you expected?"]),
                    mode("30-minute emergency circuit", "Low-air, reduced profile / entanglement talk-through, Mayday trigger criteria, and a controlled emergency breathing option per SOP.", ["Emergency actions per SOP", "Mayday criteria named"], ["Inventing a technique"], ["What information goes in the Mayday?"]),
                ),
                readinessQuestions=[
                    q("Air management means:", ["Using the cylinder until it is empty", "Tracking consumption, location, work, team status, and exit reserve together", "Opening the bypass for comfort", "Removing the regulator to talk"], 1, "Air is part of the tactical clock."),
                    q("A low-air alarm should:", ["Be ignored if you can still see the fire", "Trigger the department’s exit/emergency decision process", "Always mean you have 15 minutes left", "Be silenced as a first action"], 1, "It is a decision point."),
                    q("SCBA emergency procedures should come from:", ["A viral video", "Your manufacturer instructions and department training", "Whatever worked last year on another brand", "Improvisation"], 1, "Packs differ. Train yours."),
                ],
                officialSources=src("niosh", "nfa") + [{"label": "SCBA manufacturer instructions and department RIT/Mayday SOP", "url": "/scba-air-management-calculator.html", "scope": "Emergency breathing, skip-breathing myths, and RIT operations are AHJ- and equipment-specific."}],
                relatedSkills=["ff1_search", "ff1_communications_mayday", "probation_ppe_scba", "ff1_hose_advancement"],
                searchKeywords=["scba", "air management", "low air", "pass device", "idlh", "cylinder"],
            ),
            skill(
                id="ff1_hose_advancement",
                certificationId="firefighter_1",
                title="Hose Advancement",
                aliases=["hose", "attack line", "advance the line", "charged line", "nozzle"],
                category="Engine",
                careerStage="firefighter",
                summary="Deploy, charge, and advance an attack line as a team with nozzle control, communication, and a working backup firefighter.",
                whyItMatters="Water at the right place, in a form you can still move, is the core engine-company product.",
                learningPoints=["Flake to feed. A pretty horseshoe that cannot move is a failure.", "Charged vs uncharged advances have different problems — train both if you use both.", "Nozzle, backup, and officer (or acting) need the same picture.", "Door control and stream selection are part of advancement, not extras."],
                beforeYouDo=["Know the department’s standard line: diameter, length, nozzle type, target pressure.", "Agree on who calls for water and who checks kinks."],
                terminology=[{"term": "Backup firefighter", "meaning": "Moves hose, manages slack/kinks, and supports the nozzle firefighter."}, {"term": "Bleed / charge", "meaning": "Getting air out and water to the nozzle before making the fire room."}],
                safetyNotes=["Do not stand in the bight.", "A charged line can knock people down — body position and door control matter.", "Know the stream’s reach and reaction before you open in a hallway."],
                seeResources=[res("Hose Advancement Checklist", "/hose-advancement-checklist.html", "Step review for deploy, charge, advance.", "checklist")],
                practiceResources=[
                    res("Hose Advancement Checklist", "/hose-advancement-checklist.html", "Sequence check.", "checklist"),
                    res("Hose Layout Planner", "/hose-layout-planner.html", "Think before you pull.", "planner"),
                    res("Attack Line Calculator", "/attack-line-calculator.html", "Know the pressure behind the line.", "calculator"),
                    res("Fire Skill Wheel", "/fire-skill-wheel.html", "Hose reps.", "wheel"),
                    res("Focus Drills — attack line", "/focus-drills.html?level=firefighter_1&topic=hose", "Deploy-charge-advance.", "drill"),
                ],
                drill=drill(
                    "Deploy the standard attack line to a simulated entry point, charge, bleed, advance a short distance, and reset.",
                    "Attack line, nozzle, engine or hydrant/training water, PPE, radios.",
                    "Mark a doorway. Assign nozzle, backup, and operator. Safety for charged-line movement.",
                    mode("5-minute review", "Walk the pull, flake, and ‘ready for water’ report without charging if needed.", ["Ready-for-water meaning agreed"], ["Line piled at the door"], ["Who checks the first kink?"]),
                    mode("15-minute charged advance", "Pull, charge, bleed, hit a target, advance 25–50 ft, recover.", ["Nozzle control", "Backup feeding", "Kinks cleared"], ["Opening before the backup is set", "Uncontrolled stream"], ["What would we do at a real door?"]),
                    mode("30-minute company evolution", "Two-line or long-advance scenario: stairs or around an apparatus, communication with the pump operator, then reload for a true reset.", ["Communication", "Hose management", "Serviceable reload"], ["Leaving a rats nest for the next crew"], ["Did the operator know when we opened?"]),
                ),
                readinessQuestions=[
                    q("The backup firefighter’s primary job during advancement is:", ["Take pictures", "Feed hose, manage slack/kinks, and support the nozzle", "Run the pump", "Vent the roof immediately"], 1, "The nozzle cannot fight the fire and the hose at the same time."),
                    q("You should call for water:", ["After you are already in the fire room with a dry line", "When the line is flaked to feed and the team is ready per department practice", "Only from the cab", "Never — the operator guesses"], 1, "Ready-for-water is a crew condition, not a panic."),
                    q("A charged line that cannot advance is often caused by:", ["Too much training", "Kinks, poor flake, or no backup managing the drag", "A hydrant that is too close", "Using a smooth-bore"], 1, "Hose management is the skill."),
                ],
                officialSources=src("nfa", "fsri") + [{"label": "Department hose/nozzle SOP", "url": "/hose-advancement-checklist.html", "scope": "Line packages, nozzle types, and advancement methods are local."}],
                relatedSkills=["ff1_fire_attack", "ff1_water_supply", "probation_hose_advancement", "ff1_scba"],
                searchKeywords=["hose", "attack line", "nozzle", "advance", "kink", "preconnect", "engine company"],
            ),
            skill(
                id="ff1_ground_ladders",
                certificationId="firefighter_1",
                title="Ground Ladders",
                aliases=["ladders", "ground ladder", "raise a ladder", "24 foot", "extension ladder"],
                category="Ladders",
                careerStage="firefighter",
                summary="Select, carry, raise, place, and climb a ground ladder for a stated objective: access, rescue, ventilation, or egress.",
                whyItMatters="A ladder in the right place is a firefighter’s second staircase. A ladder in the wrong place is a trip hazard that helps no one.",
                learningPoints=["Objective first: rescue, ingress, egress, or ventilation changes placement.", "Tip, heel, angle, and locking devices are not optional.", "Climbing with tools requires a plan for three points of contact and tool control.", "Inspect before and after — bent fly sections lie."],
                beforeYouDo=["Know the lengths on YOUR rig and what each is for.", "Spot overhead wires every raise."],
                terminology=[{"term": "Fly / bed", "meaning": "Moving and base sections of an extension ladder."}, {"term": "Heel", "meaning": "The base — footing and placement start here."}],
                safetyNotes=["Electrical contact can kill. Look up.", "Do not overreach from the ladder.", "Footing on ice, gravel, and slope needs a plan."],
                seeResources=[res("Ground Ladder Angle Calculator", "/ground-ladder-angle-calculator.html", "Placement angle check.", "calculator")],
                practiceResources=[
                    res("Ground Ladder Angle Calculator", "/ground-ladder-angle-calculator.html", "Angle and reach.", "calculator"),
                    res("Fire Skill Wheel", "/fire-skill-wheel.html", "Ladder raises.", "wheel"),
                    res("Focus Drills — ladders", "/focus-drills.html?level=firefighter_1&topic=ladder", "Objective-based selection.", "drill"),
                    res("Firefighter Skills Checklist", "/firefighter-skills-checklist.html", "Rep tracking.", "checklist"),
                ],
                drill=drill(
                    "Given an objective, select and place the correct department ladder, raise, make the climb, and recover.",
                    "Department ground ladders, PPE, helmets, spotter, cones or a building face.",
                    "Clear overhead hazards. Assign tip and heel. State the objective before the raise.",
                    mode("5-minute review", "Match three objectives to three ladder choices on your rig.", ["Correct selection"], ["Always pulling the same ladder"], ["Why not the roof ladder here?"]),
                    mode("15-minute raise", "Carry, raise, extend, set hooks/locks, climb to a mark, recover.", ["Locks set", "Angle reasonable", "Heel footed"], ["Fly inverted", "No overhead check"], ["Could a victim come down this?"]),
                    mode("30-minute objective circuit", "Three placements: window rescue, roof access, and secondary egress. Time is secondary to correct placement.", ["Objective-driven", "Safe recover"], ["Leaving ladders as obstacles"], ["Which placement would you change on a real building?"]),
                ),
                readinessQuestions=[
                    q("Before raising any ladder, a required visual is:", ["The pump panel", "Overhead wires and obstructions", "The hydrant color", "Social media"], 1, "Look up."),
                    q("Ladder selection should start with:", ["Whatever is on top", "The objective: access, rescue, ventilation, or egress", "The newest firefighter’s preference", "Always the longest ladder"], 1, "Length and type follow the job."),
                    q("Climbing a ladder that is not locked/tied per department practice is:", ["Faster", "Unacceptable", "Fine for short climbs", "Only an officer problem"], 1, "Unsecured ladders move when you need them most."),
                ],
                officialSources=src("nfa") + [{"label": "Department ladder SOP and ladder manufacturer inspection guidance", "url": "/ground-ladder-angle-calculator.html", "scope": "Raise methods, tying, and inspection intervals are local and manufacturer-specific."}],
                relatedSkills=["ff1_search", "ff1_ventilation", "probation_ladders", "ff1_forcible_entry"],
                searchKeywords=["ladder", "raise", "extension", "roof ladder", "angle", "heel", "wires"],
            ),
            skill(
                id="ff1_forcible_entry",
                certificationId="firefighter_1",
                title="Forcible Entry",
                aliases=["forcible entry", "irons", "force the door", "through the lock"],
                category="Forcible Entry",
                careerStage="firefighter",
                summary="Read the door, pick tools, control the door after it opens, and force only as much as the objective requires.",
                whyItMatters="The door is both an obstacle and a flow-path control device. How you force it changes the fire.",
                learningPoints=["Inward vs outward, metal vs wood, and multiple locks change the plan.", "Gap, set, force — with door control as part of the plan.", "Through-the-lock is a skill, not a slogan.", "The objective might be search, attack, or ventilation — that changes how wide you open."],
                beforeYouDo=["Irons or the department’s assigned FE tools.", "A training door if possible; otherwise a walk-through on a real (non-damage) door construction."],
                terminology=[{"term": "Gap / set / force", "meaning": "Create a purchase, set the tool, then apply force."}, {"term": "Door control", "meaning": "Managing the opening so you control flow path and entry."}],
                safetyNotes=["Tools bounce. Eye protection and body position.", "Do not force utilities or the wrong occupancy.", "Glass and security bars are extra hazards."],
                practiceResources=[
                    res("Focus Drills — forcible entry", "/focus-drills.html?level=firefighter_1&topic=forcible", "Conventional FE reps.", "drill"),
                    res("Fire Skill Wheel", "/fire-skill-wheel.html", "Tool work.", "wheel"),
                    res("Firefighter I/II Tools", "/firefighter-1-2-tools.html", "Skill hub.", "guide"),
                ],
                drill=drill(
                    "Size up a door, state the plan, and complete conventional force on a training door — including door control after it opens.",
                    "Training door, irons or assigned tools, PPE, eye protection.",
                    "If no prop, walk real doors and dry-run tool placement without damage.",
                    mode("5-minute review", "Identify swing, likely locks, and first tool for three door photos or real doors.", ["Correct swing", "Tool choice"], ["Hitting the knob first every time"], ["What is our door-control plan?"]),
                    mode("15-minute force", "Gap-set-force reps with rotating roles. Control the door after it opens.", ["Purchase", "Control"], ["Widening for no reason"], ["Would we have vented the fire by accident?"]),
                    mode("30-minute FE problem set", "Metal door, inward wood, and a ‘through the lock’ talk-through. Include a failed first attempt and a tool change.", ["Adapt", "Communication"], ["Destroying the door past the objective"], ["When do we go to a window instead?"]),
                ),
                readinessQuestions=[
                    q("After the door is forced, a critical next thought is:", ["Walk away", "Door control and what the opening does to the fire", "Drop the irons in the yard", "Turn on a fan immediately always"], 1, "You just changed the building’s ventilation."),
                    q("Forcible entry size-up starts with:", ["The biggest tool", "Door swing, construction, locks, and the assignment", "Kicking first", "Waiting for a truck company even when you are the truck"], 1, "Read the door."),
                    q("Using more destruction than the objective needs:", ["Proves toughness", "Can delay the job, create hazards, and worsen flow path", "Is required by NFPA in all cases", "Always makes search faster"], 1, "Force to the objective."),
                ],
                officialSources=src("nfa", "fsri") + [{"label": "Department forcible-entry and occupancy SOP", "url": "/firefighter-1-2-tools.html", "scope": "When and how to force, and who authorizes damage, are local."}],
                relatedSkills=["ff1_search", "ff1_fire_attack", "ff1_ventilation"],
                searchKeywords=["forcible entry", "irons", "halligan", "flathead", "door control", "through the lock"],
            ),
            skill(
                id="ff1_search",
                certificationId="firefighter_1",
                title="Primary Search",
                aliases=["search", "primary search", "oriented search", "victim search"],
                category="Search",
                careerStage="firefighter",
                summary="Search with team integrity, orientation, a purpose, and a way out — then communicate what you found or did not find.",
                whyItMatters="Search is a life-saving assignment that also kills firefighters who lose the wall, the partner, or the exit.",
                learningPoints=["Stay oriented: wall, hose, thermal imager per department, and a partner.", "The search pattern should match the occupancy and the fire location.", "Victim removal is a different skill from locating — plan the path out.", "A ‘clear’ room is a report, not a hope."],
                beforeYouDo=["SCBA, radio, light, tool, TIC if issued.", "Know the entry point and the fire location as you understand it."],
                terminology=[{"term": "Oriented search", "meaning": "Maintaining a known reference (wall, hose, partner) so you can leave."}, {"term": "Primary search", "meaning": "Rapid search for savable lives given current conditions — not a leisurely inventory."}],
                safetyNotes=["Do not search above an uncontrolled fire without a plan.", "Holes in floors, wires, and collapse are search problems.", "If you cannot find the exit, that is a Mayday problem — early."],
                seeResources=[res("Search and Rescue Size-Up", "/search-and-rescue-sizeup.html", "Organize search factors before you enter.", "checklist")],
                practiceResources=[
                    res("Search and Rescue Size-Up", "/search-and-rescue-sizeup.html", "Size-up structure.", "checklist"),
                    res("SCBA Air Management Calculator", "/scba-air-management-calculator.html", "Air vs search time.", "calculator"),
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Life hazard and coordination.", "simulator"),
                    res("Focus Drills — search", "/focus-drills.html?level=firefighter_1&topic=search", "Oriented search.", "drill"),
                ],
                drill=drill(
                    "Complete an oriented primary search in a controlled environment, locate a training victim or a ‘clear,’ and exit as a team.",
                    "SCBA, PPE, search line or hose as used, dummy or object, radios, optional TIC.",
                    "Use a training maze, darkened bay, or furnished room with instructor control. Set a time and air check.",
                    mode("5-minute review", "State pattern, team jobs, and Mayday triggers for a one-story bedroom search.", ["Pattern named", "Exit plan"], ["Split up to ‘cover more ground’"], ["What do we say if we find a victim?"]),
                    mode("15-minute search", "Enter, search two rooms, maintain contact, exit. Debrief orientation mistakes.", ["Team integrity", "Orientation"], ["Losing the wall", "No radio"], ["Where did we get disoriented?"]),
                    mode("30-minute search + removal", "Find a dummy, choose a removal method, and get to the door. Include a lost-exit inject that is stopped before it is unsafe.", ["Victim path", "Air check", "Mayday criteria"], ["Dragging without a path", "Search past low air"], ["Would we have called a Mayday soon enough?"]),
                ),
                readinessQuestions=[
                    q("Losing contact with your partner during search is:", ["Efficient", "A serious integrity failure — correct it immediately", "Required in large buildings", "Only a problem if there is fire"], 1, "Team integrity is the search."),
                    q("A primary search should be shaped by:", ["Furniture arrangement only", "Fire location, occupancy, access, staffing, and conditions", "Always starting at the basement", "The newest map app"], 1, "Search where savable lives are most likely, with a way out."),
                    q("If you cannot find the exit and air is dropping:", ["Keep searching one more room", "Treat it as an emergency — Mayday/self-rescue per SOP", "Remove the mask to see better", "Split up"], 1, "Hope is not an orientation plan."),
                ],
                officialSources=src("niosh", "nfa", "fsri") + [{"label": "Department search, TIC, and Mayday SOP", "url": "/search-and-rescue-sizeup.html", "scope": "Search methods and RIT/Mayday language are local."}],
                relatedSkills=["ff1_scba", "ff1_communications_mayday", "ff1_forcible_entry", "ff1_hose_advancement"],
                searchKeywords=["search", "primary", "victim", "orientation", "tic", "mayday", "team integrity"],
            ),
            skill(
                id="ff1_ventilation",
                certificationId="firefighter_1",
                title="Ventilation Support",
                aliases=["ventilation", "vent", "horizontal vent", "flow path"],
                category="Ventilation",
                careerStage="firefighter",
                summary="Ventilation is a fire-behavior tool. Openings must match the attack, the search, and the chosen flow path — not habit.",
                whyItMatters="Wrong ventilation makes the fire bigger, faster, and closer to people. Timing is the skill.",
                learningPoints=["Horizontal and vertical ventilation have different effects and risks.", "Coordinate with suppression and search. Uncoordinated holes are extra doors for the fire.", "Know what you are trying to do: limited visibility, heat, victim, or fire travel.", "Read smoke. If you cannot explain the opening, do not make it."],
                beforeYouDo=["Know the fire location and the attack plan as briefed.", "PPE/SCBA and fall protection as the assignment requires."],
                terminology=[{"term": "Flow path", "meaning": "The route air and fire gases take from inlet to exhaust."}, {"term": "Horizontal ventilation", "meaning": "Openings in walls/windows rather than the roof."}],
                safetyNotes=["Roof operations need a sound roof, a ladder, and a reason.", "Breaking glass injures people below.", "Do not vent into a path that pushes fire over a search team."],
                seeResources=[res("Ventilation Checklist", "/ventilation-checklist.html", "Planning and coordination points.", "checklist")],
                practiceResources=[
                    res("Ventilation Checklist", "/ventilation-checklist.html", "Before you cut or break.", "checklist"),
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Openings and fire behavior.", "simulator"),
                    res("Focus Drills — ventilation", "/focus-drills.html?level=firefighter_1&topic=ventilation", "Opening selection.", "drill"),
                    res("FSRI Fire Safety Academy", "https://training.fsri.org/", "Research-based fire dynamics.", "official"),
                ],
                drill=drill(
                    "Given a simple residential fire picture, choose whether, where, and when to ventilate, and coordinate it with a charged line.",
                    "Building photos or a drill tower, charged line or tabletop, radios, ventilation tools as assigned.",
                    "No live fire required. Use FSRI-informed discussion: inlet, exhaust, and people.",
                    mode("5-minute review", "Define the intended exhaust and who is on the line before any window comes out.", ["Coordination named"], ["Vent for ‘fresh air’ with no plan"], ["Who can stop the opening?"]),
                    mode("15-minute decision drill", "Three photos: fire in a rear bedroom, basement, and kitchen. Pick openings and timing.", ["Why/where/when", "Search considered"], ["Roof-first always"], ["What smoke change would you expect?"]),
                    mode("30-minute coordinated evolution", "Line in place, then a horizontal opening on command. Debrief smoke/heat talk and a ‘too early’ inject.", ["Wait for water", "Communication"], ["Independent freelancing"], ["Did we make it better for the search or worse?"]),
                ),
                readinessQuestions=[
                    q("Ventilation without coordination with suppression/search can:", ["Only help", "Create a flow path that grows the fire toward people", "Never matter on single-family dwellings", "Replace the need for water"], 1, "Openings are tactical."),
                    q("The first question before making an opening is:", ["Do I have the biggest saw?", "What is the objective, and is water/search ready for the change?", "Will it look good from the street?", "Did someone already break the front window for no reason — should I copy?"], 1, "Objective and timing."),
                    q("Vertical ventilation is:", ["Always safer than windows", "A high-risk assignment that needs a sound roof, staffing, and a reason", "Required on every fire", "The same as opening the front door"], 1, "Roofs kill firefighters when the reason and the roof are wrong."),
                ],
                officialSources=src("fsri", "nfa", "niosh") + [{"label": "Department ventilation SOP", "url": "/ventilation-checklist.html", "scope": "When to vent, PPV policy, and roof ops are local."}],
                relatedSkills=["ff2_ventilation", "ff1_fire_attack", "ff1_search", "ff1_ground_ladders"],
                searchKeywords=["ventilation", "flow path", "horizontal", "vertical", "PPV", "smoke", "roof"],
            ),
            skill(
                id="ff1_water_supply",
                certificationId="firefighter_1",
                title="Water Supply Support",
                aliases=["water supply", "hydrant catch", "supply line", "drop a line"],
                category="Water Supply",
                careerStage="firefighter",
                summary="Catch a hydrant, manage supply hose, and support the engine as assigned — the pump operator cannot do this alone.",
                whyItMatters="Firefighter I water-supply work is how the engineer gets a chance to be good.",
                learningPoints=["Know the department hydrant hookup from the ground person’s view.", "Kinks, adapters, and a closed steamer cap are your problems.", "Communicate when the hydrant is made — and when it is not.", "Traffic and hose in the street are part of the skill."],
                beforeYouDo=["Hydrant kit locations on the assigned engine.", "Which outlet and hose the department wants first."],
                terminology=[{"term": "Supply line", "meaning": "Hose from source to the pump, often LDH."}, {"term": "Hydrant assist", "meaning": "The firefighter making the hydrant while the engine spots."}],
                safetyNotes=["You are in the street. Visibility and traffic control.", "Charging LDH can move violently."],
                seeResources=[res("Hydrant Flow Calculator", "/hydrant-flow-calculator.html", "Why residual will matter to the operator you are supporting.", "calculator")],
                practiceResources=[
                    res("Hose Advancement Checklist", "/hose-advancement-checklist.html", "Related hose handling.", "checklist"),
                    res("Hydrant Inspection Log", "/hydrant-inspection-log.html", "Know the hydrants in first-due.", "log"),
                    res("Focus Drills — hydrant", "/focus-drills.html?level=firefighter_1&topic=hydrant", "Connection reps.", "drill"),
                    res("Hydrant Operations skill (engineer view)", "/skill-support.html?cert=driver_operator_pumper&task=do_pumper_hydrant_ops", "What the operator is watching.", "skill"),
                ],
                drill=drill(
                    "Complete a department hydrant catch, dress the hose, and report ‘water available’ with a meaning the operator shares.",
                    "Hydrant kit, supply hose, engine or hydrant prop, PPE, traffic vests as required.",
                    "Use a training hydrant if live water is restricted. Agree on the radio words.",
                    mode("5-minute review", "Lay out the kit and say the sequence including slow open.", ["Sequence"], ["Opening wide immediately"], ["What if the cap will not spin?"]),
                    mode("15-minute catch", "Drop, wrap or connect per SOP, charge on command, clear kinks, report.", ["Connection", "Kinks", "Report"], ["Standing over the hose"], ["Did the operator actually have water?"]),
                    mode("30-minute engine support", "Hydrant plus pulling the first attack line, then resetting both. Include a bad hydrant inject (cap, no water) and a move to a second hydrant talk-through.", ["Problem reported early", "Team reset"], ["Silent failure at the hydrant"], ["When do we abandon this hydrant?"]),
                ),
                readinessQuestions=[
                    q("A hydrant firefighter should open the valve:", ["As fast as possible", "In a controlled manner per SOP, after the connection is made and the operator is ready", "Only after the fire is out", "With a power saw"], 1, "Controlled water prevents hammer and surprises."),
                    q("If the hydrant is dry or broken, you should:", ["Keep it a secret", "Report immediately so the operator can change the plan", "Wait five minutes", "Connect anyway and hope"], 1, "Early bad news is useful news."),
                    q("Supply hose kinks:", ["Do not matter in LDH", "Can starve the pump just like a closed valve", "Increase residual pressure", "Are the officer’s only job"], 1, "Dress the line."),
                ],
                officialSources=src("nfa") + [{"label": "Department water-supply SOP", "url": "/hydrant-inspection-log.html", "scope": "Hydrant connections, LDH, and first-due hydrant programs are local."}],
                relatedSkills=["do_pumper_hydrant_ops", "ff1_hose_advancement", "probation_hydrant"],
                searchKeywords=["hydrant", "supply line", "LDH", "water supply", "catch a hydrant"],
            ),
            skill(
                id="ff1_fire_attack",
                certificationId="firefighter_1",
                title="Fire Attack Fundamentals",
                aliases=["fire attack", "fire control", "stream", "hit the fire", "interior attack"],
                category="Fire Control",
                careerStage="firefighter",
                summary="Apply an effective stream as part of a team: the right stream, the right place, coordinated with ventilation and search.",
                whyItMatters="Cooling fuel and controlling the flow path is how room-and-contents fires stay room-and-contents fires.",
                learningPoints=["Direct, indirect, and combination streams are tools with reasons.", "Gas cooling / hitting what you can see depends on conditions and training — follow department fire-dynamics doctrine.", "A stream that never reaches the seat is noise.", "Know when you are the attack line vs a backup/protection line."],
                beforeYouDo=["Charged line, SCBA, a defined fire problem (prop, picture, or simulator).", "Agreement on the attack mode the officer wants."],
                terminology=[{"term": "Seat of the fire", "meaning": "Where the bulk of the burning is — the target if you can reach it safely."}, {"term": "Backup line", "meaning": "A second line protecting crew and egress, not a decoration."}],
                safetyNotes=["Steam, collapse, and flashover cues are more important than ‘getting a good hit’ on video.", "Do not pass fire if your department’s tactic and staffing say otherwise."],
                seeResources=[res("Fireground Decision Sim", "/fireground-decision-sim.html", "Attack, water, and coordination cases.", "simulator")],
                practiceResources=[
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Tactical choices.", "simulator"),
                    res("Hose Advancement Checklist", "/hose-advancement-checklist.html", "Get the line there.", "checklist"),
                    res("Nozzle Reaction Calculator", "/nozzle-reaction-calculator.html", "Why the line is hard to hold.", "calculator"),
                    res("FSRI Fire Safety Academy", "https://training.fsri.org/", "Fire dynamics.", "official"),
                ],
                drill=drill(
                    "Given a residential fire problem, state the stream objective, advance, apply water on command, and report the effect.",
                    "Attack line, nozzle, pictures or a burn building if authorized, radios.",
                    "No unauthorized live fire. Use a simulator, photos, or an acquired-structure program under instructors.",
                    mode("5-minute review", "From a photo, name fire location, stream choice, and one condition that would stop interior attack.", ["Go/no-go named"], ["Always interior"], ["What does dark turbulent smoke suggest to you?"]),
                    mode("15-minute hit and report", "Advance to a door, apply water to a target, give a conditions report.", ["Effective stream", "CAN-style report"], ["Opening the nozzle down the hallway forever"], ["Did the smoke behave as we expected?"]),
                    mode("30-minute coordinated attack", "Line, a search assignment, and a ventilation decision. Debrief sequence.", ["Coordination", "Water before vent if that is the plan"], ["Freelancing"], ["Who owned the fire room?"]),
                ),
                readinessQuestions=[
                    q("An attack line that cannot reach the fire:", ["Still counts if it is loud", "Needs a better position, more hose, or a different tactic", "Should be opened to ‘cool the hallway’ forever without a plan", "Means you should drop the nozzle and search alone"], 1, "The stream has to do work on the problem."),
                    q("Fire attack should be coordinated with:", ["Nothing — speed only", "Search, ventilation, and water supply", "Only the media", "The second-due chief’s parking"], 1, "It is a company problem."),
                    q("If conditions worsen when you open a door:", ["Ignore it", "Control the door, apply water as trained, and reassess — you may have changed the flow path", "Vent the whole first floor immediately", "Remove SCBA"], 1, "The building will tell you."),
                ],
                officialSources=src("fsri", "nfa", "niosh") + [{"label": "Department fire-attack SOP", "url": "/fireground-decision-sim.html", "scope": "Interior vs exterior, stream type, and staffing model are local."}],
                relatedSkills=["ff1_hose_advancement", "ff1_ventilation", "ff1_search", "ff1_scba"],
                searchKeywords=["fire attack", "stream", "nozzle", "interior", "flashover", "gas cooling"],
            ),
            skill(
                id="ff1_communications_mayday",
                certificationId="firefighter_1",
                title="Communications and Mayday",
                aliases=["mayday", "radio", "emergency traffic", "lumans", "who what where"],
                category="Communications",
                careerStage="firefighter",
                summary="Use the radio so people can help you: routine traffic, progress, and a Mayday that includes location, unit, and the problem.",
                whyItMatters="A silent firefighter in trouble is a body recovery. A clear Mayday is a rescue problem with a chance.",
                learningPoints=["Know the channel, how to key, and how to declare emergency traffic per SOP.", "Mayday: who, what, where — and air/crew status if you can.", "Practice before you need it. Stress shrinks vocabulary.", "Routine radio discipline makes emergency radio possible."],
                beforeYouDo=["Department Mayday policy and portable radio layout.", "Your riding assignment name (Engine 1 backup, etc.)."],
                terminology=[{"term": "Mayday", "meaning": "Firefighter emergency — lost, trapped, injured, missing, or in imminent danger per department definition."}, {"term": "Emergency traffic", "meaning": "Priority radio, not the same as a Mayday in every system — know the difference locally."}],
                safetyNotes=["Do not wait until the last breath to call.", "If you cannot talk, a PASS and a crew that notices your absence still matter — accountability is part of this skill."],
                practiceResources=[
                    res("Focus Drills — radio/Mayday", "/focus-drills.html?level=firefighter_1&topic=mayday", "Format practice.", "drill"),
                    res("Search and Rescue Size-Up", "/search-and-rescue-sizeup.html", "Location language.", "checklist"),
                    res("Fireground Decision Sim", "/fireground-decision-sim.html", "Communications under stress.", "simulator"),
                    res("Study Center", "/study-center.html?track=academy", "Comms review.", "guide"),
                ],
                drill=drill(
                    "Deliver a correct Mayday on a training channel, then a routine CAN report, using department format.",
                    "Training radios or a timer and a written format card, PPE/SCBA optional for realism.",
                    "Use a training talkgroup. Never practice Mayday on a live dispatch channel.",
                    mode("5-minute review", "Recite the department Mayday format from memory.", ["Who/what/where"], ["Rambling"], ["What channel?"]),
                    mode("15-minute radio reps", "Five Maydays from different locations (basement, floor 2 Charlie, yard). Crew acknowledges correctly.", ["Format", "Acknowledgement"], ["Talking over the Mayday"], ["Did location make sense to the RIT?"]),
                    mode("30-minute scenario", "Search evolution ends in a simulated lost-exit. Call the Mayday, then follow self-rescue/RIT talk-through per SOP.", ["Timely call", "Accountability"], ["Waiting too long"], ["What would RIT need that we did not give?"]),
                ),
                readinessQuestions=[
                    q("A Mayday should include at least:", ["A joke to stay calm", "Who you are, what the problem is, and where you are — plus air/crew if you can", "Only your first name", "A complete autobiography"], 1, "Rescuers cannot help a mystery."),
                    q("You should call a Mayday:", ["Only when the cylinder is empty", "When you are lost, trapped, injured, or in imminent danger per SOP — early", "After you have already self-rescued", "Never if you are a probationary firefighter"], 1, "Early Maydays are successful Maydays."),
                    q("Practice Maydays belong on:", ["The primary dispatch channel during dinner", "A training channel or recorded drill per department rules", "Social media live", "No practice — it is bad luck"], 1, "Do not create a real emergency to train."),
                ],
                officialSources=src("niosh", "nfa") + [{"label": "Department Mayday / RIT / radio SOP", "url": "/focus-drills.html?level=firefighter_1&topic=mayday", "scope": "Mayday language and emergency-button behavior are local."}],
                relatedSkills=["ff1_search", "ff1_scba", "fo1_initial_radio_report", "probation_radio"],
                searchKeywords=["mayday", "radio", "emergency traffic", "accountability", "rit", "pass"],
            ),
            skill(
                id="ff1_overhaul_salvage",
                certificationId="firefighter_1",
                title="Overhaul and Salvage",
                aliases=["overhaul", "salvage", "property conservation", "hidden fire"],
                category="Overhaul",
                careerStage="firefighter",
                summary="Find hidden fire without destroying evidence or people, and protect property that the fire did not already take.",
                whyItMatters="Rekindle, injuries during overhaul, and ruined belongings are preventable company failures.",
                learningPoints=["Overhaul is still a hazardous atmosphere — respiratory protection per SOP.", "Look for hidden fire with a purpose, not random demolition.", "Salvage can happen during the fire, not only after.", "Evidence and origin/cause need a thought before you toss the room."],
                beforeYouDo=["TIC if issued, tools, salvage covers as carried, lighting."],
                terminology=[{"term": "Overhaul", "meaning": "Searching for and extinguishing hidden fire."}, {"term": "Salvage", "meaning": "Protecting property from fire, smoke, and water."}],
                safetyNotes=["Holes, wiring, and remaining collapse risk.", "Do not remove SCBA just because flames are gone if policy says the atmosphere is still bad."],
                practiceResources=[
                    res("Focus Drills — overhaul", "/focus-drills.html?level=firefighter_1&topic=overhaul", "Hazard scan.", "drill"),
                    res("Fire Skill Wheel", "/fire-skill-wheel.html", "Salvage cover work.", "wheel"),
                    res("Firefighter Skills Checklist", "/firefighter-skills-checklist.html", "Salvage/overhaul items.", "checklist"),
                ],
                drill=drill(
                    "Scan a room for overhaul hazards, open a designated void, and deploy a salvage cover or water-control method.",
                    "Training room, TIC if available, salvage cover, pike pole, lighting.",
                    "Instructor marks ‘do not open’ evidence items.",
                    mode("5-minute review", "List five overhaul hazards before any opening.", ["Hazards named"], ["Yanking ceiling first"], ["When do we stay on air?"]),
                    mode("15-minute salvage + scan", "Cover a mock contents pile, then open one assigned void.", ["Property protected", "Controlled opening"], ["Trashing the room"], ["What did we preserve for investigation?"]),
                    mode("30-minute overhaul problem", "Hidden-fire hunt with a TIC talk-through, electrical hazard, and a rekindle checkpoint.", ["Systematic", "Respiratory protection"], ["Bare-face in junk"], ["What would make us call the fire back?"]),
                ),
                readinessQuestions=[
                    q("Overhaul atmospheres:", ["Are always safe when flames are gone", "Can still be IDLH — follow department respiratory rules", "Only need a dust mask", "Are a civilian problem"], 1, "Smoke and CO do not respect knockdown."),
                    q("Salvage is:", ["Only for insurance adjusters", "A firefighter skill that can run with attack", "Unprofessional", "Always after the investigation is done, never during"], 1, "Throwing water on someone’s remaining property without a cover is optional, not inevitable."),
                    q("If you might be in the origin area:", ["Start dumping drawers for fun", "Minimize unnecessary disturbance and notify the officer/investigator path per SOP", "Soak everything equally", "Take souvenirs"], 1, "Cause determination starts with what you did not destroy."),
                ],
                officialSources=src("nfa", "niosh") + [{"label": "Department overhaul, exposure, and investigation SOP", "url": "/firefighter-1-2-tools.html", "scope": "When to remove SCBA and how to protect origin areas are local."}],
                relatedSkills=["ff2_evidence_overhaul", "ff1_fire_attack", "ff1_scba"],
                searchKeywords=["overhaul", "salvage", "rekindle", "tic", "property conservation", "hidden fire"],
            ),
        ],
    }
