#!/usr/bin/env python3
"""Build interactive study decks for every Roadmap certification ID."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def deck(label, summary, guide, cards, quiz, next_steps, tools):
    return {
        "label": label,
        "summary": summary,
        "guide": guide,
        "cards": cards,
        "quiz": quiz,
        "next": next_steps,
        "tools": tools,
    }


def q(prompt, choices, correct, why):
    return [prompt, choices, correct, why]


DECKS = {
    "firefighter_1": deck(
        "Firefighter I",
        "Core structural-firefighting knowledge: PPE/SCBA, fire behavior, hose, ladders, search, and safety. Preparation only—follow your academy and certifying authority.",
        [
            ["PPE and SCBA", "Inspect, don, and check interfaces before entry. Treat low-air as a cue to follow department air-management policy, not a target for remaining inside."],
            ["Fire behavior", "Heat transfer, ventilation-limited fire, flow paths, and door control change interior conditions as soon as an opening is made."],
            ["Hose and nozzles", "Deploy, flake, charge, and advance with nozzle and backup communication. Fix kinks before blaming water supply."],
            ["Ladders and search", "Select a ladder for the objective, maintain crew integrity, and keep an exit plan during oriented search."],
            ["Mayday readiness", "Know how to declare emergency traffic, stay oriented, and support RIC without becoming a second victim."],
        ],
        [
            ["What is a flow path?", "The route heated gases, smoke, and air move between higher- and lower-pressure areas or openings."],
            ["Why inspect PPE interfaces?", "Hood, gloves, coat, and facepiece gaps are common failure points during heat and work."],
            ["Low-air alarm means?", "Act on department air-management policy; it is not a remaining-work target."],
            ["Why coordinate a door opening?", "An opening can add oxygen and strengthen a flow path before suppression is ready."],
            ["Good search habit?", "A systematic pattern, partner contact, communication, and a planned exit."],
            ["What belongs in a skill log?", "De-identified skill, repetitions, feedback, and lessons—not PHI or official sign-off."],
        ],
        [
            q("Before forcing a smoke-charged exterior door, you should:", ["Open immediately for more air", "Coordinate the opening with the line/search plan and read conditions", "Vent every window first"], 1, "Openings change ventilation and fire behavior."),
            q("The best reason to study building construction is to:", ["Predict exact collapse time", "Recognize fire-spread and structural risk clues", "Choose apparatus color"], 1, "Construction knowledge supports risk recognition, not fortune-telling."),
            q("A charged attack line will not advance because of kinks. First action:", ["Increase pump pressure immediately", "Clear hose management and communicate with the operator", "Abandon the line"], 1, "Hose management often solves apparent pressure problems."),
            q("Mayday practice should emphasize:", ["Speed over air", "Orientation, emergency traffic, and crew integrity", "Leaving your partner to find a window"], 1, "Rare high-consequence skills degrade without rehearsal."),
        ],
        ["Log hands-on repetitions, not just reading time.", "Run a Firefighter I focus drill after each topic.", "Ask an instructor what 'good' looks like on your department's skill sheets."],
        [
            ["Firefighter I/II tools", "/firefighter-1-2-tools.html"],
            ["Focus drills", "/focus-drills.html?source=roadmap&level=firefighter_1"],
            ["Study Center — Academy", "/study-center.html?track=academy"],
        ],
    ),
    "firefighter_2": deck(
        "Firefighter II",
        "Company-level coordination: ventilation timing, search, salvage/overhaul, standpipe concepts, and supporting command. Confirm JPRs with your certifying agency.",
        [
            ["Coordinated ventilation", "Vent timing, location, and method must match suppression and search—not happen as a standalone task."],
            ["Search with conditions", "Primary search priorities change with fire location, staffing, and ventilation. Keep crew integrity."],
            ["Standpipe / high-rise support", "Pack arrangement, floor control, pressure considerations, and communications matter more than a single formula."],
            ["Salvage and overhaul", "Protect property and evidence while finishing the fire problem. Watch for hidden fire and structural compromise."],
            ["Company communications", "Concise progress, needs, and hazards keep the officer's picture current."],
        ],
        [
            ["Why coordinate ventilation?", "Openings can change fire behavior, interior tenability, and search conditions."],
            ["RIT is assigned to:", "Firefighter rescue support—not a secondary attack crew unless reassigned."],
            ["Useful progress report?", "Location, task, conditions, needs, and anything that changed the plan."],
            ["Overhaul caution?", "Hidden fire, structural compromise, and evidence preservation can all be in play."],
            ["Standpipe pack purpose?", "Get a working line to the fire floor with the right fittings, length, and communication."],
            ["When should strategy change?", "When risk/benefit, conditions, resources, or progress no longer support it."],
        ],
        [
            q("Ventilation before water on fire is risky because:", ["It always cools the building", "It can intensify the fire and worsen interior conditions", "It never affects search"], 1, "Coordinate openings with suppression."),
            q("A strong Firefighter II habit is:", ["Working independently of command", "Synchronizing search, attack, and ventilation", "Skipping salvage until the next shift"], 1, "Company-level work is coordinated work."),
            q("If conditions change during search, you should:", ["Continue the original pattern silently", "Communicate the change and reassess with your officer", "Vent every room immediately"], 1, "Changing conditions require a new picture."),
            q("Salvage during overhaul should:", ["Ignore possible evidence", "Balance fire extinguishment, property protection, and documentation", "Only happen after investigators arrive"], 1, "Do not destroy evidence unnecessarily, but finish the fire problem."),
        ],
        ["Run a coordinated ventilation tabletop.", "Practice a standpipe pack layout on the floor.", "Use Fireground Decision Sim after studying the topic."],
        [
            ["Firefighter I/II tools", "/firefighter-1-2-tools.html"],
            ["Fireground Decision Sim", "/fireground-decision-sim.html"],
            ["Focus drills", "/focus-drills.html?source=roadmap&level=firefighter_2"],
        ],
    ),
    "hazmat_awareness": deck(
        "HazMat Awareness",
        "Recognize, isolate, deny entry, and notify. Awareness does not authorize offensive product control.",
        [
            ["Stay in scope", "Awareness actions are recognition, isolation, notification, and protective-action support—not rescue in the hot zone."],
            ["Scene clues", "Occupancy, containers, placards, labels, shipping papers, and witnesses all matter. Do not guess a product."],
            ["Isolation", "Use current ERG/protective-action guidance and local SOP for initial isolation and downwind concerns."],
            ["Notifications", "Who needs to know, what they need, and which specialty resources come next."],
            ["ERG use", "Treat the ERG as an initial decision aid, not a complete product SDS or incident action plan."],
        ],
        [
            ["Awareness level does not include?", "Offensive product control or hot-zone rescue unless trained and assigned otherwise."],
            ["Best first information source?", "Scene clues plus current references—not a guessed chemical name."],
            ["Why isolate early?", "To protect responders and the public while more information is gathered."],
            ["Downwind matters because?", "Vapors and smoke can travel and expose people who are not at the source."],
            ["What to tell incoming units?", "Product clues, isolation in place, wind, exposures, and what you still do not know."],
            ["Unknown product default?", "Treat as a worst reasonable case until identified."],
        ],
        [
            q("You see a placard but cannot read the ID number. You should:", ["Assume it is diesel", "Isolate, deny entry, and use current references while gathering more clues", "Walk up to the tank for a better look"], 1, "Do not close the distance to unknown product."),
            q("Awareness-level responders should:", ["Begin diking in the hot zone", "Recognize, isolate, notify, and support protective actions", "Neutralize the product"], 1, "Stay inside Awareness scope."),
            q("The ERG is best used as:", ["A complete SDS", "An initial isolation and protective-action aid", "A substitute for department SOP"], 1, "Follow current ERG and local protocol together."),
            q("A strong notification includes:", ["Only the street name", "Clues, isolation, wind/exposures, and unknowns", "A guaranteed product name"], 1, "Honesty about uncertainty is useful."),
        ],
        ["Practice placard recognition.", "Walk an isolation tabletop with a map.", "Confirm your department's Awareness SOG."],
        [
            ["HazMat Awareness study guide", "/hazmat-awareness-study-guide.html"],
            ["Placard reference", "/hazmat-placard-reference.html"],
            ["HazMat tools", "/hazmat-tools.html"],
        ],
    ),
    "hazmat_operations": deck(
        "HazMat Operations",
        "Defensive operations: zones, decon support, PPE limits, and resource requests within Operations scope.",
        [
            ["Zones", "Hot, warm, and cold zones control access. Adjust for wind, terrain, and changing product information."],
            ["Defensive actions", "Isolation, diking concepts, vapor suppression concepts, and waiting for specialty resources based on risk."],
            ["Decon support", "Corridor flow, contamination control, and protecting the cold zone. Follow local decon SOP."],
            ["PPE limits", "Protective clothing has limits. Do not invent product certainty to justify the wrong ensemble."],
            ["ICS support", "Clear objectives, accountability, and resource requests keep Operations work inside command."],
        ],
        [
            ["Operations vs Awareness?", "Operations can support defensive control and decon; Awareness primarily recognizes and isolates."],
            ["Warm zone purpose?", "Support, decon, and controlled access—not a second hot zone."],
            ["Why control the cold line?", "To prevent spreading contamination to uncontaminated people and equipment."],
            ["Defensive does not mean?", "Entering to plug a leak without training, PPE, and assignment."],
            ["Useful resource request?", "What you have, what you need, product clues, and exposures."],
            ["When to wait?", "When risk, PPE limits, or unknown product exceed your level and assignment."],
        ],
        [
            q("A decon corridor should:", ["Allow free travel both directions", "Have a clear dirty-to-clean flow and contamination control", "Be set up inside the hot zone"], 1, "Flow and control prevent spread."),
            q("Choosing PPE at Operations level should:", ["Ignore product clues", "Use current references and department policy", "Always use structural firefighting gear"], 1, "PPE has limits; policy and references matter."),
            q("Diking is generally:", ["An Awareness-only task", "A defensive option when trained, equipped, and assigned", "Always required immediately"], 1, "Stay in scope and assignment."),
            q("If the product remains unknown, you should:", ["Assume the least hazardous case", "Keep isolation and treat as a worst reasonable case", "Enter to smell it"], 1, "Unknowns raise, not lower, caution."),
        ],
        ["Set up a decon corridor walk-through.", "Run an isolation tabletop.", "Review current ERG protective-action pages."],
        [
            ["HazMat Operations study guide", "/hazmat-operations-study-guide.html"],
            ["Decon corridor planner", "/decon-corridor-planner.html"],
            ["HazMat size-up checklist", "/hazmat-sizeup-checklist.html"],
        ],
    ),
    "hazmat_technician": deck(
        "HazMat Technician",
        "Technician work is agency-specific. Use this deck for planning and support concepts—not as a substitute for technician training, SOPs, or medical direction.",
        [
            ["Training boundary", "Technician offensive control, monitoring, and specialized PPE require current training, medical clearance, and assignment."],
            ["Information quality", "SDS, shipping papers, monitoring, and technical specialists beat guessing."],
            ["Control options", "Containment, confinement, and recovery decisions depend on product, container, and risk—not a single favorite tactic."],
            ["Support the team", "Research, logistics, decon, and medical monitoring often determine whether an entry is even possible."],
            ["Documentation", "Actions, readings, times, and exposures matter for safety and later investigation."],
        ],
        [
            ["Technician work requires?", "Current training, medical clearance, PPE, and an assignment inside ICS."],
            ["Why research before entry?", "To match PPE, tactics, and medical support to the actual hazard."],
            ["Monitoring is used to:", "Inform decisions—not to create a false sense of safety by itself."],
            ["A good technician habit?", "Work one variable at a time and communicate readings and limits."],
            ["Who controls entry?", "The incident's command/safety system, not individual initiative."],
            ["After entry?", "Decon, medical monitoring, documentation, and a debrief of what changed."],
        ],
        [
            q("A technician should enter when:", ["Curious about the product", "Trained, equipped, assigned, and the risk/benefit supports it", "Awareness crews already walked in"], 1, "Assignment and controls come first."),
            q("SDS and monitoring data should:", ["Replace ICS", "Inform PPE and tactic selection", "Be ignored if you have a placard"], 1, "Better information improves decisions."),
            q("If readings exceed your ensemble limits:", ["Continue quickly", "Withdraw and reassess the plan", "Remove PPE to move faster"], 1, "Limits are limits."),
            q("Documentation after a technician operation should include:", ["Only the product name", "Actions, times, readings, exposures, and remaining hazards", "Nothing if nobody was hurt"], 1, "Records support safety and later review."),
        ],
        ["Review your agency technician SOGs.", "Practice research and ICS support roles.", "Do not use this deck as a technician skill sheet."],
        [
            ["HazMat tools", "/hazmat-tools.html"],
            ["Isolation planner", "/hazmat-isolation-planner.html"],
            ["Decon planner", "/decon-corridor-planner.html"],
        ],
    ),
    "driver_operator_pumper": deck(
        "Driver / Operator — Pumper",
        "Safe driving, placement, pump systems, hydraulics, water supply, and troubleshooting. Use department hose/nozzle packages—not generic coefficients alone.",
        [
            ["Arrive and place", "The first job is getting the apparatus and crew there safely and positioning for hose, water, and later units."],
            ["Pump systems", "Know intake/discharge paths, gauges, governor/relief, primer, and abnormal indications for YOUR apparatus."],
            ["Hydraulics", "PDP accounts for nozzle pressure, friction loss, elevation, and appliances. Mental math is a reasonableness check."],
            ["Water supply", "Hydrants, residual, drafting, relay, and tenders. Watch residual as demand changes."],
            ["Troubleshoot one variable", "Supply, valves, air leaks, cavitation, then discharge-side causes. Do not change everything at once."],
        ],
        [
            ["Operator's first job before math?", "Safe driving and placement for operations."],
            ["Practical cavitation meaning?", "The pump is not receiving enough water for the demand."],
            ["Why watch residual?", "Its change while flowing helps judge how supply responds to demand."],
            ["Why know your hose/nozzle package?", "Real targets depend on department equipment and SOP."],
            ["Relay roles?", "Source, intermediate, and attack pumpers with communications and pressure discipline."],
            ["Water hammer risk?", "Opening or closing valves too quickly can damage hose, fittings, and the system."],
        ],
        [
            q("Residual drops sharply as more lines open. You should:", ["Ignore it", "Communicate and reassess demand versus supply", "Increase every discharge immediately"], 1, "A large residual change is a water-supply clue."),
            q("Correct pump math but poor placement equals:", ["Complete performance", "Only one part of operator performance", "An automatic pass"], 1, "Driving, placement, systems, and communication all count."),
            q("If the pump will not prime from draft:", ["Keep priming indefinitely", "Check gaskets, caps, strainer, lift, and air leaks", "Open all discharges"], 1, "Air leaks and setup beat more primer time."),
            q("Troubleshooting works best when you:", ["Change several settings at once", "Change one variable and watch the result", "Ignore gauges"], 1, "Cause and effect disappear if you change everything."),
        ],
        ["Build a department-specific pump card.", "Run a hydrant residual drill.", "Practice failure recognition monthly."],
        [
            ["Pumper flashcards", "/driver-operator-pumper-flashcards.html"],
            ["Pump scenarios", "/fire-pump-training-scenarios.html"],
            ["Pump calculator", "/fire-pump-calculator.html"],
        ],
    ),
    "driver_operator_aerial": deck(
        "Driver / Operator — Aerial",
        "Placement, stabilization, load awareness, and aerial-device operation. Follow manufacturer procedure and department SOP—never this deck alone.",
        [
            ["Spotting", "Place for the objective, collapse zones, overhead hazards, later units, and outrigger/stabilizer room."],
            ["Stabilization", "Set the device per manufacturer and department procedure before raising. Confirm indicators."],
            ["Load and reach", "Know rated capacities, tip loads, and how extension/angle/personnel change the picture."],
            ["Communications", "Operator, officer, and team at the tip need closed-loop communication."],
            ["Driving", "Length, height, weight, and swing matter in traffic and on the fireground."],
        ],
        [
            ["Why walk the spot?", "To find overhead wires, grade, surface, and space for stabilizers."],
            ["Raise only after?", "Stabilization and manufacturer/department ready checks."],
            ["Tip load changes with?", "Angle, extension, waterway, and personnel/equipment at the tip."],
            ["Collapse zone reminder?", "Do not spot or operate in the area a wall or aerial could occupy if it fails."],
            ["Short-jacking?", "Only if manufacturer and department allow it for that surface and objective."],
            ["If a warning indicator activates?", "Stop, make it safe, and follow the apparatus procedure—do not override casually."],
        ],
        [
            q("Before raising the aerial you should:", ["Start moving immediately", "Stabilize and complete ready checks", "Ignore grade if you are in a hurry"], 1, "Stabilization comes first."),
            q("Overhead wires near the objective mean:", ["Raise faster", "Re-spot or choose another access method", "Use the stick as a probe"], 1, "Electrical and overhead hazards control placement."),
            q("Rated capacity is:", ["A suggestion", "A manufacturer limit that changes with configuration", "The same at every angle"], 1, "Know the chart for the setup you are in."),
            q("Good aerial communication is:", ["One long speech", "Short, closed-loop, and tied to the objective", "Silence until someone falls"], 1, "The operator needs a live picture."),
        ],
        ["Review your apparatus operator manual with an instructor.", "Practice spotting on the apron.", "Use Fireground Decision Sim for placement context."],
        [
            ["Driver/Operator practice", "/driver-operator-practice.html"],
            ["Fireground Decision Sim", "/fireground-decision-sim.html"],
            ["Focus drills", "/focus-drills.html?source=roadmap&level=driver_operator"],
        ],
    ),
    "fire_officer_1": deck(
        "Fire Officer I",
        "Company-level leadership: size-up, assignments, accountability, coaching, and risk. You own crew safety and communication, not only task completion.",
        [
            ["Size-up", "Building/occupancy, conditions, life hazard, access, resources, water, and initial actions—concise and useful."],
            ["Assignments", "Every assignment needs a task, location, objective, and communication path."],
            ["Accountability", "Know where crews are, what they are doing, and when conditions require a PAR."],
            ["Coaching", "Set the standard, observe, give specific feedback, and get another repetition."],
            ["Risk", "Strategy should change when risk/benefit, conditions, or resources no longer support it."],
        ],
        [
            ["What changes as officer?", "You own crew safety, coordination, development, and decision consequences."],
            ["Useful arrival report?", "Unit ID, building/occupancy, conditions, actions, needs, and command."],
            ["Strong assignment?", "Clear task, location, objective, and how to talk back."],
            ["When should strategy change?", "When conditions, risk, resources, or progress no longer support it."],
            ["Good coaching?", "Specific observation, the standard, and another corrected repetition."],
            ["USFA development pillars?", "Training, education, relevant experience, and continuing education."],
        ],
        [
            q("A crew finishes an assignment as conditions change. You should:", ["Wait silently", "Reassess, communicate, and align the next action with strategy", "Let them freelance"], 1, "Officers continuously reassess."),
            q("The first radio report should be:", ["A full building history", "Concise, actionable, and complete enough to set command up", "Delayed until the fire is out"], 1, "Length is not the goal—usefulness is."),
            q("Accountability fails when:", ["Crews have locations and objectives", "You cannot say where people are or what they are doing", "You ran a PAR"], 1, "Location and function must be known."),
            q("A promotional plan built only on certificates is incomplete because:", ["Certificates never matter", "Education, experience, and continuing education also matter", "Only seniority matters"], 1, "Development is more than a wall of certs."),
        ],
        ["Deliver three size-ups out loud this week.", "Lead a short company drill.", "Run Fireground Decision Sim from the officer seat."],
        [
            ["Officer study track", "/study-center.html?track=officer"],
            ["Company officer tools", "/company-officer-tools.html"],
            ["Fireground Decision Sim", "/fireground-decision-sim.html"],
        ],
    ),
    "fire_officer_2": deck(
        "Fire Officer II",
        "Beyond the first-arriving company: multi-company coordination, performance management, documentation quality, and improvement work.",
        [
            ["Multi-company operations", "Sectors/groups, span of control, and clear objectives for more than one crew."],
            ["Performance", "Expectations, evaluation, coaching, and documentation that would stand review."],
            ["Projects", "Process improvement, training plans, and evidence of leadership beyond a single incident."],
            ["Communication", "Up, down, and across—written and verbal. Ambiguity creates safety and personnel problems."],
            ["After-action", "Capture what worked, what failed, and the next repetition for the company and the department."],
        ],
        [
            ["Span of control reminder?", "Too many direct reports reduces supervision quality."],
            ["A useful after-action includes?", "Facts, one strength, one gap, and a next drill—not blame theater."],
            ["Documentation should be?", "Timely, factual, and complete enough for the next supervisor or investigator."],
            ["FO II vs FO I?", "FO II leans more into systems, multiple companies, and organizational communication."],
            ["Improvement work needs?", "A problem, a measure, a trial, and a follow-up—not only a meeting."],
            ["When transferring command?", "Give a complete picture: strategy, assignments, resources, and hazards."],
        ],
        [
            q("Two companies are working overlapping objectives. You should:", ["Let them sort it out", "Clarify sectors/objectives and communications", "Add a third company to the same task"], 1, "Overlap without coordination wastes people and creates risk."),
            q("Personnel documentation is strongest when it is:", ["Emotional and delayed", "Factual, timely, and tied to expectations", "Only verbal"], 1, "The record has to be usable later."),
            q("A process-improvement project should start with:", ["Buying new tools", "A clearly defined problem and a way to see change", "A slogan"], 1, "Define the gap first."),
            q("Command transfer should include:", ["Only the address", "Strategy, assignments, resources, and hazards", "Nothing if the fire looks smaller"], 1, "The incoming officer needs the whole picture."),
        ],
        ["Lead a multi-company drill.", "Write one after-action that names a next repetition.", "Build evidence in My Career."],
        [
            ["Leadership development", "/leadership-development.html"],
            ["Company officer tools", "/company-officer-tools.html"],
            ["Career plan builder", "/career-plan-builder.html"],
        ],
    ),
    "fire_officer_3": deck(
        "Fire Officer III",
        "Staff/chief-officer development: programs, planning, personnel systems, and multi-company operations. Confirm the exact FO III path with your certifying authority.",
        [
            ["Programs", "Training, prevention, EMS, or special operations programs need goals, resources, and evaluation."],
            ["Planning", "Budgets, staffing, and deployment are political and operational. Bring facts, options, and risks."],
            ["Personnel systems", "Hiring, development, discipline, and wellness are systems—not one-off conversations."],
            ["Multi-company / multi-agency", "ICS fluency, liaison, and clear objectives across organizations."],
            ["Evidence", "Keep projects, after-actions, and outcomes. FO III is often demonstrated, not only tested."],
        ],
        [
            ["FO III is often about?", "Organizational programs and planning, not only first-arriving tactics."],
            ["A useful proposal includes?", "Problem, options, cost/risk, and a recommended path."],
            ["Why track outcomes?", "So a program can be improved or defended with more than anecdotes."],
            ["Personnel work requires?", "Policy, documentation, fairness, and legal/HR partnership."],
            ["NFA value?", "Executive and officer courses that complement local certification—not replace it."],
            ["Stakeholder communication?", "Translate operational needs into language elected officials and the public can use."],
        ],
        [
            q("A training program with no evaluation is:", ["Complete", "Hard to improve or defend", "Automatically successful"], 1, "Programs need a way to see results."),
            q("When presenting a staffing option you should:", ["Give only the preferred answer", "Show options, risks, and a recommendation", "Avoid numbers"], 1, "Decision-makers need choices with consequences."),
            q("Discipline and development should:", ["Ignore written policy", "Follow policy, documentation, and consistency", "Happen only in the parking lot"], 1, "Systems protect people and the organization."),
            q("FO III preparation should include:", ["Only a test bank", "Projects, ICS practice, and documented outcomes", "Avoiding writing"], 1, "The role is broader than a written exam."),
        ],
        ["Map your state FO III requirements.", "Start one measurable program improvement.", "Look at current NFA officer courses."],
        [
            ["Leadership development", "/leadership-development.html"],
            ["Career plan builder", "/career-plan-builder.html"],
            ["NFA courses", "https://www.usfa.fema.gov/nfa/courses/"],
        ],
    ),
    "fire_officer_4": deck(
        "Fire Officer IV",
        "Executive-level fire-service leadership: policy, interagency relationships, and long-range organizational direction. Verify the local FO IV route.",
        [
            ["Policy", "Executive officers shape policy that crews will live with. Clarity and legality matter."],
            ["Relationships", "Elected officials, labor, neighboring agencies, and the public are part of the job."],
            ["Long-range view", "Facilities, apparatus, staffing, and risk reduction play out over years."],
            ["Ethics", "Conflicts of interest, transparency, and stewardship of public trust."],
            ["Still operational", "Executive rank does not erase the need to understand fireground risk and ICS."],
        ],
        [
            ["FO IV emphasis?", "Organizational direction and external relationships more than company tactics."],
            ["A policy should be?", "Clear, legal, trained, and enforceable—or it will fail in the field."],
            ["Why partners matter?", "Large incidents and community risk reduction are rarely single-agency problems."],
            ["Succession planning?", "Develop people before vacancies force emergency promotions."],
            ["NFA / executive education?", "Useful supplements; they do not replace local certification rules."],
            ["Public communication?", "Accurate, timely, and appropriate—without compromising investigations or personnel matters."],
        ],
        [
            q("An unenforceable policy is:", ["Fine if it looks good", "A field and legal problem", "Better than training"], 1, "Policy has to work in practice."),
            q("Executive fire officers still need ICS fluency because:", ["ICS is only for recruits", "Large incidents and multi-agency work require it", "Radio reports are obsolete"], 1, "Rank does not remove operational literacy."),
            q("Community risk reduction at this level is:", ["Only inspections", "A coordinated program with partners and measures", "A slogan for the annual report"], 1, "CRR is work, not branding."),
            q("A succession plan should:", ["Wait for retirement day", "Develop people against the competencies of the next job", "Promote the loudest person"], 1, "Build capacity early."),
        ],
        ["Confirm FO IV with your certifying agency.", "Build a leadership portfolio in My Career.", "Review NFA executive offerings."],
        [
            ["Career stages", "/career-stages.html"],
            ["My Career", "/my-fire-career.html"],
            ["NFA courses", "https://www.usfa.fema.gov/nfa/courses/"],
        ],
    ),
    "fire_instructor_1": deck(
        "Fire Instructor I",
        "Teach for job transfer: observable objectives, demonstration, coached repetitions, evaluation, and training-ground safety.",
        [
            ["Objectives", "Describe observable learner behavior, conditions, and a standard—not 'understand fire behavior.'"],
            ["Skill teaching", "Explain, demonstrate, guide practice, allow repetitions, give specific feedback, and re-test."],
            ["Scenarios", "Let learners discover information by acting. Debrief reasoning, not only the final answer."],
            ["Evaluation", "Separate safety-critical failures from coaching points. Use a simple rubric."],
            ["Safety", "Brief hazards, PPE, emergency signals, medical plan, and stop criteria before the evolution."],
        ],
        [
            ["Measurable objective?", "An observable learner action rather than a vague word like understand."],
            ["Best skill feedback?", "Specific observation, the standard/impact, and another corrected repetition."],
            ["Why allow wrong decisions in training?", "Safe failure plus debrief exposes reasoning gaps."],
            ["If an unsafe condition appears?", "Pause or stop. Training objectives never override immediate safety."],
            ["Progressive disclosure?", "Information appears after the learner takes an appropriate action to discover it."],
            ["Documentation?", "Attendance, objectives, performance, remediation, and lessons learned."],
        ],
        [
            q("A scenario that reveals the hidden fire location automatically:", ["Is more realistic", "Removes a discovery/decision opportunity", "Is always required"], 1, "Decision training is stronger when learners gather information."),
            q("Unsafe training condition appears. You should:", ["Continue for the schedule", "Pause/stop and correct it", "Document it after class only"], 1, "Stop criteria exist for a reason."),
            q("A useful rubric has:", ["Only a pass/fail vibe", "A few observable criteria and what constitutes stop vs coach", "Secret standards"], 1, "Learners and evaluators need the same picture."),
            q("Instructor I teaching is successful when learners can:", ["Sit through a lecture", "Perform the skill or decision under the stated conditions", "Repeat slogans"], 1, "Job transfer is the point."),
        ],
        ["Convert one lecture into a skill or decision exercise.", "Write one measurable objective today.", "Use the drill builder for a company session."],
        [
            ["Instructor I study guide", "/fire-instructor-1-study-guide.html"],
            ["Instructor track", "/study-center.html?track=instructor"],
            ["Drill builder", "/firefighter-drill-builder.html"],
        ],
    ),
    "fire_instructor_2": deck(
        "Fire Instructor II",
        "Program-level instruction: lesson design across a course, instructor coaching, evaluation systems, and training records that would survive review.",
        [
            ["Course design", "Sequence lessons so skills and decisions build. Do not stack unrelated lectures."],
            ["Coach instructors", "Instructor II often improves other instructors, not only recruits."],
            ["Evaluation systems", "Consistent criteria, remediation paths, and integrity of testing."],
            ["Records", "Objectives, attendance, performance, injuries, and after-action notes."],
            ["Live-fire / high-risk training", "Follow current live-fire and high-risk training standards used by your agency. This deck is not a live-fire qualification."],
        ],
        [
            ["Instructor II vs I?", "II leans into programs, other instructors, and evaluation systems."],
            ["A course map should show?", "How each lesson supports a job performance outcome."],
            ["Remediation is?", "A planned path back to the standard—not humiliation."],
            ["Test integrity?", "Same conditions, no teaching the test, and documented accommodations per policy."],
            ["High-risk training needs?", "Qualified instructors, safety officers, and current standards—not enthusiasm alone."],
            ["After a failed evaluation?", "Document, remediate, and re-evaluate against the same criteria."],
        ],
        [
            q("A training program without records is:", ["Agile", "Hard to defend or improve", "Preferred"], 1, "Records are part of the job."),
            q("Coaching another instructor should focus on:", ["Personality", "Observable teaching behaviors and learner outcomes", "Volume of slides"], 1, "Watch what learners can do."),
            q("Live-fire training qualification comes from:", ["This flashcard deck", "Your agency, AHJ, and current applicable standards", "YouTube"], 1, "Do not treat this as live-fire cert."),
            q("A good course sequence:", ["Jumps randomly between topics", "Builds skills and decisions in a job-relevant order", "Saves all practice for the last hour"], 1, "Practice belongs throughout."),
        ],
        ["Map one course from objective to evaluation.", "Sit in on another instructor and give specific feedback.", "Review your training records SOP."],
        [
            ["Instructor track", "/study-center.html?track=instructor"],
            ["Instructor I hub", "/fire-instructor-1.html"],
            ["Drill builder", "/firefighter-drill-builder.html"],
        ],
    ),
    "fire_inspector_1": deck(
        "Fire Inspector I",
        "Organized occupancy inspections using the code family your AHJ actually adopted. Cite current editions, not memory.",
        [
            ["Inspection sequence", "Identify occupancy, construction, hazards, protection systems, and egress in a repeatable order."],
            ["Documentation", "Write violations so a reasonable person could find the problem and the required correction."],
            ["Codes", "Adopted edition and local amendments control. Confirm before citing."],
            ["Safety", "Inspector PPE, dogs, industrial processes, and vacant buildings are real hazards."],
            ["Customer communication", "Explain the life-safety why, not only the code number."],
        ],
        [
            ["First inspection habit?", "A consistent walk-through order so you miss less."],
            ["A usable violation note includes?", "Location, condition, code reference, and required action."],
            ["Why confirm the adopted edition?", "Citing the wrong year or amendment undermines the inspection."],
            ["Common miss?", "Egress, extinguishers, blocked protection systems, and storage that changes occupancy hazard."],
            ["Occupancy matters because?", "Requirements change with use and occupant load."],
            ["Inspector authority?", "Comes from the AHJ, not from a FireOpsSim checklist."],
        ],
        [
            q("You are unsure which code edition is adopted. You should:", ["Cite the newest book you own", "Verify with the AHJ before writing the notice", "Skip the occupancy"], 1, "Wrong edition is a credibility and legal problem."),
            q("A vague violation like 'fix the hallway' is weak because:", ["It is too kind", "It does not tell the owner what, where, or why", "Hallways are never a problem"], 1, "The owner has to be able to comply."),
            q("Blocked sprinkler heads are a problem because:", ["They look messy", "They can prevent the system from controlling fire", "They only matter in warehouses"], 1, "Protection systems have to be able to work."),
            q("Inspector I walk-throughs should start with:", ["Random rooms", "A planned sequence covering occupancy, egress, and protection", "The roof first always"], 1, "A sequence prevents missed life-safety items."),
        ],
        ["Do a mock walk-through with the inspection checklist.", "Practice writing one complete violation note.", "Confirm your AHJ's adopted codes."],
        [
            ["Inspector tools", "/fire-inspector-tools.html"],
            ["Inspection checklist", "/fire-inspection-checklist.html"],
            ["Code violation notes", "/fire-code-violation-notes.html"],
        ],
    ),
    "fire_inspector_2": deck(
        "Fire Inspector II",
        "Complex occupancies, plans coordination, and higher-quality documentation. Still AHJ- and edition-specific.",
        [
            ["Complex occupancies", "Assembly, high-rise, industrial, and mixed use need more than a simple punch list."],
            ["Systems", "Understand how detection, suppression, smoke control, and egress work together."],
            ["Plans and permits", "Field conditions must match approved plans or be formally addressed."],
            ["Coordination", "Building, fire, and life-safety reviewers often share an occupancy."],
            ["Quality", "Photos, measurements, and clear notices reduce arguments later."],
        ],
        [
            ["Inspector II vs I?", "II leans into complex occupancies and coordination, not only routine walk-throughs."],
            ["Why photos?", "They locate the condition and support the written notice."],
            ["Occupant load matters because?", "Egress and use requirements depend on it."],
            ["Field vs plans?", "Built conditions that differ from approved plans need a process, not a shrug."],
            ["Mixed occupancy?", "Apply the requirements for each use and the most restrictive where they interact—per adopted code."],
            ["Professional tone?", "Firm on life safety, clear on corrections, no personal attacks."],
        ],
        [
            q("A high occupant-load assembly space should trigger extra attention to:", ["Paint color", "Egress capacity, arrangement, and occupant load", "Only kitchen hoods"], 1, "People movement is the life-safety problem."),
            q("If the field does not match approved plans, you should:", ["Ignore it if the building is pretty", "Document and follow AHJ process", "Approve it verbally"], 1, "Changes need a process."),
            q("Smoke control and sprinklers:", ["Never interact", "May both be part of the designed protection package", "Replace egress"], 1, "Systems work as a package."),
            q("Better notices include:", ["Sarcasm", "Location, evidence, code basis, and correction", "Only a code number"], 1, "The owner has to be able to act."),
        ],
        ["Practice occupant-load math for a real room.", "Walk a complex occupancy with a mentor.", "Use the occupancy-load calculator as a check, then verify the code method."],
        [
            ["Occupancy load calculator", "/occupancy-load-calculator.html"],
            ["Inspector tools", "/fire-inspector-tools.html"],
            ["Pre-incident plan builder", "/pre-incident-plan-builder.html"],
        ],
    ),
    "fire_investigator": deck(
        "Fire Investigator",
        "Scene safety, legal authority, systematic exam, and documentation before conclusions. Follow agency and prosecutor protocol.",
        [
            ["Authority first", "Do not exceed legal authority or your assignment. Origin-and-cause work is not a hobby."],
            ["Safety", "Structural compromise, utilities, crime, and contaminants can all be present."],
            ["Systematic exam", "Document from the outside in. Observations before opinions."],
            ["Evidence", "Preserve, photograph, and maintain chain of custody per agency protocol."],
            ["Interviews", "Non-leading questions, accurate notes, and legal limits of your role."],
        ],
        [
            ["Before concluding cause?", "Scene safety, authority, and a systematic exam."],
            ["Photo set should include?", "Overall, mid-range, and close-up with context/scale."],
            ["Chain of custody?", "Who had the item, when, and why—per agency rules."],
            ["Danger of early conclusions?", "You stop seeing contradictory evidence."],
            ["Witness interviews should be?", "Structured and non-leading, within your legal role."],
            ["IAAI / state programs?", "Professional development; they do not automatically grant legal authority."],
        ],
        [
            q("The first investigator priority on scene is usually:", ["Naming the cause", "Safety and legal authority", "Posting on social media"], 1, "Safety and authority before conclusions."),
            q("A systematic exam means:", ["Starting at the most burned room and guessing", "Working a planned order and recording observations first", "Only interviewing the owner"], 1, "Process before opinion."),
            q("If you lack authority to seize evidence, you should:", ["Take it anyway", "Follow agency/prosecutor direction", "Leave everything undocumented"], 1, "Authority limits are real."),
            q("Close-up photos without overall shots are weak because:", ["They look artistic", "They lose location context", "Investigators never use overalls"], 1, "Context locates the detail."),
        ],
        ["Confirm your agency investigator pathway.", "Practice a photo sequence on a training prop.", "Do not invent chain-of-custody rules."],
        [
            ["Specialty careers", "/specialty-careers.html"],
            ["Inspector tools", "/fire-inspector-tools.html"],
            ["IAAI", "https://www.firearson.com/"],
        ],
    ),
    "emt": deck(
        "EMT",
        "BLS assessment, communication, documentation, and safety. Certification and state licensure are separate—confirm both.",
        [
            ["Scene and BSI", "Scene safety and standard precautions before the patient exam."],
            ["Primary assessment", "Find immediate life threats. Airway, breathing, circulation, disability, exposure as trained."],
            ["Trends", "One vital is a snapshot. Change over time may show deterioration or response."],
            ["Handoff", "Problem, relevant history, key findings, treatments, response, and concerns."],
            ["Scope", "NREMT does not by itself authorize practice everywhere. State and local authorization control."],
        ],
        [
            ["Primary assessment purpose?", "Find and address immediate life threats while forming priority."],
            ["Why trend vitals?", "Change over time may reveal deterioration, improvement, or treatment response."],
            ["Strong handoff?", "Problem, findings/trends, treatments, response, and concerns."],
            ["Does NREMT alone authorize practice everywhere?", "No. State licensure/certification and local authorization control."],
            ["What belongs in a skill log?", "De-identified skill, repetitions, feedback—not PHI."],
            ["Fixation error?", "Staring at an obvious injury and missing airway or scene threats."],
        ],
        [
            q("A patient looks worse although one vital is normal. You should:", ["Ignore appearance", "Use the whole assessment and trend findings", "Document only the normal value"], 1, "Use the complete patient picture."),
            q("Best way to improve a handoff?", ["Talk longer", "Use a concise structure and get feedback", "Skip trends"], 1, "Relevance and structure beat length."),
            q("Before touching the patient:", ["Start IVs if allowed later", "Address scene safety and BSI", "Take a full SAMPLE history first"], 1, "Safety first."),
            q("If a skill is outside your scope:", ["Do it anyway if it seems needed", "Stay in scope and protocol; request ALS/resources", "Guess from social media"], 1, "Scope is a safety and legal boundary."),
        ],
        ["Use EMSCodeSim for patient-driven scenarios.", "Log de-identified skills.", "Confirm state testing and licensure steps."],
        [
            ["EMT study track", "/study-center.html?track=emt"],
            ["EMSCodeSim", "https://emscodesim.com/"],
            ["EMS career center", "/ems-career.html"],
        ],
    ),
    "aemt": deck(
        "Advanced EMT",
        "AEMT scope is state-specific. Assessment still comes first. Confirm current scope, medical direction, and protocols.",
        [
            ["Scope first", "AEMT interventions vary widely by state. Do not copy another system's skill list."],
            ["Assessment first", "Advanced tools do not replace a primary assessment and trending."],
            ["Medication safety", "Indication, contraindications, concentration, route, effect, and adverse response."],
            ["Airway support", "Within authorized skills: positioning, ventilation, and adjuncts as trained and allowed."],
            ["ALS intercept", "Know when to request paramedic/critical care resources early."],
        ],
        [
            ["Why check state scope?", "AEMT allowed skills are not nationally identical."],
            ["After any intervention?", "Reassess effect and adverse response."],
            ["Dangerous habit?", "Performing a skill because you saw it once, not because protocol allows it."],
            ["Handoff to paramedic?", "Problem, what you did, response, remaining threats, and trends."],
            ["Medical direction?", "Follow current protocols and on-line/off-line direction as required."],
            ["Documentation?", "Objective findings, times, interventions, and response—no PHI in training logs."],
        ],
        [
            q("Your protocol does not include a skill you practiced in another state. You should:", ["Do it anyway", "Follow current local scope and medical direction", "Teach it to the crew"], 1, "Local authorization controls."),
            q("A medication is given. Next:", ["Assume success", "Reassess effect and adverse response", "Stop monitoring vitals"], 1, "Treatment lives in a reassessment loop."),
            q("AEMT study should emphasize:", ["Only advanced skills", "Assessment, scope, and the skills you are actually authorized to perform", "Ignoring BLS"], 1, "BLS and assessment remain central."),
            q("When a patient needs care beyond AEMT scope:", ["Delay transport to try extra skills", "Request appropriate resources and stay in protocol", "Invent a new protocol"], 1, "Escalate early."),
        ],
        ["Print your current scope of practice.", "Practice assessment and authorized skills.", "Use EMSCodeSim, then confirm protocols."],
        [
            ["EMS career center", "/ems-career.html"],
            ["Study Center", "/study-center.html?track=emt"],
            ["EMSCodeSim", "https://emscodesim.com/"],
        ],
    ),
    "paramedic": deck(
        "Paramedic",
        "Disciplined ALS judgment: assessment first, medication/airway safety, ECG in context, leadership, and reassessment.",
        [
            ["Assessment first", "Do not let the monitor replace a focused clinical assessment."],
            ["Airway", "Positioning, ventilation, BVM, adjuncts, capnography concepts, and reassessment as trained."],
            ["Medication safety", "Indication, contraindications, dose/concentration, route, effect, and adverse response."],
            ["ECG context", "Integrate rhythm/12-lead findings with symptoms, exam, vitals, and serial change."],
            ["Leadership", "Assign roles, communicate priorities, invite concerns, and revise the plan."],
        ],
        [
            ["What comes before an ALS procedure?", "A clear problem, assessment, indication, risk/benefit, and complication plan."],
            ["Why is BLS still central?", "Assessment, ventilation, hemorrhage control, movement, and communication remain foundational."],
            ["Medication loop?", "Indication → safe administration → effect/adverse response → updated plan."],
            ["Dangerous ECG habit?", "Treating a machine label without the patient context."],
            ["Good ALS leadership?", "Clear priorities, role assignment, closed-loop communication, willingness to revise."],
            ["Medical direction?", "Protocols and on-line direction remain controlling."],
        ],
        [
            q("Monitor interpretation conflicts with the patient. You should:", ["Treat the label only", "Reassess tracing and patient in context", "Ignore symptoms"], 1, "ALS decisions integrate the whole picture."),
            q("After medication administration:", ["Move on permanently", "Reassess effect/adverse response", "Assume it worked"], 1, "Stay in the loop."),
            q("A chaotic scene needs:", ["Everyone talking at once", "Assigned roles and a stated priority", "No leadership so people feel free"], 1, "Leadership reduces harm."),
            q("Capnography, when available and indicated, helps you:", ["Skip ventilation quality", "Assess ventilation/perfusion clues as trained", "Replace all other monitoring"], 1, "It is a tool, not a complete exam."),
        ],
        ["Use EMSCodeSim for advanced scenarios.", "Review difficult calls with FTO/medical direction.", "Keep BLS perfect while adding ALS."],
        [
            ["Paramedic study track", "/study-center.html?track=paramedic"],
            ["EMSCodeSim", "https://emscodesim.com/"],
            ["First 100 EMS shifts", "/first-100-ems-shifts.html"],
        ],
    ),
    "bls": deck(
        "BLS / CPR",
        "Issuer-dependent credential (AHA, Red Cross, or another provider your agency accepts). Use the current provider manual—not a generic algorithm dump.",
        [
            ["Issuer matters", "Your department names the accepted card. Study that provider's current materials."],
            ["High-quality CPR", "Rate, depth, recoil, and minimizing interruptions as taught in your course."],
            ["AED", "Early defibrillation when indicated. Follow the prompts and your training."],
            ["Team CPR", "Switch compressors, communicate, and keep the airway/ventilation plan coordinated."],
            ["After the card", "Skills decay. Refresh before the card expires if your agency requires it sooner."],
        ],
        [
            ["BLS is issued by?", "A provider your agency accepts—not FireOpsSim."],
            ["Minimize what during CPR?", "Interruptions in compressions, as trained."],
            ["AED first action after it arrives?", "Use it as trained; do not delay for extra history if indicated."],
            ["Why recertify?", "Algorithms and skills change; agencies set accepted providers and intervals."],
            ["Scene safety still applies?", "Yes. Provider courses still start with safety."],
            ["Infant/child differences?", "Follow the current provider course—do not mix algorithms from memory."],
        ],
        [
            q("Your department accepts Red Cross BLS but you studied an old AHA flowchart. You should:", ["Use the old flowchart at work", "Take the accepted current course", "Mix both"], 1, "Issuer and edition matter."),
            q("High-quality compressions emphasize:", ["Long pauses for pulse checks", "Rate, depth, recoil, and limited interruptions as trained", "Hands off the chest as much as possible"], 1, "Follow the current course."),
            q("If you are unsure of the current algorithm:", ["Invent one", "Use the current provider materials and medical direction", "Ask social media during the arrest"], 1, "Current materials win."),
            q("BLS practice on FireOpsSim is:", ["An official provider card", "Preparation only; the card comes from an accepted provider", "A replacement for manikin time"], 1, "You still need the issuer course."),
        ],
        ["Confirm the accepted provider.", "Book a current BLS/CPR course.", "Practice assessment on EMSCodeSim without treating it as a BLS card."],
        [
            ["EMS life-support companion", "/ems-life-support.html?cert=bls"],
            ["AHA CPR", "https://cpr.heart.org/"],
            ["Red Cross classes", "https://www.redcross.org/take-a-class"],
        ],
    ),
    "acls": deck(
        "ACLS",
        "Advanced Cardiovascular Life Support is issuer-dependent. Study current provider materials, local protocols, and medical direction.",
        [
            ["Not a protocol replacement", "ACLS algorithms support, they do not override medical direction."],
            ["High-quality BLS first", "ALS does not rescue poor compressions and ventilation."],
            ["Rhythm in context", "Treat the patient and the verified rhythm, not only a monitor label."],
            ["Team leader", "Assign roles, closed-loop communication, and timed interventions as trained."],
            ["Post-arrest", "Follow current provider and local post-ROSC expectations."],
        ],
        [
            ["ACLS card comes from?", "An accepted provider course—not this website."],
            ["If BLS is poor, ACLS is?", "Much less effective."],
            ["Closed-loop communication?", "Order, repeat-back, and confirmation."],
            ["Drug decisions?", "Indication, dose, and timing per current course and protocol."],
            ["Why local protocols?", "Agencies may differ from a classroom algorithm."],
            ["Mega-code practice?", "Useful; still not a substitute for an official course."],
        ],
        [
            q("Monitor says a rhythm that does not match the patient. You should:", ["Push the first drug on the poster", "Reassess patient and tracing", "Stop BLS"], 1, "Context before the algorithm."),
            q("The team leader should:", ["Do every skill personally", "Assign roles and keep the algorithm/time moving", "Stay silent"], 1, "Leadership is coordination."),
            q("ACLS study here is for:", ["Printing a provider card", "Recall and team habits before/after the official course", "Replacing medical direction"], 1, "Issuer course remains required."),
            q("High-quality CPR during ACLS:", ["Is optional once ALS starts", "Continues as the foundation", "Stops for every rhythm check of unlimited length"], 1, "BLS remains the base."),
        ],
        ["Take/renew the accepted ACLS course.", "Practice team roles.", "Pair with paramedic assessment practice."],
        [
            ["Life-support companion", "/ems-life-support.html?cert=acls"],
            ["Paramedic study track", "/study-center.html?track=paramedic"],
            ["EMSCodeSim", "https://emscodesim.com/"],
        ],
    ),
    "pals": deck(
        "PALS",
        "Pediatric Advanced Life Support is issuer-dependent. Pair current provider materials with pediatric assessment and local pediatric protocols.",
        [
            ["Kids are not small adults", "Assessment, equipment, and dosing follow pediatric training—not adult shortcuts."],
            ["Issuer course", "Your agency names the accepted PALS/pediatric ALS provider."],
            ["Respiratory first", "Pediatric emergencies are often respiratory. Support oxygenation/ventilation as trained."],
            ["Dosing safety", "Weight-based dosing and concentration checks. Do not guess."],
            ["Family and team", "Assign roles, communicate, and follow local family-presence policy."],
        ],
        [
            ["PALS card comes from?", "An accepted provider—not FireOpsSim."],
            ["Common pediatric pathway?", "Respiratory compromise leading to arrest if not reversed."],
            ["Why length-based tapes/apps?", "To support dosing and equipment size as trained and authorized."],
            ["After any intervention?", "Reassess work of breathing, perfusion, and mental status."],
            ["Local protocols?", "Still controlling for your EMS/fire agency."],
            ["Infant CPR differences?", "Follow the current provider course; do not mix from memory."],
        ],
        [
            q("A pediatric patient with increased work of breathing needs:", ["Immediate adult ACLS drugs", "Assessment and respiratory support as trained", "A wait-and-see approach with no monitoring"], 1, "Respiratory support is often the priority."),
            q("Medication dosing should be:", ["Copied from the last adult call", "Weight-based per current course and protocol", "Guessed to save time"], 1, "Pediatric dosing errors are high-risk."),
            q("This study deck is:", ["A PALS provider card", "Preparation around an official issuer course", "A replacement for pediatric clinical time"], 1, "Take the accepted course."),
            q("Team PALS works best with:", ["One person doing everything", "Assigned roles and closed-loop communication", "No leader"], 1, "Pediatrics is a team problem."),
        ],
        ["Confirm accepted PALS provider.", "Review pediatric equipment on your apparatus.", "Use EMSCodeSim pediatric cases if available in your workflow."],
        [
            ["Life-support companion", "/ems-life-support.html?cert=pals"],
            ["EMS career center", "/ems-career.html"],
            ["AHA CPR", "https://cpr.heart.org/"],
        ],
    ),
    "ics_100": deck(
        "ICS-100",
        "Introduction to the Incident Command System. Complete the current FEMA Independent Study course, then apply the language on the fireground.",
        [
            ["Purpose", "ICS is a standardized way to organize people, communications, and objectives on an incident."],
            ["Command", "One Incident Commander (or Unified Command) sets objectives. Span of control matters."],
            ["Sections", "Operations, Planning, Logistics, and Finance/Admin exist when the incident needs them—not as decoration."],
            ["Common language", "Clear text and plain ICS titles beat radio slang that outsiders cannot use."],
            ["Take the course", "IS-100 is free from FEMA EMI. This deck is not the certificate."],
        ],
        [
            ["ICS is for?", "Incidents of any size that need organized command and communications."],
            ["Span of control?", "How many resources one supervisor can effectively manage."],
            ["Unified Command?", "Agencies with jurisdiction sharing command when appropriate."],
            ["General Staff?", "Operations, Planning, Logistics, Finance/Admin as needed."],
            ["Where is the certificate?", "FEMA Independent Study / your state EMI process—not FireOpsSim."],
            ["Why it matters on the fireground?", "Size-up, assignments, and radio reports use ICS language."],
        ],
        [
            q("ICS-100 certification comes from:", ["This quiz", "The current FEMA IS-100 course", "A fire department patch"], 1, "Complete the official course."),
            q("Span of control is about:", ["How far a hose can reach", "How many resources a supervisor can manage effectively", "The height of a ladder"], 1, "Supervision quality."),
            q("ICS organization should:", ["Always stand up all sections immediately", "Expand and contract to the incident's needs", "Ignore operations"], 1, "Modular organization."),
            q("After passing IS-100, apply it by:", ["Forgetting the terms", "Using ICS language in size-up, assignments, and drills", "Only citing it on a resume"], 1, "Use it at work."),
        ],
        ["Complete current IS-100.c (or successor) on FEMA EMI.", "Practice an arrival report using ICS terms.", "Run a decision sim and name the IC and objectives."],
        [
            ["ICS/NIMS hub", "/ics-nims-training.html?cert=ics_100"],
            ["FEMA IS-100", "https://training.fema.gov/is/courseoverview.aspx?code=IS-100.c"],
            ["Fireground Decision Sim", "/fireground-decision-sim.html"],
        ],
    ),
    "ics_200": deck(
        "ICS-200",
        "ICS for single resources and initial action incidents. Pair FEMA IS-200 with company-officer decision practice.",
        [
            ["Initial action", "First-arriving officers apply ICS immediately: command, objectives, and assignments."],
            ["Single resources", "Engine, truck, ambulance, and chief officers as resources with leaders and status."],
            ["Briefings", "Leaders need objectives, assignments, communications, and safety."],
            ["Transfer of command", "Face-to-face or radio with a complete picture when practical."],
            ["Take IS-200", "This deck supports recall; FEMA issues the course completion."],
        ],
        [
            ["ICS-200 builds on?", "ICS-100 concepts applied to initial action and single resources."],
            ["A briefing should include?", "Objectives, assignments, communications, and safety."],
            ["Resource status?", "Assigned, available, out of service—keep it honest."],
            ["Why transfer command formally?", "So the incoming IC has strategy, hazards, and assignments."],
            ["Company officer connection?", "Size-up and crew assignments are ICS in miniature."],
            ["Certificate source?", "Current FEMA IS-200 course."],
        ],
        [
            q("ICS-200 is most useful to:", ["Only federal coordinating officers", "Company officers running initial action incidents", "People who never go on runs"], 1, "Initial action is the daily use case."),
            q("A resource without a leader or status is:", ["Fine", "Hard to manage in ICS", "Automatically in Operations"], 1, "Resources need leaders and status."),
            q("When command transfers, include:", ["Only the address", "Objectives, hazards, assignments, and resources", "Nothing if it is a still alarm"], 1, "Give a complete picture."),
            q("Practice ICS-200 by:", ["Only reading slides", "Giving assignments and a short IAP-style briefing on drills", "Avoiding the radio"], 1, "Use it on the training ground."),
        ],
        ["Complete current IS-200.", "Give one incident briefing this week on a drill.", "Use officer focus drills."],
        [
            ["ICS/NIMS hub", "/ics-nims-training.html?cert=ics_200"],
            ["FEMA IS-200", "https://training.fema.gov/is/courseoverview.aspx?code=IS-200.c"],
            ["Company officer tools", "/company-officer-tools.html"],
        ],
    ),
    "ics_300": deck(
        "ICS-300",
        "Intermediate ICS for expanding incidents. Often delivered in a classroom by the state or EMI—not only Independent Study. Verify the current delivery method.",
        [
            ["Expanding incidents", "When the organization grows, planning, logistics, and operations support must grow with it."],
            ["IAP", "Objectives, strategy, tactics, assignments, and communications for an operational period."],
            ["Meetings", "Planning cycle / operational period meetings exist to produce a useful plan, not to fill a calendar."],
            ["Demobilization", "Resources leave in a controlled way. Safety and accountability continue."],
            ["Find the course", "ICS-300 is commonly state-delivered. Check EMI and your state training office."],
        ],
        [
            ["ICS-300 vs 200?", "300 addresses expanding incidents and the planning cycle more deeply."],
            ["Operational period?", "The time window a plan is built to cover."],
            ["Why write objectives?", "So every section and crew is aimed at the same outcomes."],
            ["Logistics matters when?", "The incident lasts long enough that people, food, fuel, and relief become the problem."],
            ["Where to take it?", "Often in-person via state/EMI—confirm current offerings."],
            ["Still need 100/200?", "Yes. 300 assumes the basics."],
        ],
        [
            q("ICS-300 is typically:", ["A 10-minute online meme", "An intermediate course often delivered in a classroom", "The same as IS-100"], 1, "Check current delivery."),
            q("An IAP is useful when it:", ["Lists every rumor", "States objectives, assignments, and communications for a period", "Is never shared"], 1, "Plans have to be usable."),
            q("Expanding an incident organization should:", ["Add sections for show", "Match complexity and span of control", "Eliminate Operations"], 1, "Modular growth."),
            q("Before attending ICS-300, complete:", ["Nothing", "The current ICS-100 and ICS-200 prerequisites your host requires", "FO IV"], 1, "Hosts publish prerequisites."),
        ],
        ["Check FEMA EMI and your state for ICS-300 offerings.", "Practice writing three incident objectives.", "Review leadership/planning resources."],
        [
            ["ICS/NIMS hub", "/ics-nims-training.html?cert=ics_300"],
            ["FEMA EMI", "https://training.fema.gov/"],
            ["NFA courses", "https://www.usfa.fema.gov/nfa/courses/"],
        ],
    ),
    "ics_400": deck(
        "ICS-400",
        "Advanced ICS for complex incidents and MACS concepts. Usually classroom-delivered. Confirm prerequisites and current host.",
        [
            ["Complex incidents", "Multiple jurisdictions, long duration, and political/media pressure change the command environment."],
            ["Area Command / MACS", "Know the concepts at a high level; your host course is authoritative."],
            ["EOC relationship", "Incident command and emergency operations centers support each other with different jobs."],
            ["Prerequisites", "ICS-400 hosts typically require 100/200/300. Bring completion certificates."],
            ["Not a FireOpsSim certificate", "We help you prepare and find the course."],
        ],
        [
            ["ICS-400 focuses on?", "Complex incident management and multi-agency coordination concepts."],
            ["Why prerequisites?", "Advanced ICS assumes you can already run initial and expanding ICS."],
            ["MACS in one line?", "Coordination above a single incident when the system is overloaded or many incidents exist."],
            ["EOC vs IC?", "EOC supports; IC/UC runs the incident unless local doctrine says otherwise."],
            ["Where to take it?", "State/EMI classroom offerings—search current catalogs."],
            ["Apply it how?", "Large-event planning, department SOP, and multi-agency drills."],
        ],
        [
            q("ICS-400 is best treated as:", ["A substitute for ICS-100", "Advanced classroom training for complex incidents", "A pump operator card"], 1, "Know what the course is for."),
            q("If you have not completed ICS-300, you should:", ["Skip to 400", "Complete required prerequisites first", "Invent a certificate"], 1, "Hosts check prereqs."),
            q("Multi-agency coordination is needed when:", ["One engine handles a dumpster", "Incidents or jurisdictions exceed a single IC's ability to coordinate", "Nobody has a radio"], 1, "Scale drives structure."),
            q("FireOpsSim ICS-400 content is:", ["The official EMI final exam", "Orientation and course-finding support", "A live incident IAP"], 1, "Take the official course."),
        ],
        ["Verify ICS-400 dates with your state training office.", "Bring ICS-100/200/300 completions.", "Practice multi-company command on drills."],
        [
            ["ICS/NIMS hub", "/ics-nims-training.html?cert=ics_400"],
            ["FEMA EMI", "https://training.fema.gov/"],
            ["NFA", "https://www.usfa.fema.gov/nfa/courses/"],
        ],
    ),
    "is_700": deck(
        "IS-700 / NIMS",
        "National Incident Management System overview. Complete current FEMA IS-700. This is not the same course as ICS-100.",
        [
            ["NIMS vs ICS", "NIMS is the national framework. ICS is the on-scene command system inside that framework."],
            ["Why NIMS?", "So agencies can work together with shared concepts for command, resource management, and communications."],
            ["Resource management", "Typing, requesting, and tracking resources so mutual aid is not a guessing game."],
            ["Communications", "Common, interoperable, and plain language as policy requires."],
            ["Take IS-700", "Free Independent Study. Keep a copy of your certificate."],
        ],
        [
            ["IS-700 is about?", "NIMS—the national framework—not only company-level ICS tactics."],
            ["ICS sits where?", "Inside NIMS as the on-scene management system."],
            ["Resource typing helps?", "Asking for the capability you actually need."],
            ["Plain language?", "Reduces confusion between agencies and disciplines."],
            ["Certificate from?", "Current FEMA IS-700 course."],
            ["Related course?", "IS-800 covers the National Response Framework—a different course."],
        ],
        [
            q("NIMS and ICS are:", ["The same course", "Related but not identical; NIMS is broader", "Only for FEMA employees"], 1, "Do not skip 700 because you took 100."),
            q("Resource typing is useful because:", ["It sounds official", "It helps request the right capability", "It replaces training"], 1, "Ask for what you need."),
            q("IS-700 completion comes from:", ["FireOpsSim", "FEMA Independent Study", "A local engine company"], 1, "Official course."),
            q("After IS-700, a firefighter should:", ["Never use ICS terms", "Understand how local ICS fits the national system", "Ignore mutual aid"], 1, "Connect national concepts to local SOP."),
        ],
        ["Complete current IS-700.b (or successor).", "Store the certificate in your Career Road credentials.", "Take ICS-100 if you have not."],
        [
            ["ICS/NIMS hub", "/ics-nims-training.html?cert=is_700"],
            ["FEMA IS-700", "https://training.fema.gov/is/courseoverview.aspx?code=IS-700.b"],
            ["FEMA course list", "https://training.fema.gov/is/crslist.aspx"],
        ],
    ),
    "is_800": deck(
        "IS-800 / National Response Framework",
        "How the nation responds across levels of government. Complete current FEMA IS-800. Different from ICS and NIMS overview courses.",
        [
            ["NRF purpose", "Describe how the U.S. responds to incidents across local, state, tribal, territorial, and federal partners."],
            ["Not your company SOP", "NRF is national doctrine. Local response still follows local plans."],
            ["ESFs", "Emergency Support Functions organize federal/state capabilities by function—know they exist."],
            ["Take IS-800", "Independent Study certificate from FEMA EMI."],
            ["Pair with 700", "NIMS (700) + NRF (800) + ICS (100/200) is a common stack for many agencies."],
        ],
        [
            ["IS-800 covers?", "The National Response Framework."],
            ["Why it matters to fire/EMS?", "Large incidents bring partners who use NRF/NIMS language."],
            ["Local plans still?", "Yes. NRF does not replace department SOP."],
            ["Certificate from?", "Current FEMA IS-800 course."],
            ["Related?", "IS-700 NIMS and ICS-100/200 for on-scene work."],
            ["ESF in one line?", "A way to group capabilities (like firefighting or health) during national response."],
        ],
        [
            q("IS-800 is:", ["A pump hydraulics course", "The NRF independent study course", "The same as Firefighter I"], 1, "Know which course you need."),
            q("The NRF replaces local fire SOP:", ["True", "False", "Only on Tuesdays"], 1, "Local plans remain controlling for your department."),
            q("A common credential stack is:", ["Only IS-800", "ICS-100/200 plus IS-700 and IS-800 as required by the agency", "None of the FEMA courses"], 1, "Agencies publish the stack they want."),
            q("FireOpsSim provides:", ["The FEMA final exam", "Context and a link to the official course", "Federal resource ordering authority"], 1, "Take the official IS-800."),
        ],
        ["Complete current IS-800.d (or successor).", "Keep ICS and NIMS current too if your agency requires the stack.", "File certificates in Career Road."],
        [
            ["ICS/NIMS hub", "/ics-nims-training.html?cert=is_800"],
            ["FEMA IS-800", "https://training.fema.gov/is/courseoverview.aspx?code=IS-800.d"],
            ["FEMA course list", "https://training.fema.gov/is/crslist.aspx"],
        ],
    ),
}


def main():
    out = {
        "schemaVersion": 1,
        "updatedAt": "2026-08-20",
        "disclaimer": "Interactive FireOpsSim study decks are preparation/reference only. They are not official skill sheets, provider cards, or FEMA certificates. Verify department SOPs, state/AHJ rules, medical direction, adopted codes, manufacturer procedures, and current issuer/FEMA course editions.",
        "decks": DECKS,
    }
    path = ROOT / "study-data" / "cert-study.json"
    path.write_text(json.dumps(out, indent=2) + "\n")
    print(f"Wrote {len(DECKS)} decks to {path}")


if __name__ == "__main__":
    main()
